Repository DSpace/dspace-angular, pull requests merged in 2020-09, with the labels that each got.

#855 Removal of email option for the curation script
  src/app/curation-form/curation-form.component.spec.ts
  src/app/curation-form/curation-form.component.ts
Labels: 1 APPROVAL, tools: curation-tasks

#853 844: Fix file upload to use section ID instead of 'upload'
  src/app/submission/sections/upload/section-upload.component.html
  src/app/submission/sections/upload/section-upload.component.spec.ts
Labels: 1 APPROVAL, e/3, quick win

#715 DS-4515: Start new submission via Search or ID Lookup (i.e. submit external source)
  src/app/+import-external-page/import-external-page.component.html
  src/app/+import-external-page/import-external-page.component.scss
  src/app/+import-external-page/import-external-page.component.spec.ts
  src/app/+import-external-page/import-external-page.component.ts
  src/app/+import-external-page/import-external-page.module.ts
  src/app/+import-external-page/import-external-routing.module.ts
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.html
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.spec.ts
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.ts
  src/app/app-routing.module.ts
  src/app/core/data/external-source.service.ts
  src/app/shared/collection-dropdown/collection-dropdown.component.ts
  src/app/shared/mocks/external-source.service.mock.ts
  src/app/shared/shared.module.ts
  src/app/shared/testing/submission-service.stub.ts
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.html
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.scss
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.spec.ts
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.ts
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.html
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.scss
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.spec.ts
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.ts
  src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.html
  src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.scss
  src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.spec.ts
  src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.ts
  src/app/submission/import-external/submission-import-external.component.html
  src/app/submission/import-external/submission-import-external.component.scss
  src/app/submission/import-external/submission-import-external.component.spec.ts
  src/app/submission/import-external/submission-import-external.component.ts
  src/app/submission/submission.module.ts
  src/app/submission/submission.service.spec.ts
  src/app/submission/submission.service.ts
  src/assets/i18n/en.json5
Labels: component: submission, new feature

#857 Issue#819
  src/app/core/locale/locale.service.ts
Labels: bug

#863 Fixes for preboot and SSR error handling
  server.ts
Labels: 1 APPROVAL

#856 Hard redirect after log in
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/auth/auth-blocking.guard.spec.ts
  src/app/core/auth/auth-blocking.guard.ts
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.effects.ts
  src/app/core/auth/auth.reducer.spec.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/authenticated.guard.ts
  src/app/core/auth/selectors.ts
  src/app/core/auth/server-auth.service.ts
  src/app/core/core.module.ts
  src/app/core/reload/reload.guard.spec.ts
  src/app/core/reload/reload.guard.ts
  src/app/core/services/browser-hard-redirect.service.spec.ts
  src/app/core/services/browser-hard-redirect.service.ts
  src/app/core/services/hard-redirect.service.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts
  src/app/shared/impersonate-navbar/impersonate-navbar.component.spec.ts
  src/app/shared/log-in/container/log-in-container.component.spec.ts
  src/app/shared/log-in/container/log-in-container.component.ts
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.spec.ts
  src/app/shared/log-in/log-in.component.ts
  src/app/shared/log-in/methods/password/log-in-password.component.spec.ts
  src/app/shared/log-in/methods/password/log-in-password.component.ts
  src/app/shared/log-in/methods/shibboleth/log-in-shibboleth.component.spec.ts
  src/app/shared/log-in/methods/shibboleth/log-in-shibboleth.component.ts
  src/app/shared/testing/auth-service.stub.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
Labels: high priority

#871 Ensure CSR fallback only happens on actual errors
  server.ts
Labels: 1 APPROVAL

#872 Switch from Coveralls.io to Codecov.io
  .travis.yml
  README.md
  package.json
  yarn.lock
Labels: 1 APPROVAL, code task, improvement

#873 Fix bug concerning bistream pagination on the item page
  src/app/+item-page/full/field-components/file-section/full-file-section.component.html
  src/app/+item-page/full/field-components/file-section/full-file-section.component.spec.ts
  src/app/+item-page/full/field-components/file-section/full-file-section.component.ts
  src/app/+item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/+item-page/simple/field-components/file-section/file-section.component.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/data/bundle-data.service.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug

#868 Google scholar fixes
  docs/Configuration.md
  scripts/set-env.ts
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
  src/app/core/services/browser-hard-redirect.service.spec.ts
  src/app/core/services/browser-hard-redirect.service.ts
  src/app/core/services/hard-redirect.service.spec.ts
  src/app/core/services/hard-redirect.service.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/shared/file-download-link/file-download-link.component.spec.ts
  src/app/shared/file-download-link/file-download-link.component.ts
  src/config/global-config.interface.ts
  src/environments/environment.common.ts
Labels: 1 APPROVAL, high priority

#878 Remove circular dependencies part 2
  .github/pull_request_template.md
  src/app/core/shared/operators.ts
  src/app/info/info-routing-paths.ts
  src/app/info/info-routing.module.ts
Labels: 1 APPROVAL

#877 remove remaining uses of /api in the rest namespace
  .travis.yml
  docker/environment.dev.ts
  docs/Configuration.md
  src/environments/environment.common.ts
  src/environments/environment.template.ts
Labels: 1 APPROVAL
