Repository DSpace/dspace-angular, pull requests merged in 2020-08, with the labels that each got.

#724 DS-4514 start a new submission via file
  src/app/+my-dspace-page/collection-selector/collection-selector.component.html
  src/app/+my-dspace-page/collection-selector/collection-selector.component.scss
  src/app/+my-dspace-page/collection-selector/collection-selector.component.spec.ts
  src/app/+my-dspace-page/collection-selector/collection-selector.component.ts
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.html
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.spec.ts
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.ts
  src/app/+my-dspace-page/my-dspace-page.module.ts
  src/app/shared/uploader/uploader-error.model.ts
  src/app/shared/uploader/uploader-options.model.ts
  src/app/shared/uploader/uploader.component.ts
  src/assets/i18n/en.json5
Labels: e/24

#830 Fix issue with repeatable scrollable dropdowns in the submission
  src/app/shared/form/form.component.ts
  src/app/submission/sections/form/section-form-operations.service.ts
Labels: 1 APPROVAL, bug

#829 Put dynamic workflowgroup links on Collections in an array
  src/app/+collection-page/edit-collection-page/collection-roles/collection-roles.component.spec.ts
  src/app/+collection-page/edit-collection-page/collection-roles/collection-roles.component.ts
  src/app/+community-page/edit-community-page/community-roles/community-roles.component.html
  src/app/+community-page/edit-community-page/community-roles/community-roles.component.ts
  src/app/core/eperson/group-data.service.ts
  src/app/core/shared/collection.model.ts
  src/app/core/shared/community.model.ts
  src/app/core/shared/hal-resource.model.ts
  src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.spec.ts
  src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.ts
  src/app/shared/comcol-forms/edit-comcol-page/comcol-role/comcol-role.ts
Labels: 1 APPROVAL

#825 Add robots.txt
  angular.json
  package.json
  scripts/set-env.ts
  server.ts
  src/app/core/shared/hal-endpoint.service.spec.ts
  src/app/core/shared/hal-endpoint.service.ts
  src/robots.txt
  webpack.config.ts
  webpack/webpack.browser.ts
  webpack/webpack.common.ts
  webpack/webpack.prod.ts
  webpack/webpack.test.ts
  yarn.lock
Labels: 1 APPROVAL

#841 Hide EPerson search section in the edit mode
  src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.html
  src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.spec.ts
Labels: 1 APPROVAL, bug

#845 Support multiple dso type values in discovery
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts
  src/app/+collection-page/collection-page.component.ts
  src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.ts
  src/app/+item-page/edit-item-page/item-move/item-move.component.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.spec.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/create-collection-parent-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.html
  src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.ts
  src/app/shared/dso-selector/modal-wrappers/edit-collection-selector/edit-collection-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/edit-community-selector/edit-community-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/edit-item-selector/edit-item-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
  src/app/shared/search/paginated-search-options.model.spec.ts
  src/app/shared/search/paginated-search-options.model.ts
  src/app/shared/search/search-options.model.spec.ts
  src/app/shared/search/search-options.model.ts
  src/app/statistics/statistics.service.spec.ts
  src/app/statistics/statistics.service.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, component: Discovery, improvement
