Repository DSpace/dspace-angular, pull requests merged in 2020-02, with the labels that each got.

#574 DS-4380 and DS-4257: Minor updates to Docker configs for JDK11 and new URL configs
  docker/docker-compose-rest.yml
  docker/docker-compose-travis.yml
  docker/local.cfg
Labels: enhancement

#586 [Docker] .dockerignore doesn't ignore "node_modules"
  .dockerignore
Labels: bug

#597 fix Submission cannot be completed #592
  src/app/+admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/+admin/admin-registries/bitstream-formats/bitstream-formats.component.ts
  src/app/+item-page/edit-item-page/item-delete/item-delete.component.spec.ts
  src/app/+item-page/edit-item-page/item-delete/item-delete.component.ts
  src/app/app.module.ts
  src/app/core/data/bitstream-format-data.service.spec.ts
  src/app/core/data/bitstream-format-data.service.ts
  src/app/core/data/data.service.ts
  src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.spec.ts
  src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.spec.ts
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.ts
  src/app/submission/edit/submission-edit.component.spec.ts
  src/app/submission/edit/submission-edit.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts
  src/app/submission/sections/upload/section-upload.component.ts
  src/app/submission/submit/submission-submit.component.spec.ts
  src/app/submission/submit/submission-submit.component.ts
Labels: bug

#591 Breadcrumbs
  resources/i18n/en.json5
  src/app/+browse-by/+browse-by-metadata-page/browse-by-metadata-page.component.spec.ts
  src/app/+browse-by/browse-by-dso-breadcrumb.resolver.ts
  src/app/+browse-by/browse-by-guard.ts
  src/app/+browse-by/browse-by-i18n-breadcrumb.resolver.ts
  src/app/+browse-by/browse-by-routing.module.ts
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts
  src/app/+collection-page/collection-page-routing.module.ts
  src/app/+collection-page/collection-page.component.ts
  src/app/+collection-page/edit-collection-page/edit-collection-page.routing.module.ts
  src/app/+community-page/community-page-routing.module.ts
  src/app/+community-page/community-page.component.ts
  src/app/+community-page/edit-community-page/edit-community-page.routing.module.ts
  src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts
  src/app/+item-page/item-page-routing.module.ts
  src/app/+item-page/item-page.resolver.ts
  src/app/+login-page/login-page-routing.module.ts
  src/app/+search-page/search-page-routing.module.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/breadcrumbs/breadcrumb/breadcrumb-config.model.ts
  src/app/breadcrumbs/breadcrumb/breadcrumb.model.ts
  src/app/breadcrumbs/breadcrumbs.component.html
  src/app/breadcrumbs/breadcrumbs.component.scss
  src/app/breadcrumbs/breadcrumbs.component.spec.ts
  src/app/breadcrumbs/breadcrumbs.component.ts
  src/app/core/breadcrumbs/breadcrumbs.service.ts
  src/app/core/breadcrumbs/collection-breadcrumb.resolver.ts
  src/app/core/breadcrumbs/community-breadcrumb.resolver.ts
  src/app/core/breadcrumbs/dso-breadcrumb.resolver.spec.ts
  src/app/core/breadcrumbs/dso-breadcrumb.resolver.ts
  src/app/core/breadcrumbs/dso-breadcrumbs.service.spec.ts
  src/app/core/breadcrumbs/dso-breadcrumbs.service.ts
  src/app/core/breadcrumbs/dso-name.service.spec.ts
  src/app/core/breadcrumbs/dso-name.service.ts
  src/app/core/breadcrumbs/i18n-breadcrumb.resolver.spec.ts
  src/app/core/breadcrumbs/i18n-breadcrumb.resolver.ts
  src/app/core/breadcrumbs/i18n-breadcrumbs.service.spec.ts
  src/app/core/breadcrumbs/i18n-breadcrumbs.service.ts
  src/app/core/breadcrumbs/item-breadcrumb.resolver.ts
  src/app/core/cache/builders/remote-data-build.service.ts
  src/app/core/data/remote-data.ts
  src/app/core/metadata/metadata.service.ts
  src/app/core/shared/child-hal-resource.model.ts
  src/app/core/shared/collection.model.ts
  src/app/core/shared/community.model.ts
  src/app/core/shared/dspace-object.model.ts
  src/app/core/shared/item.model.ts
  src/app/entity-groups/research-entities/metadata-representations/org-unit/org-unit-item-metadata-list-element.component.spec.ts
  src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.spec.ts
  src/app/shared/comcol-page-browse-by/comcol-page-browse-by.component.ts
Labels: needs review
