Repository DSpace/dspace-angular, pull requests merged in 2020-10, with the labels that each got.

#866 Metadata edit patch error fix
  src/app/+item-page/edit-item-page/item-metadata/item-metadata.component.spec.ts
  src/app/+item-page/edit-item-page/item-metadata/item-metadata.component.ts
  src/app/core/cache/object-cache.service.ts
  src/app/core/data/item-template-data.service.ts
  src/app/core/data/object-updates/object-updates.actions.ts
  src/app/core/data/object-updates/object-updates.reducer.spec.ts
  src/app/core/data/object-updates/object-updates.reducer.ts
  src/app/core/data/object-updates/object-updates.service.spec.ts
  src/app/core/data/object-updates/object-updates.service.ts
  src/app/core/data/object-updates/patch-operation-service/metadata-patch-operation.service.spec.ts
  src/app/core/data/object-updates/patch-operation-service/metadata-patch-operation.service.ts
  src/app/core/data/object-updates/patch-operation-service/operations/metadata/metadata-patch-add-operation.model.ts
  src/app/core/data/object-updates/patch-operation-service/operations/metadata/metadata-patch-operation.model.ts
  src/app/core/data/object-updates/patch-operation-service/operations/metadata/metadata-patch-remove-operation.model.ts
  src/app/core/data/object-updates/patch-operation-service/operations/metadata/metadata-patch-replace-operation.model.ts
  src/app/core/data/object-updates/patch-operation-service/patch-operation.service.ts
  src/app/core/data/update-data.service.ts
  src/assets/i18n/en.json5
Labels: bug

#874 Delete eperson
  src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.html
  src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.spec.ts
  src/app/+admin/admin-access-control/epeople-registry/epeople-registry.component.ts
  src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/core/dspace-rest-v2/dspace-rest-v2.service.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/eperson/models/eperson-dto.model.ts
  src/assets/i18n/en.json5
Labels: high priority

#901 #895 fix grid layout
  src/app/shared/object-grid/object-grid.component.scss
Labels: 1 APPROVAL, bug, component: Discovery

#881 Back link on bitstream edit page
  src/app/+bitstream-page/bitstream-page.resolver.ts
  src/app/+bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts
  src/app/+bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/app/core/shared/bitstream.model.ts
  src/app/core/shared/bundle.model.ts
Labels: 1 APPROVAL, bug, component: Item

#913 Fix grid search result shadows
  src/app/+admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-grid-element/workflow-item/workflow-item-search-result-admin-workflow-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/search-result-grid-element.component.ts
Labels: 1 APPROVAL, bug, component: Discovery, usability

#891 Fix DSO 404 pages
  src/app/+collection-page/collection-page.component.ts
  src/app/+community-page/community-page.component.ts
  src/app/+item-page/simple/item-page.component.ts
  src/app/app-routing-paths.ts
  src/app/core/breadcrumbs/dso-breadcrumb.resolver.ts
  src/app/core/shared/operators.spec.ts
  src/app/core/shared/operators.ts
  src/app/process-page/detail/process-detail.component.ts
  src/app/statistics-page/statistics-page/statistics-page.component.ts
Labels: 1 APPROVAL, bug

#894 miscellaneous fixes for import from external source page
  src/app/shared/mocks/external-source.service.mock.ts
  src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.scss
  src/app/submission/import-external/import-external-searchbar/submission-import-external-searchbar.component.ts
  src/app/submission/import-external/submission-import-external.component.html
  src/app/submission/import-external/submission-import-external.component.spec.ts
  src/app/submission/import-external/submission-import-external.component.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug
