Repository DSpace/dspace-angular, pull requests merged in 2020-12, with the labels that each got.

#969 Sync Docker compose scripts with backend (DSpace/DSpace)
  docker/README.md
  docker/cli.assetstore.yml
  docker/cli.ingest.yml
  docker/cli.yml
  docker/db.entities.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
  docker/docker-compose.yml
Labels: bug, code task

#952 Filter queries using correct operators
  src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.ts
  src/app/shared/search/search-labels/search-labels.component.ts
  src/app/shared/search/search.utils.spec.ts
  src/app/shared/search/search.utils.ts
Labels: 1 APPROVAL, bug

#967 Item view relationship query fix
  src/app/+item-page/simple/related-entities/related-entities-search/related-entities-search.component.spec.ts
  src/app/shared/utils/relation-query.utils.spec.ts
  src/app/shared/utils/relation-query.utils.ts
Labels: 1 APPROVAL, quick win

#937 Comcol resource policies
  src/app/+collection-page/edit-collection-page/collection-authorizations/collection-authorizations.component.html
  src/app/+collection-page/edit-collection-page/collection-authorizations/collection-authorizations.component.spec.ts
  src/app/+collection-page/edit-collection-page/collection-authorizations/collection-authorizations.component.ts
  src/app/+collection-page/edit-collection-page/edit-collection-page.module.ts
  src/app/+collection-page/edit-collection-page/edit-collection-page.routing.module.ts
  src/app/+community-page/edit-community-page/community-authorizations/community-authorizations.component.html
  src/app/+community-page/edit-community-page/community-authorizations/community-authorizations.component.spec.ts
  src/app/+community-page/edit-community-page/community-authorizations/community-authorizations.component.ts
  src/app/+community-page/edit-community-page/edit-community-page.module.ts
  src/app/+community-page/edit-community-page/edit-community-page.routing.module.ts
  src/app/+item-page/edit-item-page/edit-item-page.module.ts
  src/app/core/shared/operators.ts
  src/app/shared/resource-policies/create/resource-policy-create.component.spec.ts
  src/app/shared/resource-policies/create/resource-policy-create.component.ts
  src/app/shared/resource-policies/edit/resource-policy-edit.component.spec.ts
  src/app/shared/resource-policies/edit/resource-policy-edit.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
Labels: authorization, component: Collection, component: Community

#965 issue 964 properly impl getEntityTypeByLabel
  src/app/core/data/entity-type.service.ts
Labels: 1 APPROVAL
