Repository DSpace/dspace-angular, pull requests merged in 2020-07, with the labels that each got.

#687 New User Registration
  src/app/app-routing.module.ts
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.effects.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/auth.service.ts
  src/app/core/cache/response.models.ts
  src/app/core/core.module.ts
  src/app/core/data/eperson-registration.service.spec.ts
  src/app/core/data/eperson-registration.service.ts
  src/app/core/data/registration-response-parsing.service.spec.ts
  src/app/core/data/registration-response-parsing.service.ts
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/eperson/models/eperson.model.ts
  src/app/core/shared/registration.model.ts
  src/app/register-page/create-profile/confirmed.validator.spec.ts
  src/app/register-page/create-profile/confirmed.validator.ts
  src/app/register-page/create-profile/create-profile.component.html
  src/app/register-page/create-profile/create-profile.component.spec.ts
  src/app/register-page/create-profile/create-profile.component.ts
  src/app/register-page/register-email/register-email.component.html
  src/app/register-page/register-email/register-email.component.spec.ts
  src/app/register-page/register-email/register-email.component.ts
  src/app/register-page/register-page-routing.module.ts
  src/app/register-page/register-page.module.ts
  src/app/register-page/registration.resolver.spec.ts
  src/app/register-page/registration.resolver.ts
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.spec.ts
  src/app/shared/log-in/log-in.component.ts
  src/assets/i18n/en.json5
Labels: authentication: password, high priority

#716 Authorization for downloads of restricted bitstreams
  src/app/+item-page/full/field-components/file-section/full-file-section.component.html
  src/app/+item-page/simple/field-components/file-section/file-section.component.html
  src/app/core/auth/auth-request.service.ts
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/token-response-parsing.service.spec.ts
  src/app/core/auth/token-response-parsing.service.ts
  src/app/core/cache/response.models.ts
  src/app/core/core.module.ts
  src/app/core/data/request.models.ts
  src/app/core/shared/file.service.ts
  src/app/shared/file-download-link/file-download-link.component.html
  src/app/shared/file-download-link/file-download-link.component.scss
  src/app/shared/file-download-link/file-download-link.component.spec.ts
  src/app/shared/file-download-link/file-download-link.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/testing/auth-request-service.stub.ts
Labels: 1 APPROVAL, authorization, high priority

#703 Cc license submission step
  src/app/community-list-page/community-list-service.spec.ts
  src/app/core/core.module.ts
  src/app/core/shared/hal-resource.model.ts
  src/app/core/submission/models/submission-cc-licence-link.resource-type.ts
  src/app/core/submission/models/submission-cc-licence.resource-type.ts
  src/app/core/submission/models/submission-cc-license-url.model.ts
  src/app/core/submission/models/submission-cc-license.model.ts
  src/app/core/submission/models/workspaceitem-section-cc-license.model.ts
  src/app/core/submission/models/workspaceitem-sections.model.ts
  src/app/core/submission/submission-cc-license-data.service.ts
  src/app/core/submission/submission-cc-license-url-data.service.ts
  src/app/shared/ds-select/ds-select.component.html
  src/app/shared/ds-select/ds-select.component.scss
  src/app/shared/ds-select/ds-select.component.spec.ts
  src/app/shared/ds-select/ds-select.component.ts
  src/app/shared/shared.module.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.scss
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts
  src/app/submission/submission.module.ts
  src/assets/i18n/en.json5
Labels: component: submission, high priority

#749 Edit collection item template
  src/app/+admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.spec.ts
  src/app/+admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.ts
  src/app/+admin/admin-registries/metadata-schema/metadata-schema.component.spec.ts
  src/app/+admin/admin-registries/metadata-schema/metadata-schema.component.ts
  src/app/+collection-page/collection-page-routing.module.ts
  src/app/+collection-page/collection-page.module.ts
  src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.html
  src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.spec.ts
  src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.ts
  src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.html
  src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.spec.ts
  src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.ts
  src/app/+collection-page/edit-item-template-page/item-template-page.resolver.spec.ts
  src/app/+collection-page/edit-item-template-page/item-template-page.resolver.ts
  src/app/+item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/+item-page/edit-item-page/edit-item-page.module.ts
  src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/+item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html
  src/app/+item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.ts
  src/app/+item-page/edit-item-page/item-metadata/item-metadata.component.html
  src/app/+item-page/edit-item-page/item-metadata/item-metadata.component.spec.ts
  src/app/+item-page/edit-item-page/item-metadata/item-metadata.component.ts
  src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.spec.ts
  src/app/core/core.module.ts
  src/app/core/data/data.service.ts
  src/app/core/data/item-data.service.ts
  src/app/core/data/item-template-data.service.spec.ts
  src/app/core/data/item-template-data.service.ts
  src/app/core/data/metadata-field-data.service.spec.ts
  src/app/core/data/metadata-field-data.service.ts
  src/app/core/data/update-data.service.ts
  src/app/core/metadata/metadata-field.model.ts
  src/app/core/registry/registry.service.spec.ts
  src/app/core/registry/registry.service.ts
  src/app/core/shared/template-item.model.ts
  src/app/core/shared/template-item.resource-type.ts
  src/app/shared/comcol-forms/comcol-form/comcol-form.component.html
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, high priority

#755 Reset scroll position on route change
  src/modules/app/browser-app.module.ts
Labels: 1 APPROVAL, Difficulty: low, accessibility, bug, good first issue, quick win, usability

#714 Language header
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/core.module.ts
  src/app/core/locale/locale.interceptor.spec.ts
  src/app/core/locale/locale.interceptor.ts
  src/app/core/locale/locale.service.spec.ts
  src/app/core/locale/locale.service.ts
  src/app/core/locale/server-locale.service.ts
  src/app/shared/lang-switch/lang-switch.component.spec.ts
  src/app/shared/lang-switch/lang-switch.component.ts
  src/modules/app/server-app.module.ts
Labels: 1 APPROVAL

#760 Move coveralls step to "after_success" in Travis CI
  .travis.yml
  package.json
Labels: bug, configuration

#794 Replace all references to `master` with `main`
  .github/pull_request_template.md
  README.md
  docker/cli.ingest.yml
Labels: code task, configuration

#796 Automatically add new Issues to "DSpace Backlog" project board
  .github/workflows/issue_opened.yml
Labels: code task

#795 Auto Assign new Pull Requests to "main" branch to the PR creator
  .github/workflows/pull_request_opened.yml
Labels: code task

#758 DS 630 - item delete broken
  src/app/+item-page/edit-item-page/item-delete/item-delete.component.ts
  src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.html
  src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/process-page/form/process-form.component.spec.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug

#792 IP Authentication: X-Forwarded-For Interceptor
  src/app/core/auth/server-auth.service.ts
  src/app/core/forward-client-ip/forward-client-ip.interceptor.spec.ts
  src/app/core/forward-client-ip/forward-client-ip.interceptor.ts
  src/modules/app/server-app.module.ts
Labels: 1 APPROVAL, authorization

#717 Features support
  src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/+admin/admin-access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/+admin/admin-sidebar/admin-sidebar.component.spec.ts
  src/app/+admin/admin-sidebar/admin-sidebar.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/data/feature-authorization/authorization-data.service.spec.ts
  src/app/core/data/feature-authorization/authorization-data.service.ts
  src/app/core/data/feature-authorization/authorization-search-params.ts
  src/app/core/data/feature-authorization/authorization-utils.ts
  src/app/core/data/feature-authorization/feature-authorization-guard/feature-authorization.guard.spec.ts
  src/app/core/data/feature-authorization/feature-authorization-guard/feature-authorization.guard.ts
  src/app/core/data/feature-authorization/feature-authorization-guard/site-administrator.guard.ts
  src/app/core/data/feature-authorization/feature-data.service.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/services/server-response.service.ts
  src/app/core/shared/authorization.model.ts
  src/app/core/shared/authorization.resource-type.ts
  src/app/core/shared/feature.model.ts
  src/app/core/shared/feature.resource-type.ts
  src/app/core/shared/operators.ts
  src/app/unauthorized/unauthorized.component.html
  src/app/unauthorized/unauthorized.component.scss
  src/app/unauthorized/unauthorized.component.ts
  src/assets/i18n/en.json5
Labels: e/16, high priority

#799 Curation Task Admin UI
  src/app/+admin/admin-curation-tasks/admin-curation-tasks.component.html
  src/app/+admin/admin-curation-tasks/admin-curation-tasks.component.spec.ts
  src/app/+admin/admin-curation-tasks/admin-curation-tasks.component.ts
  src/app/+admin/admin-routing.module.ts
  src/app/+admin/admin-sidebar/admin-sidebar.component.ts
  src/app/+admin/admin.module.ts
  src/app/+collection-page/edit-collection-page/collection-curate/collection-curate.component.html
  src/app/+collection-page/edit-collection-page/collection-curate/collection-curate.component.spec.ts
  src/app/+collection-page/edit-collection-page/collection-curate/collection-curate.component.ts
  src/app/+community-page/edit-community-page/community-curate/community-curate.component.html
  src/app/+community-page/edit-community-page/community-curate/community-curate.component.spec.ts
  src/app/+community-page/edit-community-page/community-curate/community-curate.component.ts
  src/app/core/core.module.ts
  src/app/core/data/configuration-data.service.spec.ts
  src/app/core/data/configuration-data.service.ts
  src/app/core/shared/config-property.resource-type.ts
  src/app/core/shared/configuration-property.model.ts
  src/app/curation-form/curation-form.component.html
  src/app/curation-form/curation-form.component.spec.ts
  src/app/curation-form/curation-form.component.ts
  src/app/shared/comcol-forms/edit-comcol-page/edit-comcol-page.component.html
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
  src/environments/environment.common.ts
  src/environments/mock-environment.ts
Labels: tools: curation-tasks
