Repository DSpace/dspace-angular, pull requests merged in 2020-06, with the labels that each got.

#693 Fix all outdated references to environment.*.js.
  docker/README.md
  docker/docker-compose.yml
  docker/environment.dev.ts
  docs/Configuration.md
Labels: bug, configuration

#692 Fix minimist vulnerability
  package.json
  postcss.config.js
  yarn.lock
Labels: dependencies

#708 Collection dropdown on MyDSpace & support enable/disable in Submission UI
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.html
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.spec.ts
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.ts
  src/app/core/data/collection-data.service.spec.ts
  src/app/core/data/collection-data.service.ts
  src/app/shared/collection-dropdown/collection-dropdown.component.html
  src/app/shared/collection-dropdown/collection-dropdown.component.scss
  src/app/shared/collection-dropdown/collection-dropdown.component.spec.ts
  src/app/shared/collection-dropdown/collection-dropdown.component.ts
  src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.html
  src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.ts
  src/app/shared/notifications/notifications.service.ts
  src/app/shared/shared.module.ts
  src/app/submission/form/collection/submission-form-collection.component.html
  src/app/submission/form/collection/submission-form-collection.component.spec.ts
  src/app/submission/form/collection/submission-form-collection.component.ts
  src/assets/i18n/en.json5
Labels: component: MyDSpace, component: submission, high priority

#709 Simplify bitstream drag and drop
  src/app/+item-page/edit-item-page/edit-item-page.module.ts
  src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.html
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.html
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.spec.ts
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.ts
  src/app/core/data/bundle-data.service.ts
  src/app/core/data/object-updates/object-updates.actions.ts
  src/app/core/data/object-updates/object-updates.reducer.spec.ts
  src/app/core/data/object-updates/object-updates.reducer.ts
  src/app/core/data/object-updates/object-updates.service.spec.ts
  src/app/core/data/object-updates/object-updates.service.ts
  src/app/core/data/request.service.ts
  src/app/shared/mocks/request.service.mock.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.spec.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.ts
Labels: 1 APPROVAL, component: administrative tools

#723 Wait for async code in beforeEach
  src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/community-list-page/community-list-service.spec.ts
  src/app/shared/mocks/request.service.mock.ts
Labels: bug

#710 Community and Collection Tree fixes
  src/app/+admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.scss
  src/app/community-list-page/community-list-datasource.ts
  src/app/community-list-page/community-list-service.spec.ts
  src/app/community-list-page/community-list-service.ts
  src/app/community-list-page/community-list/community-list.component.spec.ts
  src/app/community-list-page/community-list/community-list.component.ts
  src/app/core/cache/builders/remote-data-build.service.ts
Labels: 1 APPROVAL, high priority
