Repository DSpace/dspace-angular, pull requests merged in 2020-11, with the labels that each got.

#905 bugfix of issue #904
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/publication/publication-search-result-list-element.component.html
Labels: 1 APPROVAL, bug, component: Item

#880 [#879] Clarify the use of the production build script, and when configuration is processed
  .gitignore
  README.md
Labels: improvement

#935 Update Travis to only send coverage reports to codecov *once*
  .travis.yml
Labels: code task

#939 Use codecov bash script instead of codecov node module
  .travis.yml
  package.json
  yarn.lock
Labels: bug, code task

#932 Submission relationship lookup externalsources: Missing i18n labels & other issues
  src/app/core/data/lookup-relation.service.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/external-source-entry/external-source-entry-list-submission-element.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/app/shared/object-collection/shared/importable-list-item-control/importable-list-item-control.component.html
  src/app/shared/object-list/object-list.component.html
  src/assets/i18n/en.json5
Labels: 1 APPROVAL

#946 #945 Clean node at end to avoid rimraf error
  package.json
Labels: bug

#545 Create relationships as an admin in edit item
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.scss
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.html
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.spec.ts
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts
  src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.html
  src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/core/data/entity-type.service.ts
  src/app/core/data/object-updates/object-updates.reducer.ts
  src/app/core/data/object-updates/object-updates.service.ts
  src/app/core/data/relationship.service.ts
  src/app/entity-groups/research-entities/item-list-elements/person/person-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts
  src/app/shared/object-collection/shared/object-collection-element/abstract-listable-element.component.ts
  src/assets/i18n/en.json5
Labels: component: Item, component: administrative tools, component: configurable entities, improvement

#934 Fix for handle redirects
  src/app/core/data/dso-redirect-data.service.ts
Labels: 1 APPROVAL

#926 #674 fix thumbnail
  .editorconfig
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-grid-element/collection-search-result/collection-admin-search-result-grid-element.component.spec.ts
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-grid-element/community-search-result/community-admin-search-result-grid-element.component.spec.ts
  src/app/+item-page/full/full-item-page.component.spec.ts
  src/app/+item-page/simple/item-page.component.spec.ts
  src/app/core/cache/builders/link.service.spec.ts
  src/app/core/cache/builders/link.service.ts
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.html
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.spec.ts
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.ts
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.html
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.spec.ts
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.ts
  src/app/shared/object-grid/grid-thumbnail/grid-thumbnail.component.html
  src/app/shared/object-grid/grid-thumbnail/grid-thumbnail.component.ts
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.ts
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/publication/publication-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/search-result-grid-element.component.ts
Labels: 1 APPROVAL, bug, component: Discovery

#933 Fix security issues reported by LGTM
  package.json
  server.ts
  src/config/global-config.interface.ts
  src/config/ui-server-config.interface.ts
  src/environments/environment.common.ts
  src/environments/mock-environment.ts
  yarn.lock
Labels: 1 APPROVAL

#916 Communities and collections not shown right after creation
  src/app/+collection-page/create-collection-page/create-collection-page.component.spec.ts
  src/app/+collection-page/create-collection-page/create-collection-page.component.ts
  src/app/+collection-page/delete-collection-page/delete-collection-page.component.spec.ts
  src/app/+collection-page/delete-collection-page/delete-collection-page.component.ts
  src/app/+community-page/create-community-page/create-community-page.component.spec.ts
  src/app/+community-page/create-community-page/create-community-page.component.ts
  src/app/+community-page/delete-community-page/delete-community-page.component.spec.ts
  src/app/+community-page/delete-community-page/delete-community-page.component.ts
  src/app/core/data/comcol-data.service.spec.ts
  src/app/core/data/comcol-data.service.ts
  src/app/core/data/remote-data.ts
  src/app/core/shared/operators.ts
  src/app/shared/comcol-forms/create-comcol-page/create-comcol-page.component.spec.ts
  src/app/shared/comcol-forms/create-comcol-page/create-comcol-page.component.ts
  src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.spec.ts
  src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts
  src/app/shared/remote-data.utils.ts
Labels: bug, component: Collection, component: Community

#944 Fix com/col tree issues (#899 & #908)
  src/app/community-list-page/community-list-datasource.ts
  src/app/community-list-page/community-list-service.ts
  src/app/community-list-page/community-list/community-list.component.html
  src/app/community-list-page/community-list/community-list.component.ts
Labels: 1 APPROVAL

#953 Switch codecov 'patch' checks to informational only
  .codecov.yml
Labels: code task

#942 Remove workaround for baseUrl ending in /api
  scripts/set-env.ts
Labels: 1 APPROVAL

#929 Issue 2988: Password (re)set for eperson with add PatchOperation
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
Labels: 1 APPROVAL, authentication: general, bug

#827 Support for process output on detail page
  src/app/core/shared/process-output.resource-type.ts
  src/app/process-page/detail/process-detail.component.html
  src/app/process-page/detail/process-detail.component.spec.ts
  src/app/process-page/detail/process-detail.component.ts
  src/app/process-page/processes/process.model.ts
  src/app/shared/mocks/auth.service.mock.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL

#956 Add CI to Github via Actions (based on Travis CI config)
  .github/workflows/build.yml
  .travis.yml
  docker/docker-compose-ci.yml
Labels: 1 APPROVAL, code task, high priority

#959 Update build.yml to not limit by branch
  .github/workflows/build.yml
Labels: 1 APPROVAL, code task

#954 replaced orcidV2 label keys with orcid
  src/assets/i18n/ar.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
Labels: 1 APPROVAL, i18n / l10n
