Repository DSpace/dspace-angular, pull requests merged in 2021-11, with the labels that each got.

#1398 Fix menu icon i18n messages
  src/assets/i18n/en.json5
Labels: i18n / l10n, 1 APPROVAL

#1397 Fix issue with request a copy functionality route
  src/app/item-page/item-page-routing.module.ts
Labels: 1 APPROVAL

#1401 Sync with DSpace/DSpace docker-compose setup
  docker/docker-compose-rest.yml
Labels: bug, 1 APPROVAL, backend: Docker

#1400 Disable CLI analytics by default
  angular.json
Labels: code task, 1 APPROVAL

#1411 Add a config:dev:check:rest option for checking dev environment settings
  package.json
Labels: improvement, code task, 1 APPROVAL

#1406 group creation validator
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/access-control/group-registry/group-form/validators/group-exists.validator.ts
  src/assets/i18n/en.json5
Labels: bug, error handling, 1 APPROVAL

#1412 [Issue 1410] Production build
  angular.json
  package.json
  server.ts
  src/app/breadcrumbs/breadcrumbs.component.spec.ts
  src/app/breadcrumbs/breadcrumbs.component.ts
  src/app/collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.ts
  src/app/community-list-page/community-list-datasource.ts
  src/app/core/cache/builders/link.service.ts
  src/app/core/data/eperson-registration.service.spec.ts
  src/app/core/data/href-only-data.service.ts
  src/app/core/pagination/pagination.service.ts
  src/app/core/shared/external-source.model.ts
  src/app/core/shared/file.service.ts
  src/app/core/shared/metadata.models.ts
  src/app/core/shared/metadata.utils.spec.ts
  src/app/core/shared/search/search-configuration.service.ts
  src/app/core/shared/uuid.service.ts
  src/app/core/tasks/claimed-task-data.service.spec.ts
  src/app/core/tasks/pool-task-data.service.spec.ts
  src/app/core/tasks/tasks.service.spec.ts
  src/app/core/xsrf/xsrf.interceptor.ts
  src/app/item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/item-page/mirador-viewer/mirador-viewer.component.ts
  src/app/item-page/mirador-viewer/mirador-viewer.service.ts
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.spec.ts
  src/app/request-copy/deny-request-copy/deny-request-copy.component.ts
  src/app/request-copy/grant-deny-request-copy/grant-deny-request-copy.component.ts
  src/app/request-copy/grant-request-copy/grant-request-copy.component.ts
  src/app/request-copy/request-copy.resolver.ts
  src/app/shared/bitstream-request-a-copy-page/bitstream-request-a-copy-page.component.ts
  src/app/shared/chips/chips.component.ts
  src/app/shared/dso-page/dso-page-edit-button/dso-page-edit-button.component.ts
  src/app/shared/dso-page/dso-page-version-button/dso-page-version-button.component.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
  src/app/shared/metadata-representation/metadata-representation.decorator.spec.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.ts
  src/app/shared/mydspace-actions/claimed-task/reject/claimed-task-actions-reject.component.ts
  src/app/shared/mydspace-actions/mydspace-reloadable-actions.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.ts
  src/app/shared/object-select/collection-select/collection-select.component.spec.ts
  src/app/shared/object-select/object-select/object-select.component.ts
  src/app/shared/testing/utils.test.ts
  src/app/shared/theme-support/theme.service.ts
  src/app/shared/theme-support/themed.component.ts
  src/app/submission/edit/submission-edit.component.ts
  src/ngx-translate-loaders/translate-json5-http.loader.ts
  tsconfig.server.json
  webpack.server.config.js
  webpack/webpack.prod.ts
  yarn.lock
Labels: high priority, code task

#1408 [CST-4903] The start time and end time of the export process are different
  src/app/process-page/detail/process-detail.component.html
  src/app/process-page/detail/process-detail.component.ts
  src/app/process-page/overview/process-overview.component.html
  src/app/process-page/overview/process-overview.component.spec.ts
  src/assets/i18n/en.json5
Labels: bug, usability, 1 APPROVAL

#1413 [CST-4918] Process status remains Running in detail page
  src/app/process-page/process-page.resolver.ts
Labels: bug, 1 APPROVAL
