Repository DSpace/dspace-angular, pull requests merged in 2021-09, with the labels that each got.

#1309 fix the profile page component in the custom theme
  src/app/profile-page/profile-page.module.ts
  src/themes/custom/app/profile-page/profile-page.component.ts
Labels: bug, high priority, themes, 1 APPROVAL

#1301 Switch to Cypress.io for all e2e tests
  .github/workflows/build.yml
  README.md
  angular.json
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/homepage.spec.ts
  cypress/integration/item-page.spec.ts
  cypress/integration/item-statistics.spec.ts
  cypress/integration/pagenotfound.spec.ts
  cypress/integration/search-navbar.spec.ts
  cypress/integration/search-page.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  e2e/protractor-ci.conf.js
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/src/item-statistics/item-statistics.e2e-spec.ts
  e2e/src/item-statistics/item-statistics.po.ts
  e2e/src/pagenotfound/pagenotfound.e2e-spec.ts
  e2e/src/pagenotfound/pagenotfound.po.ts
  e2e/src/search-navbar/search-navbar.e2e-spec.ts
  e2e/src/search-navbar/search-navbar.po.ts
  e2e/src/search-page/search-page.e2e-spec.ts
  e2e/src/search-page/search-page.po.ts
  e2e/tsconfig.json
  package.json
  yarn.lock
Labels: high priority, code task

#1311 Temporarily disable a11y check until random failure for color contrast can be fixed
  cypress/integration/homepage.spec.ts
Labels: bug, testing framework

#1300 Adds support for capturing i18n translation updates within a theme
  package.json
  scripts/merge-i18n-files.ts
  src/themes/custom/assets/i18n/en.json5
Labels: new feature, 1 APPROVAL

#1298 Cannot easily tell similar named EPeople or Groups apart (usability issue)
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/access-control/group-registry/group-form/members-list/members-list.component.html
  src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.html
  src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.ts
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/access-control/group-registry/groups-registry.component.spec.ts
  src/app/access-control/group-registry/groups-registry.component.ts
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/shared/testing/eperson.mock.ts
  src/app/shared/testing/group-mock.ts
  src/assets/i18n/en.json5
Labels: bug, usability, high priority, 1 APPROVAL

#1324 Fixed edit item bitstreams
  src/app/item-page/bitstreams/upload/upload-bitstream.component.spec.ts
  src/app/item-page/bitstreams/upload/upload-bitstream.component.ts
Labels: bug, high priority, 1 APPROVAL, e/2

#1319 edit item metadata fix
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.spec.ts
  src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.html
  src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.spec.ts
  src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.ts
Labels: bug, 1 APPROVAL, component: Item
