Repository DSpace/dspace-angular, pull requests merged in 2021-08, with the labels that each got.

#1283 Update en.json5
  src/assets/i18n/en.json5
Labels: i18n / l10n

#1287 Language attribute on HTML tag
  src/app/core/locale/locale.service.spec.ts
  src/app/core/locale/locale.service.ts
Labels: bug, accessibility, 1 APPROVAL

#1295 Fix sidebar a11y issues
  src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.html
  src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.html
  src/app/admin/admin-sidebar/admin-sidebar.component.scss
  src/app/admin/admin-sidebar/admin-sidebar.component.spec.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.html
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.scss
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.spec.ts
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
  src/app/navbar/navbar-section/navbar-section.component.html
  src/app/navbar/navbar-section/navbar-section.component.ts
  src/app/shared/menu/menu-item/link-menu-item.component.html
  src/app/shared/menu/menu-item/link-menu-item.component.spec.ts
  src/app/shared/menu/menu-item/link-menu-item.component.ts
  src/app/shared/menu/menu-item/onclick-menu-item.component.html
  src/app/shared/menu/menu-item/onclick-menu-item.component.spec.ts
  src/app/shared/menu/menu-item/onclick-menu-item.component.ts
  src/themes/dspace/styles/_global-styles.scss
Labels: bug, accessibility, component: administrative tools, 1 APPROVAL, medium priority, e/12
