Repository DSpace/dspace-angular, pull requests merged in 2021-02, with the labels that each got.

#906 German translation fixes
  src/assets/i18n/de.json5
Labels: i18n / l10n

#834 latvian translation update
  src/assets/i18n/lv.json5
Labels: merge conflict

#968 Meta "generator" tag in page header
  src/app/core/core.module.ts
  src/app/core/data/root-data.service.spec.ts
  src/app/core/data/root-data.service.ts
  src/app/core/data/root.model.ts
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
  src/app/core/shared/hal-endpoint.service.ts
Labels: 1 APPROVAL

#999 Fix issue with import from external source page
  src/app/+import-external-page/import-external-page.module.ts
  src/app/core/data/comcol-data.service.spec.ts
Labels: 1 APPROVAL, bug, tools:external-sources

#983 Collection mapper
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.html
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts
  src/app/+collection-page/collection-page-routing.module.ts
  src/app/+collection-page/edit-collection-page/edit-collection-page.routing.module.ts
  src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts
  src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.html
  src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.spec.ts
  src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, e/3

#977 Enable Customized CSRF Protection in Angular UI
  src/app/app.module.ts
  src/app/core/auth/auth.service.ts
  src/app/core/xsrf/xsrf.interceptor.spec.ts
  src/app/core/xsrf/xsrf.interceptor.ts
Labels: authentication: general, authorization, bug, high priority

#1014 W2p 76634 google analytics tracking id from backend
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/statistics/google-analytics.service.spec.ts
  src/app/statistics/google-analytics.service.ts
  src/config/global-config.interface.ts
  src/environments/environment.common.ts
  src/environments/mock-environment.ts
  src/main.browser.ts
  src/modules/app/browser-app.module.ts
Labels: 1 APPROVAL, configuration, e/1, improvement

#984 Submission external sources limited on metadata field
  src/app/core/data/relationship-type.service.spec.ts
  src/app/core/data/relationship-type.service.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts
  src/app/shared/form/builder/models/relationship-options.model.ts
  src/app/shared/object-list/selectable-list/selectable-list.service.ts
  src/app/submission/submission.module.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, component: configurable entities, e/23, usability

#1017 Fix unnecessary calls when creating/deleting groups
  src/app/+admin/admin-access-control/group-registry/group-form/group-form.component.ts
  src/app/+admin/admin-access-control/group-registry/group-form/members-list/members-list.component.html
  src/app/+admin/admin-access-control/group-registry/group-form/members-list/members-list.component.ts
  src/app/+admin/admin-access-control/group-registry/group-form/subgroup-list/subgroups-list.component.ts
  src/app/+admin/admin-access-control/group-registry/groups-registry.component.html
  src/app/+admin/admin-access-control/group-registry/groups-registry.component.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/eperson/models/eperson-dto.model.ts
  src/app/core/eperson/models/group-dto.model.ts
  src/app/core/eperson/models/group.model.ts
  src/app/core/shared/dspace-object.model.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, authorization, bug

#1022 Fix: Search filter from entity page carries over to discovery
  src/app/+search-page/configuration-search-page.component.spec.ts
  src/app/+search-page/configuration-search-page.component.ts
  src/app/+search-page/search.component.spec.ts
Labels: 1 APPROVAL, bug

#1015 fix #869 Submission embargo bug
  src/app/core/config/models/config-access-condition-option.model.ts
  src/app/core/submission/models/submission-upload-file-access-condition.model.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/submission/sections/upload/accessConditions/submission-section-upload-access-conditions.component.html
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
  src/app/submission/sections/upload/section-upload.component.html
  src/app/submission/sections/upload/section-upload.component.spec.ts
  src/app/submission/sections/upload/section-upload.component.ts
Labels: 1 APPROVAL, bug, component: submission

#1031 Comment out Edit Item tabs which are not yet implemented.
  src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts
Labels: 1 APPROVAL, bug

#1033 Cleanup duplicative or incorrect Angular UI i18n keys
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, i18n / l10n

#1038 Remove ng-high-memory & remove Node v10 support
  .github/workflows/build.yml
  README.md
  package.json
Labels: 1 APPROVAL
