Repository DSpace/dspace-angular, pull requests merged in 2021-03, with the labels that each got.

#1024 Add CSRF support to uploader Component
  src/app/+my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.spec.ts
  src/app/core/xsrf/xsrf.interceptor.spec.ts
  src/app/core/xsrf/xsrf.interceptor.ts
  src/app/shared/mocks/http-xsrf-token-extractor.mock.ts
  src/app/shared/uploader/uploader.component.spec.ts
  src/app/shared/uploader/uploader.component.ts
Labels: 1 APPROVAL, bug, high priority

#828 Update pt.json5
  src/assets/i18n/pt.json5
Labels: merge conflict

#1049 Use of embed sizes in the ComCol tree
  src/app/community-list-page/community-list-service.ts
  src/app/core/data/comcol-data.service.ts
  src/app/core/data/community-data.service.ts
  src/app/core/data/data.service.spec.ts
  src/app/core/data/data.service.ts
  src/app/core/data/dspace-rest-response-parsing.service.ts
  src/app/core/index/index.selectors.spec.ts
  src/app/core/index/index.selectors.ts
Labels: 1 APPROVAL, bug

#1040 Environment files merging with overwriteMerge
  scripts/set-env.ts
Labels: 1 APPROVAL, bug, configuration

#1068 Ensure REST API is up/available for e2e tests
  .github/workflows/build.yml
Labels: 1 APPROVAL, bug, code task

#1061 Unclickable title in search list fix
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-list-element/collection-search-result/collection-admin-search-result-list-element.component.spec.ts
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-list-element/community-search-result/community-admin-search-result-list-element.component.spec.ts
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-list-element/item-search-result/item-admin-search-result-list-element.component.spec.ts
  src/app/+admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-list-element/workflow-item/workflow-item-search-result-admin-workflow-list-element.component.spec.ts
  src/app/+admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-list-element/workflow-item/workflow-item-search-result-admin-workflow-list-element.component.ts
  src/app/core/breadcrumbs/dso-name.service.spec.ts
  src/app/core/breadcrumbs/dso-name.service.ts
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-issue/journal-issue-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-issue/journal-issue-search-result-list-element.component.spec.ts
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-volume/journal-volume-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-volume/journal-volume-search-result-list-element.component.spec.ts
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal/journal-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal/journal-search-result-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/org-unit/org-unit-search-result-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/project/project-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/project/project-search-result-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/sidebar-search-list-elements/person/person-sidebar-search-list-element.component.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.spec.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.ts
  src/app/shared/mocks/dso-name.service.mock.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/workflow-item-search-result/workflow-item-search-result-detail-element.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/workspace-item-search-result/workspace-item-search-result-detail-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-approved-search-result/claimed-approved-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-approved-search-result/claimed-approved-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-declined-search-result/claimed-declided-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-declined-search-result/claimed-declined-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/item-search-result/item-search-result-list-element-submission.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.ts
  src/app/shared/object-list/search-result-list-element/collection-search-result/collection-search-result-list-element.component.html
  src/app/shared/object-list/search-result-list-element/collection-search-result/collection-search-result-list-element.component.spec.ts
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.html
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.spec.ts
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.spec.ts
  src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.spec.ts
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, e/4

#1062 Fix trail not showing on item pages
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/breadcrumbs/breadcrumb/breadcrumb-config.model.ts
  src/app/breadcrumbs/breadcrumbs.component.html
  src/app/breadcrumbs/breadcrumbs.component.spec.ts
  src/app/breadcrumbs/breadcrumbs.component.ts
  src/app/breadcrumbs/breadcrumbs.service.spec.ts
  src/app/breadcrumbs/breadcrumbs.service.ts
  src/app/core/breadcrumbs/breadcrumbsProviderService.ts
  src/app/core/breadcrumbs/dso-breadcrumbs.service.ts
  src/app/core/breadcrumbs/i18n-breadcrumbs.service.ts
  src/app/process-page/process-breadcrumbs.service.ts
Labels: 1 APPROVAL, bug, e/4

#1056 Fix issue where stale RemoteData is emitted first
  src/app/core/data/comcol-data.service.spec.ts
  src/app/core/data/data.service.spec.ts
  src/app/core/data/data.service.ts
  src/app/core/tasks/tasks.service.ts
Labels: bug, e/4, high priority

#1077 Fix issue where the themed submission page would crash
  src/app/submission/submit/themed-submission-submit.component.ts
Labels: 1 APPROVAL, high priority

#1064 Bugs on Collection Item Template fix
  src/app/+collection-page/collection-page-routing-paths.ts
  src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.spec.ts
  src/app/+collection-page/edit-collection-page/collection-metadata/collection-metadata.component.ts
  src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.html
  src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.spec.ts
  src/app/+collection-page/edit-item-template-page/edit-item-template-page.component.ts
  src/app/+item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/core/data/item-template-data.service.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, e/6

#1075 Edit item page permissions fixes
  src/app/+item-page/edit-item-page/edit-item-page.component.html
  src/app/+item-page/edit-item-page/edit-item-page.component.spec.ts
  src/app/+item-page/edit-item-page/edit-item-page.component.ts
  src/app/+item-page/edit-item-page/edit-item-page.routing.module.ts
  src/app/+item-page/item-page-edit-metadata.guard.ts
  src/app/+item-page/item-page-routing.module.ts
  src/app/core/data/feature-authorization/feature-authorization-guard/dso-page-feature.guard.spec.ts
  src/app/core/data/feature-authorization/feature-authorization-guard/dso-page-feature.guard.ts
  src/app/shared/dso-page/dso-page-edit-button/dso-page-edit-button.component.html
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, e/2

#1065 Handle redirect for items not working fix
  src/app/+lookup-by-id/lookup-guard.spec.ts
  src/app/+lookup-by-id/lookup-guard.ts
Labels: 1 APPROVAL

#888 #885 media viewer
  package.json
  src/app/+item-page/item-page.module.ts
  src/app/+item-page/media-viewer/media-viewer-image/media-viewer-image.component.html
  src/app/+item-page/media-viewer/media-viewer-image/media-viewer-image.component.scss
  src/app/+item-page/media-viewer/media-viewer-image/media-viewer-image.component.spec.ts
  src/app/+item-page/media-viewer/media-viewer-image/media-viewer-image.component.ts
  src/app/+item-page/media-viewer/media-viewer-video/media-viewer-video.component.html
  src/app/+item-page/media-viewer/media-viewer-video/media-viewer-video.component.scss
  src/app/+item-page/media-viewer/media-viewer-video/media-viewer-video.component.spec.ts
  src/app/+item-page/media-viewer/media-viewer-video/media-viewer-video.component.ts
  src/app/+item-page/media-viewer/media-viewer.component.html
  src/app/+item-page/media-viewer/media-viewer.component.scss
  src/app/+item-page/media-viewer/media-viewer.component.spec.ts
  src/app/+item-page/media-viewer/media-viewer.component.ts
  src/app/+item-page/simple/item-types/publication/publication.component.html
  src/app/+item-page/simple/item-types/shared/item.component.ts
  src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/core/shared/media-viewer-item.model.ts
  src/assets/i18n/en.json5
  src/assets/images/replacement_audio.svg
  src/assets/images/replacement_document.svg
  src/assets/images/replacement_image.svg
  src/assets/images/replacement_video.svg
  src/config/global-config.interface.ts
  src/config/media-viewer-config.interface.ts
  src/environments/environment.common.ts
  src/environments/mock-environment.ts
  src/styles/_global-styles.scss
  yarn.lock
Labels: component: Item, new feature

#1060 Fix or address string escaping / replacement issues reported by LGTM
  src/app/core/auth/auth.interceptor.ts
  src/app/core/shared/metadata.utils.spec.ts
  src/app/core/shared/metadata.utils.ts
Labels: 1 APPROVAL

#1076 UI sends wrong request when creating new metadata field without qualifier
  src/app/core/registry/registry.service.spec.ts
  src/app/core/registry/registry.service.ts
Labels: 1 APPROVAL, bug, e/4
