Repository DSpace/dspace-angular, pull requests merged in 2021-01, with the labels that each got.

#960 Auto-save in new Item Submission form breaks the form
  src/app/core/json-patch/json-patch-operations.service.spec.ts
  src/app/core/json-patch/json-patch-operations.service.ts
  src/app/shared/form/builder/form-builder.service.ts
  src/app/shared/form/form.actions.ts
  src/app/shared/form/form.component.html
  src/app/shared/form/form.component.spec.ts
  src/app/shared/form/form.component.ts
  src/app/shared/form/form.reducer.spec.ts
  src/app/shared/form/form.reducer.ts
  src/app/shared/form/form.service.spec.ts
  src/app/shared/form/form.service.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/shared/testing/sections-service.stub.ts
  src/app/shared/testing/submission-service.stub.ts
  src/app/submission/form/footer/submission-form-footer.component.html
  src/app/submission/form/footer/submission-form-footer.component.spec.ts
  src/app/submission/form/footer/submission-form-footer.component.ts
  src/app/submission/objects/submission-objects.actions.ts
  src/app/submission/objects/submission-objects.effects.spec.ts
  src/app/submission/objects/submission-objects.effects.ts
  src/app/submission/objects/submission-objects.reducer.spec.ts
  src/app/submission/objects/submission-objects.reducer.ts
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
  src/app/submission/sections/sections.service.spec.ts
  src/app/submission/sections/sections.service.ts
  src/app/submission/submission.service.spec.ts
  src/app/submission/submission.service.ts
  src/environments/environment.common.ts
Labels: bug, component: submission, high priority, usability

#972 Private/Withdrawn badges for items everywhere
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-grid-element/item-search-result/item-admin-search-result-grid-element.component.html
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-grid-element/item-search-result/item-admin-search-result-grid-element.component.spec.ts
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-list-element/item-search-result/item-admin-search-result-list-element.component.html
  src/app/+admin/admin-search-page/admin-search-results/admin-search-result-list-element/item-search-result/item-admin-search-result-list-element.component.spec.ts
  src/app/+item-page/full/full-item-page.component.html
  src/app/+item-page/simple/item-page.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-issue/journal-issue-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-volume/journal-volume-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal/journal-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/org-unit/org-unit-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/person/person-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/project/project-search-result-grid-element.component.html
  src/app/shared/item/item-alerts/item-alerts.component.html
  src/app/shared/item/item-alerts/item-alerts.component.scss
  src/app/shared/item/item-alerts/item-alerts.component.spec.ts
  src/app/shared/item/item-alerts/item-alerts.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.html
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL

#996 Update the rest hostname to api7.dspace.org
  README.md
  docs/Configuration.md
  src/environments/environment.common.ts
Labels: 1 APPROVAL, configuration

#979 680 Fix change event reference for recent submission
  src/app/+collection-page/collection-page.component.ts
  src/app/shared/pagination/paginationChangeEvent.interface.ts
Labels: 1 APPROVAL, bug, component: Discovery

#1003 Fix prod mode with preboot disabled
  server.ts
Labels: 1 APPROVAL
