Repository DSpace/dspace-angular, pull requests merged in 2021-06, with the labels that each got.

#1226 Add option to pin to a specific version of Chrome/ChromeDriver in our CI process
  .github/workflows/build.yml
Labels: bug, code task, high priority

#1216 Escape browse by author data requests
  src/app/core/browse/browse.service.spec.ts
  src/app/core/browse/browse.service.ts
Labels: 1 APPROVAL, bug, component: Discovery, medium priority

#1209 Fix the rel name for the submissioncclicenseUrls-search link
  src/app/core/submission/submission-cc-license-url-data.service.ts
Labels: 1 APPROVAL, bug, component: submission

#1212 Fix theme switching issues
  angular.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/root/root.component.html
  src/app/root/root.component.spec.ts
  src/app/root/root.component.ts
  src/app/root/themed-root.component.ts
  src/index.html
  src/styles/_global-styles.scss
  src/styles/startup.scss
Labels: 1 APPROVAL, bug, medium priority, testathon, themes

#1227 Remove references to Testathon & Beta 5 from Demo / Default theme
  src/themes/dspace/app/+home-page/home-news/home-news.component.html
Labels: 1 APPROVAL, themes

#1215 Remove duplicate author field
  src/app/+item-page/simple/field-components/specific-field/author/item-page-author-field.component.ts
  src/app/+item-page/simple/item-types/publication/publication.component.html
  src/app/+item-page/simple/item-types/publication/publication.component.spec.ts
  src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.spec.ts
  src/app/+item-page/simple/metadata-representation-list/metadata-representation-list.component.spec.ts
  src/app/+item-page/simple/metadata-representation-list/metadata-representation-list.component.ts
  src/app/core/shared/dspace-object.model.ts
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
Labels: 1 APPROVAL, bug, component: Item, e/2, high priority

#1223 Updated version of the FR wordings
  src/assets/i18n/fr.json5
Labels: i18n / l10n

#1211 Creating a new submission should redirect to workspaceitem edit page
  src/app/submission/submit/submission-submit.component.html
  src/app/submission/submit/submission-submit.component.spec.ts
  src/app/submission/submit/submission-submit.component.ts
Labels: 1 APPROVAL, component: submission, medium priority

#1235 Fix incorrect i18n tags in Collection Delete page
  src/app/+collection-page/delete-collection-page/delete-collection-page.component.html
Labels: 1 APPROVAL, bug, component: Collection, component: administrative tools

#1230 Fix admin sidebar link a11y issues
  src/app/+admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.html
  src/app/+admin/admin-sidebar/admin-sidebar.component.html
  src/app/+admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.html
  src/app/shared/menu/menu-item/link-menu-item.component.html
  src/app/shared/menu/menu-item/onclick-menu-item.component.html
Labels: 1 APPROVAL, accessibility, bug, component: administrative tools, e/2, high priority

#1225 Workflow rejection reasons are not properly encoded
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
Labels: 1 APPROVAL

#1221 Move header changes to dspace theme
  e2e/protractor.conf.js
  src/app/+home-page/home-page-routing.module.ts
  src/app/app.module.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.scss
  src/app/header-nav-wrapper/header-navbar-wrapper.component.html
  src/app/header-nav-wrapper/header-navbar-wrapper.component.scss
  src/app/header-nav-wrapper/themed-header-navbar-wrapper.component.scss
  src/app/header-nav-wrapper/themed-header-navbar-wrapper.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/navbar/navbar-section/navbar-section.component.html
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.scss
  src/app/navbar/navbar.component.ts
  src/app/root/root.component.html
  src/assets/i18n/en.json5
  src/styles/_custom_variables.scss
  src/themes/custom/app/header-nav-wrapper/header-navbar-wrapper.component.html
  src/themes/custom/app/header-nav-wrapper/header-navbar-wrapper.component.scss
  src/themes/custom/app/header-nav-wrapper/header-navbar-wrapper.component.ts
  src/themes/custom/styles/_theme_sass_variable_overrides.scss
  src/themes/custom/theme.module.ts
  src/themes/dspace/app/+home-page/home-news/home-news.component.scss
  src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.html
  src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.scss
  src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.ts
  src/themes/dspace/app/header/header.component.html
  src/themes/dspace/app/header/header.component.scss
  src/themes/dspace/app/header/header.component.ts
  src/themes/dspace/app/navbar/navbar.component.html
  src/themes/dspace/app/navbar/navbar.component.scss
  src/themes/dspace/app/navbar/navbar.component.ts
  src/themes/dspace/styles/_global-styles.scss
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
  src/themes/dspace/theme.module.ts
Labels: 1 APPROVAL, high priority, themes

#1241 Fix contrast issues with grays
  src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.html
  src/app/shared/object-list/type-badge/type-badge.component.html
  src/styles/_bootstrap_variables.scss
  src/themes/custom/styles/_theme_sass_variable_overrides.scss
  src/themes/dspace/styles/_theme_sass_variable_overrides.scss
Labels: 1 APPROVAL, accessibility, bug, e/2, high priority

#1243 Add missing i18n key for Sherpa Journals by ISSN
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, component: MyDSpace, component: submission, configuration

#1219 Fix thumbnail a11y issues
  src/app/+item-page/field-components/metadata-field-wrapper/metadata-field-wrapper.component.html
  src/app/+item-page/field-components/metadata-field-wrapper/metadata-field-wrapper.component.spec.ts
  src/app/+item-page/field-components/metadata-field-wrapper/metadata-field-wrapper.component.ts
  src/app/+item-page/full/field-components/file-section/full-file-section.component.html
  src/app/+item-page/simple/item-types/publication/publication.component.html
  src/app/+item-page/simple/item-types/shared/item.component.ts
  src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-issue/journal-issue-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-volume/journal-volume-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal/journal-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/org-unit/org-unit-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/person/person-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/project/project-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
  src/app/shared/mocks/translate.service.mock.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.html
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.html
  src/app/shared/object-grid/grid-thumbnail/grid-thumbnail.component.html
  src/app/shared/object-grid/grid-thumbnail/grid-thumbnail.component.scss
  src/app/shared/object-grid/grid-thumbnail/grid-thumbnail.component.spec.ts
  src/app/shared/object-grid/grid-thumbnail/grid-thumbnail.component.ts
  src/app/shared/object-grid/object-grid.component.scss
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/shared.module.ts
  src/app/thumbnail/thumbnail.component.html
  src/app/thumbnail/thumbnail.component.scss
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
  src/assets/i18n/en.json5
  src/styles/_custom_variables.scss
Labels: 1 APPROVAL, accessibility, bug, e/5, high priority

#1237 Access Control - Groups only editable by Com/Col admin if group related to com/col & Only site admin access to access control epeople
  src/app/+admin/admin-sidebar/admin-sidebar.component.ts
  src/app/access-control/access-control-routing-paths.ts
  src/app/access-control/access-control-routing.module.ts
  src/app/access-control/group-registry/group-page.guard.spec.ts
  src/app/access-control/group-registry/group-page.guard.ts
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/access-control/group-registry/groups-registry.component.spec.ts
  src/app/access-control/group-registry/groups-registry.component.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/core/eperson/models/group-dto.model.ts
  src/assets/i18n/en.json5
Labels: bug, component: administrative tools, medium priority, testathon

#1201 Fixes for submission forms bugs
  src/app/core/json-patch/builder/json-patch-operations-builder.ts
  src/app/shared/date.util.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker-inline/dynamic-date-picker-inline.component.html
  src/app/shared/form/form.component.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/submission/form/submission-form.component.ts
  src/app/submission/sections/form/section-form-operations.service.spec.ts
  src/app/submission/sections/form/section-form-operations.service.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.scss
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
Labels: bug, component: submission, high priority

#1222 Fix search sidebar a11y issues
  src/app/core/core.module.ts
  src/app/core/shared/sequence.service.spec.ts
  src/app/core/shared/sequence.service.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-suggestions/org-unit-input-suggestions.component.html
  src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.html
  src/app/shared/input-suggestions/input-suggestions.component.ts
  src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-boolean-filter/search-boolean-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.html
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-filter.component.scss
  src/app/shared/search/search-filters/search-filter/search-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.html
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, accessibility, bug, component: Discovery, e/8, high priority

#1245 Disable community/collection delete button while the delete operation is being processed
  src/app/+collection-page/delete-collection-page/delete-collection-page.component.html
  src/app/+community-page/delete-community-page/delete-community-page.component.html
  src/app/shared/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, high priority

#1246 Add pagination to edit relationships tab
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/+item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/core/shared/item.model.ts
Labels: 1 APPROVAL, bug, component: configurable entities, high priority

#1253 Fix issue when switching submission's collection between those with different submission definition
  src/app/submission/form/collection/submission-form-collection.component.spec.ts
  src/app/submission/form/collection/submission-form-collection.component.ts
Labels: 1 APPROVAL, bug, component: submission, medium priority

#1251 Delete pending json patch operations
  src/app/core/json-patch/json-patch-operations.actions.ts
  src/app/core/json-patch/json-patch-operations.reducer.spec.ts
  src/app/core/json-patch/json-patch-operations.reducer.ts
  src/app/core/json-patch/json-patch-operations.service.spec.ts
  src/app/core/json-patch/json-patch-operations.service.ts
  src/app/shared/testing/submission-json-patch-operations-service.stub.ts
  src/app/submission/edit/submission-edit.component.spec.ts
  src/app/submission/edit/submission-edit.component.ts
Labels: 1 APPROVAL, bug, component: submission, medium priority

#1261 Use thumbnail links for items and bitstreams
  src/app/+bitstream-page/bitstream-page.resolver.ts
  src/app/+collection-page/collection-page.resolver.ts
  src/app/+item-page/edit-item-page/item-authorizations/item-authorizations.component.ts
  src/app/+item-page/full/field-components/file-section/full-file-section.component.ts
  src/app/+item-page/item.resolver.ts
  src/app/+item-page/simple/item-types/publication/publication.component.html
  src/app/+item-page/simple/item-types/shared/item.component.ts
  src/app/+item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/+search-page/search.component.ts
  src/app/community-list-page/community-list-service.ts
  src/app/core/cache/builders/link.service.spec.ts
  src/app/core/cache/builders/link.service.ts
  src/app/core/cache/builders/remote-data-build.service.spec.ts
  src/app/core/cache/builders/remote-data-build.service.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/data/data.service.spec.ts
  src/app/core/data/dso-redirect-data.service.spec.ts
  src/app/core/shared/bitstream.model.ts
  src/app/core/shared/item.model.ts
  src/app/core/shared/search/search.service.ts
  src/app/core/submission/vocabularies/vocabulary.service.ts
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-issue/journal-issue-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-volume/journal-volume-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal/journal-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/org-unit/org-unit-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/person/person-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/project/project-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/search-result-grid-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-approved-search-result/claimed-approved-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-declined-search-result/claimed-declined-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.ts
  src/app/shared/utils/follow-link-config.model.ts
  src/app/thumbnail/thumbnail.component.spec.ts
Labels: 1 APPROVAL, e/4, medium priority, new feature

#1244 [CSTPER-144] Fixed issue with authorization request encountered while logging-in with shibboleth
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.effects.spec.ts
  src/app/core/auth/auth.effects.ts
  src/app/core/auth/auth.reducer.spec.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/server-auth.service.ts
  src/app/shared/testing/auth-service.stub.ts
Labels: 1 APPROVAL, authentication: Shibboleth, bug, high priority
