Repository DSpace/dspace-angular, pull requests merged in 2021-07, with the labels that each got.

#1247 Fix move item page
  src/app/+item-page/edit-item-page/item-move/item-move.component.html
  src/app/+item-page/edit-item-page/item-move/item-move.component.spec.ts
  src/app/+item-page/edit-item-page/item-move/item-move.component.ts
  src/app/core/data/item-data.service.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.spec.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts
  src/app/shared/truncatable/truncatable-part/truncatable-part.component.scss
  src/assets/i18n/en.json5
  src/styles/_truncatable-part.component.scss
  src/styles/base-theme.scss
  src/themes/custom/styles/theme.scss
  src/themes/dspace/styles/theme.scss
Labels: 1 APPROVAL, bug, component: Item, e/6, high priority

#1228 Fix issues with meta tags
  src/app/+collection-page/collection-page.component.ts
  src/app/+item-page/full/full-item-page.component.ts
  src/app/+item-page/simple/item-page.component.ts
  src/app/core/core.reducers.ts
  src/app/core/metadata/meta-tag.actions.ts
  src/app/core/metadata/meta-tag.reducer.spec.ts
  src/app/core/metadata/meta-tag.reducer.ts
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
  src/app/shared/mocks/item.mock.ts
Labels: bug, component: SEO, high priority, testathon

#1266 fix bitstream download during submission
  src/app/shared/file-download-link/file-download-link.component.html
  src/app/shared/file-download-link/file-download-link.component.ts
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
Labels: 1 APPROVAL, bug, component: submission

#1240 Improve session timeout UX
  src/app/+browse-by/+browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.effects.ts
  src/app/core/auth/auth.interceptor.ts
  src/app/core/auth/auth.reducer.spec.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/selectors.ts
  src/app/core/utilities/enter-zone.scheduler.ts
  src/app/core/utilities/leave-zone.scheduler.ts
  src/app/root/root.component.ts
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts
  src/app/shared/idle-modal/idle-modal.component.html
  src/app/shared/idle-modal/idle-modal.component.spec.ts
  src/app/shared/idle-modal/idle-modal.component.ts
  src/app/shared/mocks/auth.service.mock.ts
  src/assets/i18n/en.json5
  src/config/auth-config.interfaces.ts
  src/environments/environment.common.ts
  src/environments/mock-environment.ts
Labels: accessibility, bug, e/16, high priority

#1239 Fix hardcoded submission section IDs
  src/app/shared/testing/sections-service.stub.ts
  src/app/submission/form/collection/submission-form-collection.component.spec.ts
  src/app/submission/form/collection/submission-form-collection.component.ts
  src/app/submission/form/submission-form.component.html
  src/app/submission/form/submission-upload-files/submission-upload-files.component.spec.ts
  src/app/submission/form/submission-upload-files/submission-upload-files.component.ts
  src/app/submission/sections/sections.service.spec.ts
  src/app/submission/sections/sections.service.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
Labels: 1 APPROVAL, bug, component: submission

#1249 No way to view an Item when in simple "Approve/Reject" workflow stage
  src/app/+item-page/full/full-item-page.component.html
  src/app/+item-page/full/full-item-page.component.spec.ts
  src/app/+item-page/full/full-item-page.component.ts
  src/app/+item-page/simple/item-page.component.ts
  src/app/+workflowitems-edit-page/item-from-workflow.resolver.spec.ts
  src/app/+workflowitems-edit-page/item-from-workflow.resolver.ts
  src/app/+workflowitems-edit-page/workflowitems-edit-page-routing-paths.ts
  src/app/+workflowitems-edit-page/workflowitems-edit-page-routing.module.ts
  src/app/+workflowitems-edit-page/workflowitems-edit-page.module.ts
  src/app/shared/item/item-versions/item-versions.component.ts
  src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.html
  src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.ts
  src/assets/i18n/en.json5
Labels: bug, component: submission, high priority, merge conflict

#1262 Ensure we are always using UTC dates in the UI, as the backend expects/uses UTC-based dates
  src/app/+browse-by/+browse-by-date-page/browse-by-date-page.component.spec.ts
  src/app/+browse-by/+browse-by-date-page/browse-by-date-page.component.ts
  src/app/shared/date.util.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
Labels: 1 APPROVAL, bug, high priority

#1269 improve positioning of buttons in the submission form
  src/app/submission/form/footer/submission-form-footer.component.html
  src/app/submission/form/footer/submission-form-footer.component.spec.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, component: submission, low priority

#1250 Cannot map new items with Collection Admin
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.html
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts
  src/app/+collection-page/collection-item-mapper/collection-item-mapper.component.ts
  src/app/+item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.spec.ts
  src/app/shared/object-select/collection-select/collection-select.component.spec.ts
  src/app/shared/object-select/collection-select/collection-select.component.ts
  src/app/shared/object-select/item-select/item-select.component.html
  src/app/shared/object-select/item-select/item-select.component.spec.ts
  src/app/shared/object-select/item-select/item-select.component.ts
  src/app/shared/object-select/object-select/object-select.component.ts
Labels: 1 APPROVAL, bug, component: Collection, high priority

#1252 Fix accessibility issues #1172 #1167 #1171
  src/app/+item-page/edit-item-page/item-bitstreams/item-bitstreams.component.scss
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.html
  src/app/+item-page/edit-item-page/item-bitstreams/item-edit-bitstream-drag-handle/item-edit-bitstream-drag-handle.component.html
  src/app/+item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html
  src/app/+item-page/edit-item-page/item-metadata/item-metadata.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/search-navbar/search-navbar.component.html
  src/app/search-navbar/search-navbar.component.scss
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.scss
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker-inline/dynamic-date-picker-inline.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.scss
  src/app/shared/form/form.component.html
  src/app/shared/form/form.component.scss
  src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.html
  src/app/shared/lang-switch/lang-switch.component.html
  src/app/shared/log-in/methods/password/log-in-password.component.html
  src/app/shared/number-picker/number-picker.component.html
  src/app/shared/search-form/search-form.component.html
  src/app/shared/search/search-switch-configuration/search-switch-configuration.component.html
  src/app/shared/uploader/uploader.component.html
  src/app/submission/sections/container/section-container.component.html
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, accessibility, bug, high priority

#1255 Improve logging Angular implementation
  src/app/app.module.ts
  src/app/core/log/log.interceptor.spec.ts
  src/app/core/log/log.interceptor.ts
Labels: 1 APPROVAL, high priority

#1254 Improve error handling during submission
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html
  src/app/shared/form/form.component.ts
  src/app/shared/form/form.reducer.ts
  src/app/shared/form/form.service.ts
  src/app/shared/mocks/form-service.mock.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/shared/testing/sections-service.stub.ts
  src/app/submission/edit/submission-edit.component.html
  src/app/submission/edit/submission-edit.component.ts
  src/app/submission/form/submission-form.component.spec.ts
  src/app/submission/form/submission-form.component.ts
  src/app/submission/form/submission-upload-files/submission-upload-files.component.spec.ts
  src/app/submission/form/submission-upload-files/submission-upload-files.component.ts
  src/app/submission/objects/submission-objects.actions.ts
  src/app/submission/objects/submission-objects.effects.spec.ts
  src/app/submission/objects/submission-objects.effects.ts
  src/app/submission/objects/submission-objects.reducer.spec.ts
  src/app/submission/objects/submission-objects.reducer.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts
  src/app/submission/sections/container/section-container.component.spec.ts
  src/app/submission/sections/form/section-form-operations.service.ts
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
  src/app/submission/sections/license/section-license.component.spec.ts
  src/app/submission/sections/models/section-data.model.ts
  src/app/submission/sections/sections.directive.ts
  src/app/submission/sections/sections.service.spec.ts
  src/app/submission/sections/sections.service.ts
  src/app/submission/sections/upload/section-upload.component.spec.ts
  src/app/submission/selectors.ts
  src/app/submission/submission.service.spec.ts
  src/app/submission/submission.service.ts
  src/app/submission/submit/submission-submit.component.ts
Labels: component: submission, medium priority

#1242 Add support for legacy bitstream download URLs
  src/app/+bitstream-page/bitstream-page-routing.module.ts
  src/app/+bitstream-page/legacy-bitstream-url.resolver.spec.ts
  src/app/+bitstream-page/legacy-bitstream-url.resolver.ts
  src/app/app-routing-paths.ts
  src/app/app-routing.module.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/shared/operators.spec.ts
  src/app/core/shared/operators.ts
Labels: 1 APPROVAL, bug, component: SEO, e/4, high priority, testathon

#1275 #1273 no js issue
  src/app/core/auth/auth.actions.ts
  src/app/core/auth/auth.effects.spec.ts
  src/app/core/auth/auth.effects.ts
  src/app/core/auth/auth.reducer.spec.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/server-auth.service.ts
  src/app/core/data/feature-authorization/authorization-data.service.spec.ts
  src/app/core/data/feature-authorization/authorization-data.service.ts
  src/app/shared/testing/auth-service.stub.ts
Labels: bug, component: SEO, high priority

#1276 Remove unused config params
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
  src/app/core/services/browser-hard-redirect.service.spec.ts
  src/app/core/services/browser-hard-redirect.service.ts
  src/app/core/services/hard-redirect.service.spec.ts
  src/app/core/services/hard-redirect.service.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/config/global-config.interface.ts
  src/environments/environment.common.ts
  src/environments/mock-environment.ts
Labels: 1 APPROVAL, high priority

#1277 Fix timezone issue with test dates
  src/app/shared/resource-policies/form/resource-policy-form.component.spec.ts
  src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
Labels: 1 APPROVAL, code task

#1280 Fix issue where the app wouldn't load for the first request in prod mode
  src/app/core/dspace-rest/dspace-rest.service.ts
  src/app/core/log/log.interceptor.ts
Labels: 1 APPROVAL, bug, high priority

#1282 SEO + SSR fixes: Fix <meta> tag syntax and add a basic test that SSR is working
  .github/workflows/build.yml
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
Labels: bug, high priority

#1264 Update pt-PT.json5
  src/assets/i18n/pt-PT.json5
Labels: i18n / l10n
