Repository DSpace/dspace-angular, pull requests merged in 2021-05, with the labels that each got.

#1139 Fix relationship modal on item page
  src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
Labels: 1 APPROVAL, bug, e/1, medium priority

#1138 Fix date filter bugs
  src/app/+my-dspace-page/my-dspace-configuration.service.spec.ts
  src/app/core/shared/search/search-configuration.service.spec.ts
  src/app/core/shared/search/search-configuration.service.ts
  src/app/shared/search/paginated-search-options.model.spec.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/shared/search/search-options.model.spec.ts
  src/app/shared/search/search-options.model.ts
  src/styles/_custom_variables.scss
Labels: 1 APPROVAL, bug, component: Discovery, e/3, high priority, testathon

#1086 [CST-4009] Discovery result sort options not reflecting what is configured
  src/app/+my-dspace-page/my-dspace-page.component.html
  src/app/+my-dspace-page/my-dspace-page.component.spec.ts
  src/app/+my-dspace-page/my-dspace-page.component.ts
  src/app/+search-page/search.component.html
  src/app/+search-page/search.component.spec.ts
  src/app/+search-page/search.component.ts
  src/app/core/core.module.ts
  src/app/core/shared/search/search-configuration.service.ts
  src/app/core/shared/search/search-filters/search-config.model.ts
  src/app/core/shared/search/search-filters/search-config.resource-type.ts
  src/app/core/shared/search/search.service.spec.ts
  src/app/core/shared/search/search.service.ts
  src/app/shared/search/search-settings/search-settings.component.html
  src/app/shared/search/search-settings/search-settings.component.spec.ts
  src/app/shared/search/search-settings/search-settings.component.ts
  src/app/shared/search/search-sidebar/search-sidebar.component.html
  src/app/shared/search/search-sidebar/search-sidebar.component.ts
  src/assets/i18n/en.json5
Labels: bug, component: Discovery, medium priority

#1146 Fix edit group navigation bug
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
Labels: 1 APPROVAL, bug, component: administrative tools, e/1, high priority, testathon

#1145 Remove menu options for disabled features
  src/app/+admin/admin-sidebar/admin-sidebar.component.ts
Labels: 1 APPROVAL, bug, component: administrative tools, e/1, medium priority, testathon

#1181 Fix dso-selector issues
  src/app/shared/dso-selector/dso-selector/authorized-collection-selector/authorized-collection-selector.component.spec.ts
  src/app/shared/dso-selector/dso-selector/authorized-collection-selector/authorized-collection-selector.component.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.spec.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
  src/assets/i18n/en.json5
Labels: 1 APPROVAL, bug, e/4, medium priority, testathon

#1180 Fix pagination in author lookup window
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.ts
Labels: 1 APPROVAL, bug, component: configurable entities, component: submission, e/3, identifiers: ORCID, medium priority, testathon

#1200 Update metadata import export script params
  src/app/+admin/admin-import-metadata-page/metadata-import-page.component.spec.ts
  src/app/+admin/admin-import-metadata-page/metadata-import-page.component.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
Labels: 1 APPROVAL, component: Collection, e/2, high priority, testathon, tools: export, tools: import, tools:processes

#1182 Fix item-level statistics pages
  e2e/src/item-statistics/item-statistics.e2e-spec.ts
  e2e/src/item-statistics/item-statistics.po.ts
  package.json
  src/app/+item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/+item-page/item-page.resolver.ts
  src/app/+item-page/item.resolver.ts
  src/app/core/breadcrumbs/item-breadcrumb.resolver.ts
  src/app/statistics-page/statistics-page-routing.module.ts
  yarn.lock
Labels: 1 APPROVAL, bug, component: statistics, e/2, medium priority, testathon
