Repository DSpace/dspace-angular, pull requests merged in 2022-10, with the labels that each got.

#1825 MyDSpace support for entity type specific list views
  src/app/core/data/base/base-data.service.ts
  src/app/core/data/base/find-all-data.spec.ts
  src/app/core/data/base/identifiable-data.service.spec.ts
  src/app/core/data/dso-redirect.service.spec.ts
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-issue/journal-issue-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-volume/journal-volume-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal/journal-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/org-unit/org-unit-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/org-unit/org-unit-search-result-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/project/project-search-result-list-element.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.html
  src/app/my-dspace-page/my-dspace-search.module.ts
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.ts
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html
  src/app/shared/search/search.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, component: configurable entities, high priority, new feature, component: MyDSpace, 1 APPROVAL

#1858 Hindi Translation
  config/config.example.yml
  src/assets/i18n/hi.json5
  src/config/default-app-config.ts
Labels: i18n / l10n, 1 APPROVAL

#1812 Fix error validation for required `name` fields in submission
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/ds-dynamic-input.model.ts
  src/app/shared/form/builder/form-builder.service.spec.ts
  src/app/shared/form/builder/form-builder.service.ts
  src/app/shared/form/builder/parsers/concat-field-parser.ts
  src/app/shared/form/form.service.spec.ts
  src/app/shared/form/form.service.ts
  src/app/shared/mocks/form-builder-service.mock.ts
Labels: bug, component: submission, 1 APPROVAL, medium priority, e/3

#1876 Fix z-index issue with thumbnails in item list checkboxes
  src/app/shared/object-list/object-list.component.scss
Labels: high priority, 1 APPROVAL

#1828 Fix for PR#1822 - Adjusted two equality checks for scope type which always return false.
  src/app/core/eperson/models/workspaceitem.resource-type.ts
  src/app/core/submission/models/workspaceitem.model.ts
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
Labels: bug, component: configurable entities, component: workflow, 1 APPROVAL

#1818 New users might be registered in a massive way by a robot
  cypress/support/index.ts
  package.json
  src/app/core/data/eperson-registration.service.spec.ts
  src/app/core/data/eperson-registration.service.ts
  src/app/core/google-recaptcha/google-recaptcha.module.ts
  src/app/core/google-recaptcha/google-recaptcha.service.spec.ts
  src/app/core/google-recaptcha/google-recaptcha.service.ts
  src/app/core/shared/registration.model.ts
  src/app/register-email-form/register-email-form.component.html
  src/app/register-email-form/register-email-form.component.spec.ts
  src/app/register-email-form/register-email-form.component.ts
  src/app/register-email-form/register-email-form.module.ts
  src/app/shared/cookies/browser-klaro.service.spec.ts
  src/app/shared/cookies/browser-klaro.service.ts
  src/app/shared/cookies/klaro-configuration.ts
  src/app/shared/google-recaptcha/google-recaptcha.component.html
  src/app/shared/google-recaptcha/google-recaptcha.component.scss
  src/app/shared/google-recaptcha/google-recaptcha.component.spec.ts
  src/app/shared/google-recaptcha/google-recaptcha.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
  tsconfig.app.json
  tsconfig.server.json
  tsconfig.spec.json
  yarn.lock
Labels: bug, improvement, authentication: general, authentication: password, 1 APPROVAL

#1845 Search/MyDSpace fixes
  src/app/core/end-user-agreement/end-user-agreement-current-user.guard.spec.ts
  src/app/core/orcid/orcid-auth.service.ts
  src/app/core/shared/search/search-filter.service.ts
  src/app/core/shared/search/search.service.ts
  src/app/item-page/edit-item-page/edit-item-page.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/abstract/claimed-task-actions-abstract.component.ts
  src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.html
  src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/claimed-task-actions.component.ts
  src/app/shared/mydspace-actions/claimed-task/switcher/claimed-task-actions-loader.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/switcher/claimed-task-actions-loader.component.ts
  src/app/shared/mydspace-actions/mydspace-reloadable-actions.spec.ts
  src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.html
  src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.spec.ts
  src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.ts
  src/app/shared/object-collection/object-collection.component.html
  src/app/shared/object-collection/object-collection.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts
  src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.html
  src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.spec.ts
  src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/claimed-task-search-result/claimed-task-search-result-detail-element.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/pool-search-result/pool-search-result-detail-element.component.ts
  src/app/shared/object-detail/object-detail.component.html
  src/app/shared/object-detail/object-detail.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.ts
  src/app/shared/object-list/object-list.component.html
  src/app/shared/object-list/object-list.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-wrapper/search-facet-filter-wrapper.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/search/search-filters/search-filters.component.ts
  src/app/shared/search/search-results/search-results.component.html
  src/app/shared/search/search-results/search-results.component.ts
  src/app/shared/search/search-results/themed-search-results.component.ts
  src/app/shared/search/search-sidebar/search-sidebar.component.html
  src/app/shared/search/search-sidebar/search-sidebar.component.ts
  src/app/shared/search/search.component.html
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/submission/form/footer/submission-form-footer.component.spec.ts
Labels: bug, component: Discovery, component: MyDSpace, 1 APPROVAL

#1869 Some translations for pt-BR
  src/assets/i18n/pt-BR.json5
Labels: i18n / l10n

#1881 Fix issue when deleting a member from a group
  src/app/access-control/group-registry/group-form/members-list/members-list.component.ts
  src/app/core/eperson/group-data.service.spec.ts
  src/app/core/eperson/group-data.service.ts
Labels: bug, high priority, authorization

#1886 Fix dual notification when deleting bitstreamformats
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts
Labels: bug, component: administrative tools

#1896 Add missing translations in version 7.4 pt-BR
  src/assets/i18n/pt-BR.json5
Labels: i18n / l10n, 1 APPROVAL

#1895 Fix button translation ...
  src/app/home-page/recent-item-list/recent-item-list.component.html
Labels: bug, quick win, 1 APPROVAL

#1853 Use CSS variables in TypeScript
  src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.spec.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.spec.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.spec.ts
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.reducer.ts
  src/app/core/core.module.ts
  src/app/root/root.component.spec.ts
  src/app/root/root.component.ts
  src/app/shared/host-window.service.ts
  src/app/shared/key-value-pair.model.ts
  src/app/shared/sass-helper/css-variable.actions.ts
  src/app/shared/sass-helper/css-variable.reducer.ts
  src/app/shared/sass-helper/css-variable.service.spec.ts
  src/app/shared/sass-helper/css-variable.service.ts
  src/app/shared/sass-helper/sass-helper.reducer.ts
  src/app/shared/sass-helper/sass-helper.service.ts
  src/app/shared/testing/css-variable-service.stub.ts
  src/modules/app/server-init.service.ts
Labels: bug, themes, 1 APPROVAL

#1922 Issue 1920 - "data-service.decorator.spec.ts" tests fails intermittently
  src/app/core/data/base/data-service.decorator.spec.ts
Labels: bug, 1 APPROVAL, testing framework

#1893 [#1892] Apply type-bind properly to concat fields that are not dynamic arrays
  src/app/shared/form/builder/ds-dynamic-form-ui/models/ds-dynamic-concat.model.ts
Labels: bug, component: submission, quick win, 1 APPROVAL

#1928 Fix missing type-bind relations for checkbox group
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list-checkbox-group.model.ts
Labels: bug, component: submission, 1 APPROVAL

#1903 Replace Moment.js with date-fns
  package.json
  src/app/shared/date.util.spec.ts
  src/app/shared/date.util.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/shared/shared.module.ts
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#1908 Shrink size of Klaro & ban wildcard imports.
  .eslintrc.json
  package.json
  scripts/base-href.ts
  scripts/env-to-yaml.ts
  scripts/serve.ts
  scripts/test-rest.ts
  server.ts
  src/app/app.reducer.ts
  src/app/core/cache/object-cache.reducer.spec.ts
  src/app/core/cache/server-sync-buffer.reducer.spec.ts
  src/app/core/data/object-updates/object-updates.reducer.spec.ts
  src/app/core/data/request.reducer.spec.ts
  src/app/core/index/index.reducer.spec.ts
  src/app/core/index/index.selectors.ts
  src/app/core/json-patch/json-patch-operations.reducer.spec.ts
  src/app/core/router/router.effects.ts
  src/app/navbar/navbar.effects.spec.ts
  src/app/navbar/navbar.effects.ts
  src/app/shared/cookies/browser-klaro.service.spec.ts
  src/app/shared/cookies/browser-klaro.service.ts
  src/app/shared/cookies/klaro-configuration.ts
  src/app/shared/host-window.reducer.spec.ts
  src/app/shared/menu/menu.reducer.spec.ts
  src/app/shared/mocks/dspace-rest/endpoint-mocking-rest.service.ts
  src/app/shared/search/search-filters/search-filter/search-filter.reducer.spec.ts
  src/app/shared/sidebar/sidebar-effects.service.ts
  src/app/shared/sidebar/sidebar.reducer.spec.ts
  src/app/shared/truncatable/truncatable.reducer.spec.ts
  src/app/shared/utils/file-size-pipe.ts
  src/assets/i18n/en.json5
  src/config/config.server.ts
  src/config/config.util.ts
  src/ngx-translate-loaders/translate-server.loader.ts
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#1910 Update pt-BR to replace ficheiro (pt-PT)
  src/assets/i18n/pt-BR.json5
Labels: i18n / l10n, 1 APPROVAL

#1925 Minor fixes related to line breaks & Markdown in metadata fields
  src/app/item-page/field-components/metadata-values/metadata-values.component.html
  src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.ts
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
Labels: bug, improvement, 1 APPROVAL

#1902 Fix issues with user menu on different screen sizes
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.scss
  src/app/navbar/navbar-section/navbar-section.component.html
  src/app/navbar/navbar-section/navbar-section.component.scss
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.scss
  src/app/navbar/navbar.component.spec.ts
  src/app/navbar/navbar.component.ts
  src/app/root/root.component.html
  src/app/shared/animations/slide.ts
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.html
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.ts
  src/assets/i18n/en.json5
  src/themes/dspace/app/navbar/navbar.component.html
  src/themes/dspace/app/navbar/navbar.component.scss
  src/themes/dspace/styles/_global-styles.scss
Labels: bug, usability, 1 APPROVAL

#1878 Add IDs and pagination gear to Bitstream Formats
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
Labels: usability, component: administrative tools, 1 APPROVAL

#1916 Kazakh Translations
  src/assets/i18n/kk.json5
Labels: i18n / l10n, 1 APPROVAL

#1938 GitHub Workflows security hardening (for dspace-angular)
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/issue_opened.yml
  .github/workflows/label_merge_conflicts.yml
Labels: code task

#1912 Listable-object decorator refactor
  src/app/shared/object-collection/shared/listable-object/listable-object.decorator.spec.ts
  src/app/shared/object-collection/shared/listable-object/listable-object.decorator.ts
Labels: bug, themes, 1 APPROVAL

#1919 Search in sidebar/facet don't escape special characters
  src/app/core/shared/search/search.service.spec.ts
  src/app/core/shared/search/search.service.ts
Labels: bug, component: Discovery

#1933 DS-8298: fixes issue where the lastHarvested and message fields were reversed
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.html
Labels: bug, 1 APPROVAL, integration: OAI Harvester
