Repository DSpace/dspace-angular, pull requests merged in 2022-08, with the labels that each got.

#1742 fix missing space between author names MyDspace our submissions #1730
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
Labels: bug, usability, component: MyDSpace, 1 APPROVAL

#1715 Option to disable gdpr / privacy statements
  config/config.example.yml
  src/app/core/end-user-agreement/abstract-end-user-agreement.guard.ts
  src/app/core/end-user-agreement/end-user-agreement-current-user.guard.spec.ts
  src/app/core/end-user-agreement/end-user-agreement-current-user.guard.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.ts
  src/app/info/info-routing.module.ts
  src/app/shared/cookies/browser-klaro.service.ts
  src/assets/i18n/en.json5
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/info-config.interface.ts
  src/environments/environment.test.ts
Labels: bug, improvement, configuration, 1 APPROVAL, medium priority, privacy

#1773 Remove/replace gendered language in code comments
  README.md
  src/app/core/data/feature-authorization/feature-authorization-guard/some-feature-authorization.guard.ts
  src/app/core/data/processes/process-data.service.ts
  src/app/core/end-user-agreement/end-user-agreement.service.ts
  src/app/core/shared/metadata.models.ts
  src/app/health-page/health-panel/health-status/health-status.component.ts
  src/app/info/end-user-agreement/end-user-agreement.component.ts
  src/app/profile-page/profile-page-researcher-form/profile-page-researcher-form.component.ts
  src/app/shared/cookies/klaro-configuration.ts
  src/app/shared/object-list/metadata-representation-list-element/item/item-metadata-list-element.component.ts
Labels: code task

#1756 Add admin option to export all fields in the metadata export
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
Labels: improvement, tools: export, 1 APPROVAL

#1768 Moved 3rd party css imports to separate file
  src/styles/_vendor.scss
  src/styles/base-theme.scss
  src/themes/custom/styles/theme.scss
  src/themes/dspace/styles/theme.scss
Labels: bug, themes, 1 APPROVAL

#1673 Swedish language file for DSpace 7
  src/assets/i18n/sv.json5
Labels: i18n / l10n

#1788 Enable Swedish language
  config/config.example.yml
  src/config/default-app-config.ts
Labels: i18n / l10n, configuration, 1 APPROVAL

#1777 Fix pagination in metadata browse links
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/browse-by/browse-by.component.ts
  src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html
  src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.spec.ts
  src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.ts
Labels: bug, component: Discovery, high priority, 1 APPROVAL, e/6

#1786 Enable responsive font sizes
  src/styles/_bootstrap_variables.scss
Labels: usability, themes, 1 APPROVAL
