Repository DSpace/dspace-angular, pull requests merged in 2022-01, with the labels that each got.

#1474 Update docker-compose scripts to use environment variables (to align with runtime configs)
  README.md
  docker/README.md
  docker/cli.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
  docker/docker-compose.yml
  docker/environment.dev.ts
  docker/local.cfg
Labels: code task, backend: Docker

#1454 Disallow Shibboleth users to change password
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
Labels: bug, high priority, authentication: Shibboleth, 1 APPROVAL

#1467 Admin is unable to reset other users' password
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
Labels: bug, high priority, authentication: general, authentication: password, component: administrative tools, 1 APPROVAL

#1427 Always enable deposit button
  src/app/submission/form/footer/submission-form-footer.component.html
  src/app/submission/form/footer/submission-form-footer.component.spec.ts
  src/app/submission/objects/submission-objects.effects.spec.ts
  src/app/submission/objects/submission-objects.effects.ts
Labels: bug, component: submission, high priority, e/6

#1489 Scripts & Processes without parameters fix
  src/app/process-page/form/process-form.component.spec.ts
  src/app/process-page/form/process-form.component.ts
Labels: bug, 1 APPROVAL, e/2, tools:processes

#1465 Move correlation ID to store
  src/app/app.module.ts
  src/app/app.reducer.ts
  src/app/core/log/log.interceptor.spec.ts
  src/app/core/log/log.interceptor.ts
  src/app/correlation-id/correlation-id.actions.ts
  src/app/correlation-id/correlation-id.reducer.spec.ts
  src/app/correlation-id/correlation-id.reducer.ts
  src/app/correlation-id/correlation-id.service.spec.ts
  src/app/correlation-id/correlation-id.service.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
Labels: bug, high priority, e/3

#1407 Show an error page if the rest api is not available
  src/app/app-routing-paths.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/data/root-data.service.ts
  src/app/core/server-check/server-check.guard.spec.ts
  src/app/core/server-check/server-check.guard.ts
  src/app/core/services/server-response.service.ts
  src/app/page-internal-server-error/page-internal-server-error.component.html
  src/app/page-internal-server-error/page-internal-server-error.component.scss
  src/app/page-internal-server-error/page-internal-server-error.component.ts
  src/app/page-internal-server-error/themed-page-internal-server-error.component.ts
  src/app/root/root.component.ts
  src/assets/i18n/en.json5
Labels: high priority, new feature, error handling

#1490 Docker-Compose Environment variables must be strings or numbers, not booleans
  docker/docker-compose.yml
Labels: bug, 1 APPROVAL, backend: Docker

#1493 Revert "Show an error page if the rest api is not available"
  src/app/app-routing-paths.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/data/root-data.service.ts
  src/app/core/server-check/server-check.guard.spec.ts
  src/app/core/server-check/server-check.guard.ts
  src/app/core/services/server-response.service.ts
  src/app/page-internal-server-error/page-internal-server-error.component.html
  src/app/page-internal-server-error/page-internal-server-error.component.scss
  src/app/page-internal-server-error/page-internal-server-error.component.ts
  src/app/page-internal-server-error/themed-page-internal-server-error.component.ts
  src/app/root/root.component.ts
  src/assets/i18n/en.json5
Labels: bug

#1496 Fix user profile page
  src/app/core/core.module.ts
  src/app/core/eperson/group-data.service.ts
Labels: bug, high priority, 1 APPROVAL

#1497 Replace href="#" with href="javascript:void(0);" everywhere
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-suggestions/org-unit-input-suggestions.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-suggestions/person-input-suggestions.component.html
  src/app/footer/footer.component.html
  src/app/item-page/field-components/collections/collections.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/chips/chips.component.html
  src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.html
  src/app/shared/input-suggestions/input-suggestions.component.html
  src/app/shared/input-suggestions/validation-suggestions/validation-suggestions.component.html
  src/app/shared/lang-switch/lang-switch.component.html
  src/app/submission/sections/container/section-container.component.html
Labels: bug, usability, 1 APPROVAL

#1498 [CST-4880] Add ServerCheckGuard in order to show internal server error page when rest server is not available
  src/app/app-routing-paths.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/data/root-data.service.spec.ts
  src/app/core/data/root-data.service.ts
  src/app/core/server-check/server-check.guard.spec.ts
  src/app/core/server-check/server-check.guard.ts
  src/app/core/services/server-response.service.ts
  src/app/page-internal-server-error/page-internal-server-error.component.html
  src/app/page-internal-server-error/page-internal-server-error.component.scss
  src/app/page-internal-server-error/page-internal-server-error.component.ts
  src/app/page-internal-server-error/themed-page-internal-server-error.component.ts
  src/app/root/root.component.ts
  src/app/shared/menu/menu.component.ts
  src/assets/i18n/en.json5
Labels: bug, high priority

#1500 Fix issue with grid view mode
  src/app/core/shared/search/search-configuration.service.ts
  src/app/shared/search/models/paginated-search-options.model.ts
Labels: bug, component: Discovery, high priority

#1472 Feedback form
  src/app/app-routing-paths.ts
  src/app/core/core.module.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/core/feedback/feedback-data.service.spec.ts
  src/app/core/feedback/feedback-data.service.ts
  src/app/core/feedback/feedback.guard.ts
  src/app/core/feedback/models/feedback.model.ts
  src/app/core/feedback/models/feedback.resource-type.ts
  src/app/footer/footer.component.html
  src/app/info/feedback/feedback-form/feedback-form.component.html
  src/app/info/feedback/feedback-form/feedback-form.component.scss
  src/app/info/feedback/feedback-form/feedback-form.component.spec.ts
  src/app/info/feedback/feedback-form/feedback-form.component.ts
  src/app/info/feedback/feedback.component.html
  src/app/info/feedback/feedback.component.scss
  src/app/info/feedback/feedback.component.spec.ts
  src/app/info/feedback/feedback.component.ts
  src/app/info/feedback/themed-feedback.component.ts
  src/app/info/info-routing-paths.ts
  src/app/info/info-routing.module.ts
  src/app/info/info.module.ts
  src/app/shared/mocks/mock-native-window-ref.ts
  src/app/shared/testing/route-service.stub.ts
  src/assets/i18n/en.json5
  src/themes/custom/app/info/feedback/feedback.component.html
  src/themes/custom/app/info/feedback/feedback.component.scss
  src/themes/custom/app/info/feedback/feedback.component.ts
  src/themes/custom/theme.module.ts
Labels: high priority, new feature

#1503 Fix deleting an item with an empty or invalid entity type
  src/app/item-page/edit-item-page/item-delete/item-delete.component.spec.ts
  src/app/item-page/edit-item-page/item-delete/item-delete.component.ts
Labels: high priority, 1 APPROVAL

#1507 Fix submission upload
  src/app/submission/form/submission-form.component.ts
  src/app/submission/objects/submission-objects.effects.ts
Labels: bug, component: submission, high priority, 1 APPROVAL

#1470 Port OIDC (OpenID Connect) auth plugin from DSpace-CRIS
  src/app/core/auth/models/auth.method-type.ts
  src/app/core/auth/models/auth.method.ts
  src/app/shared/log-in/methods/oidc/log-in-oidc.component.html
  src/app/shared/log-in/methods/oidc/log-in-oidc.component.spec.ts
  src/app/shared/log-in/methods/oidc/log-in-oidc.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
Labels: authentication: general, new feature

#1475 Add submission section for item embargo
  src/app/core/config/models/config-accesses-conditions-options.model.ts
  src/app/core/config/models/config-submission-access.model.ts
  src/app/core/config/models/config-submission-accesses.model.ts
  src/app/core/config/models/config-type.ts
  src/app/core/config/submission-accesses-config.service.ts
  src/app/core/core.module.ts
  src/app/core/submission/models/access-condition.model.ts
  src/app/core/submission/models/submission-accesses.resource-type.ts
  src/app/core/submission/models/submission-item-access-condition.model.ts
  src/app/core/submission/models/submission-upload-file-access-condition.model.ts
  src/app/core/submission/models/workspaceitem-section-accesses.model.ts
  src/app/core/submission/models/workspaceitem-sections.model.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.scss
  src/app/shared/mocks/section-accesses-config.service.mock.ts
  src/app/shared/mocks/section-accesses.service.mock.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/shared/testing/form-event.stub.ts
  src/app/submission/sections/accesses/section-accesses.component.html
  src/app/submission/sections/accesses/section-accesses.component.scss
  src/app/submission/sections/accesses/section-accesses.component.spec.ts
  src/app/submission/sections/accesses/section-accesses.component.ts
  src/app/submission/sections/accesses/section-accesses.model.ts
  src/app/submission/sections/accesses/section-accesses.service.ts
  src/app/submission/sections/container/section-container.component.ts
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
  src/app/submission/sections/models/section.model.ts
  src/app/submission/sections/sections-type.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
  src/app/submission/selectors.ts
  src/app/submission/submission.module.ts
  src/assets/i18n/en.json5
Labels: component: submission, high priority, new feature
