Repository DSpace/dspace-angular, pull requests merged in 2022-05, with the labels that each got.

#1601 Display the access status badges
  config/config.example.yml
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/item-search-result/item-admin-search-result-grid-element.component.spec.ts
  src/app/core/core.module.ts
  src/app/core/data/access-status-data.service.spec.ts
  src/app/core/data/access-status-data.service.ts
  src/app/core/data/item-data.service.spec.ts
  src/app/core/data/version-history-data.service.spec.ts
  src/app/core/shared/item.model.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/object-list/access-status-badge/access-status-badge.component.html
  src/app/shared/object-list/access-status-badge/access-status-badge.component.spec.ts
  src/app/shared/object-list/access-status-badge/access-status-badge.component.ts
  src/app/shared/object-list/access-status-badge/access-status.model.ts
  src/app/shared/object-list/access-status-badge/access-status.resource-type.ts
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.ts
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html
  src/app/shared/search/search.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/testing/hal-endpoint-service.stub.ts
  src/assets/i18n/en.json5
  src/assets/i18n/fr.json5
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/item-config.interface.ts
  src/config/item-page-config.interface.ts
  src/environments/environment.test.ts
Labels: improvement, component: Discovery, medium priority

#1615 Upgrade ng-dynamic-forms to v15 and RxJs to v7
  package.json
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/pagination/pagination.service.ts
  src/app/core/shared/hal-endpoint.service.spec.ts
  src/app/core/shared/operators.ts
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.ts
  src/app/root/root.component.spec.ts
  src/app/root/root.component.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
  src/app/shared/item/item-versions/item-versions.component.spec.ts
  src/app/shared/numeric.util.spec.ts
  src/app/shared/numeric.util.ts
  src/app/shared/remote-data.utils.ts
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/vocabulary-treeview/vocabulary-tree-flat-data-source.ts
  src/app/shared/vocabulary-treeview/vocabulary-treeview.service.spec.ts
  src/app/statistics/google-analytics.service.spec.ts
  src/app/statistics/google-analytics.service.ts
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.spec.ts
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
  yarn.lock
Labels: bug, dependencies, high priority, e/8

#1639 Fix search bar with input scope
  src/app/collection-page/collection-page.component.html
  src/app/collection-page/themed-collection-page.component.ts
  src/app/shared/search-form/search-form.component.spec.ts
  src/app/shared/search-form/search-form.component.ts
Labels: bug, component: Discovery, e/2

#1444 Add RSS buttons if the feature is enabled on the rest side
  src/app/collection-page/collection-item-mapper/collection-item-mapper.component.spec.ts
  src/app/community-page/sub-collection-list/community-page-sub-collection-list.component.spec.ts
  src/app/community-page/sub-community-list/community-page-sub-community-list.component.spec.ts
  src/app/core/core.module.ts
  src/app/core/services/link-head.service.spec.ts
  src/app/core/services/link-head.service.ts
  src/app/home-page/top-level-community-list/top-level-community-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/object-select/collection-select/collection-select.component.spec.ts
  src/app/shared/object-select/item-select/item-select.component.spec.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/rss-feed/rss.component.html
  src/app/shared/rss-feed/rss.component.scss
  src/app/shared/rss-feed/rss.component.spec.ts
  src/app/shared/rss-feed/rss.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/testing/search-configuration-service.stub.ts
Labels: component: Discovery, new feature, medium priority

#1653 Fix RSS accessibility issue: link has no discernible text
  src/app/shared/rss-feed/rss.component.html
  src/assets/i18n/en.json5
Labels: bug, high priority, testing framework

#1634 Add special groups list to the profile page
  src/app/core/auth/auth-request.service.ts
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/models/auth-status.model.ts
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
  src/app/shared/testing/auth-request-service.stub.ts
  src/app/shared/testing/special-group.mock.ts
  src/assets/i18n/en.json5
Labels: bug, authorization, 1 APPROVAL, medium priority

#1658 Fix entitytype redirect encoding issue
  src/app/item-page/item-page.resolver.spec.ts
  src/app/item-page/item-page.resolver.ts
Labels: bug, component: configurable entities, high priority, 1 APPROVAL

#1640 Show notifications when failing to create/delete role Groups
  src/app/collection-page/edit-collection-page/collection-roles/collection-roles.component.spec.ts
  src/app/community-page/edit-community-page/community-roles/community-roles.component.spec.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.spec.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, 1 APPROVAL

#1652 [CST-5303] Live Import providers i18n keys
  src/assets/i18n/en.json5
Labels: high priority, 1 APPROVAL

#1608 Cache redesign part 3: simplify the invalidation of cached objects
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/access-control/group-registry/groups-registry.component.spec.ts
  src/app/access-control/group-registry/groups-registry.component.ts
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.ts
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts
  src/app/collection-page/delete-collection-page/delete-collection-page.component.ts
  src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.spec.ts
  src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.ts
  src/app/community-page/delete-community-page/delete-community-page.component.ts
  src/app/core/cache/object-cache.reducer.spec.ts
  src/app/core/cache/object-cache.reducer.ts
  src/app/core/cache/object-cache.service.spec.ts
  src/app/core/cache/object-cache.service.ts
  src/app/core/data/bitstream-format-data.service.spec.ts
  src/app/core/data/comcol-data.service.spec.ts
  src/app/core/data/data.service.spec.ts
  src/app/core/data/data.service.ts
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/core/registry/registry.service.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/item-page/simple/item-types/versioned-item/versioned-item.component.spec.ts
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.spec.ts
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.ts
  src/app/shared/comcol/comcol-forms/delete-comcol-page/delete-comcol-page.component.spec.ts
  src/app/shared/comcol/comcol-forms/delete-comcol-page/delete-comcol-page.component.ts
  src/app/shared/confirmation-modal/confirmation-modal.component.spec.ts
  src/app/shared/confirmation-modal/confirmation-modal.component.ts
  src/app/shared/idle-modal/idle-modal.component.spec.ts
  src/app/shared/idle-modal/idle-modal.component.ts
  src/app/shared/item/item-versions/item-versions-delete-modal/item-versions-delete-modal.component.html
  src/app/shared/item/item-versions/item-versions-delete-modal/item-versions-delete-modal.component.ts
  src/app/shared/item/item-versions/item-versions.component.spec.ts
  src/app/shared/item/item-versions/item-versions.component.ts
  src/app/shared/mocks/request.service.mock.ts
  src/app/shared/resource-policies/resource-policies.component.spec.ts
  src/app/shared/resource-policies/resource-policies.component.ts
  src/app/shared/search/search-switch-configuration/search-switch-configuration.component.spec.ts
  src/test.ts
Labels: improvement, Difficulty: High, high priority, performance / caching, code task, e/30

#1667 Docker Fixes: Ensure multiple architecture build is disabled for PRs
  .github/workflows/docker.yml
Labels: high priority, backend: Docker
