Repository DSpace/dspace-angular, pull requests merged in 2022-02, with the labels that each got.

#1508 Full Scottish Gaelic translation.
  src/assets/i18n/gd.json5
Labels: i18n / l10n

#1509 Enable Scottish Gaelic
  config/config.example.yml
  src/config/default-app-config.ts
Labels: i18n / l10n

#1438 Edit IIIF bitstream metadata
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.scss
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/assets/i18n/en.json5
Labels: improvement, integration: IIIF

#1461 Update de.json5
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL

#1526 [Issue 1525] Unwrap environment during conversion to YAML
  scripts/env-to-yaml.ts
Labels: bug, high priority, configuration, 1 APPROVAL

#1512 Various small changes to improve customizability
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/admin/admin-sidebar/themed-admin-sidebar.component.ts
  src/app/app.module.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/collection-page/collection-page.component.html
  src/app/community-list-page/community-list-page.component.html
  src/app/community-list-page/community-list-page.module.ts
  src/app/community-list-page/community-list/themed-community-list.component.ts
  src/app/community-page/community-page.component.html
  src/app/my-dspace-page/my-dspace-page.component.html
  src/app/navbar/navbar.component.html
  src/app/root/root.component.html
  src/app/search-page/configuration-search-page.component.ts
  src/app/search-page/search-page.component.html
  src/app/shared/comcol/comcol-page-browse-by/themed-comcol-page-browse-by.component.ts
  src/app/shared/comcol/comcol.module.ts
  src/app/shared/dso-selector/dso-selector/authorized-collection-selector/authorized-collection-selector.component.ts
  src/app/shared/dso-selector/dso-selector/dso-selector.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html
  src/app/shared/object-grid/object-grid.component.scss
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-approved-search-result/claimed-approved-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-declined-search-result/claimed-declined-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/themed-item-list-preview.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/item-search-result/item-search-result-list-element-submission.component.html
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.html
  src/app/shared/search-form/search-form.component.spec.ts
  src/app/shared/search/search.component.html
  src/app/shared/search/search.component.ts
  src/app/shared/search/search.module.ts
  src/app/shared/search/themed-search.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/theme-support/themed.component.ts
  src/app/thumbnail/thumbnail.component.ts
  src/styles/_truncatable-part.component.scss
  src/themes/custom/app/community-list-page/community-list/community-list.component.html
  src/themes/custom/app/community-list-page/community-list/community-list.component.scss
  src/themes/custom/app/community-list-page/community-list/community-list.component.ts
  src/themes/custom/app/search-page/search-page.component.ts
  src/themes/custom/theme.module.ts
Labels: improvement, themes

#1530 [CST-5341] Link back to the item page in the now downloading page
  src/app/shared/bitstream-download-page/bitstream-download-page.component.html
  src/app/shared/bitstream-download-page/bitstream-download-page.component.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL
