Repository DSpace/dspace-angular, pull requests merged in 2022-09, with the labels that each got.

#1790 Spanish translation updated
  src/assets/i18n/es.json5
Labels: i18n / l10n

#1741 Consolidate all initialization in a single Service
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/auth/auth.service.ts
  src/app/core/shared/distinct-next.ts
  src/app/init.service.spec.ts
  src/app/init.service.ts
  src/app/shared/mocks/theme-service.mock.ts
  src/app/shared/theme-support/theme.service.spec.ts
  src/app/shared/theme-support/theme.service.ts
  src/config/app-config.interface.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/browser-init.service.spec.ts
  src/modules/app/browser-init.service.ts
  src/modules/app/server-app.module.ts
  src/modules/app/server-init.service.ts
  src/modules/transfer-state/dspace-browser-transfer-state.module.ts
  src/modules/transfer-state/dspace-browser-transfer-state.service.ts
  src/modules/transfer-state/dspace-server-transfer-state.module.ts
  src/modules/transfer-state/dspace-server-transfer-state.service.ts
  src/modules/transfer-state/dspace-transfer-state.service.ts
Labels: bug, high priority, e/20

#1779 Make create, edit community/collection/item dialogs theme-able.
  src/app/menu.resolver.ts
  src/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/themed-create-collection-parent-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/themed-create-community-parent-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/themed-create-item-parent-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/edit-collection-selector/themed-edit-collection-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/edit-community-selector/themed-edit-community-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/edit-item-selector/themed-edit-item-selector.component.ts
  src/app/shared/shared.module.ts
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/create-collection-parent-selector.component.html
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/create-collection-parent-selector.component.scss
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-collection-parent-selector/create-collection-parent-selector.component.ts
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.scss
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.html
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.scss
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-item-parent-selector/create-item-parent-selector.component.ts
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-collection-selector/edit-collection-selector.component.html
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-collection-selector/edit-collection-selector.component.scss
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-collection-selector/edit-collection-selector.component.ts
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-community-selector/edit-community-selector.component.html
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-community-selector/edit-community-selector.component.scss
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-community-selector/edit-community-selector.component.ts
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-item-selector/edit-item-selector.component.html
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-item-selector/edit-item-selector.component.scss
  src/themes/custom/app/shared/dso-selector/modal-wrappers/edit-item-selector/edit-item-selector.component.ts
  src/themes/custom/eager-theme.module.ts
Labels: improvement, component: submission, component: administrative tools, themes, 1 APPROVAL, component: Community, component: Collection

#1792 Add delete process functionality
  src/app/process-page/detail/process-detail.component.html
  src/app/process-page/detail/process-detail.component.spec.ts
  src/app/process-page/detail/process-detail.component.ts
  src/app/process-page/overview/process-bulk-delete.service.spec.ts
  src/app/process-page/overview/process-bulk-delete.service.ts
  src/app/process-page/overview/process-overview.component.html
  src/app/process-page/overview/process-overview.component.spec.ts
  src/app/process-page/overview/process-overview.component.ts
  src/assets/i18n/en.json5
Labels: bug, improvement

#1759 External provider query error
  src/app/submission/import-external/submission-import-external.component.html
  src/app/submission/import-external/submission-import-external.component.spec.ts
  src/assets/i18n/en.json5
Labels: bug, error handling, 1 APPROVAL, tools:import-sources

#1797 Force all code to use LF line endings in .gitattibutes
  .gitattributes
  scripts/sync-i18n-files.ts
  src/app/app.module.ts
  src/assets/i18n/tr.json5
Labels: bug, code task, 1 APPROVAL

#1815 94322: Fix theme matching using handles
  src/app/core/shared/collection.model.ts
  src/app/core/shared/community.model.ts
  src/app/core/shared/handle-object.model.ts
  src/app/core/shared/item.model.ts
  src/app/shared/theme-support/theme.service.ts
  src/config/theme.model.spec.ts
  src/config/theme.model.ts
Labels: bug, high priority, configuration, themes, 1 APPROVAL, e/4

#1801 Displaying Recent Submissions on the homepage
  config/config.example.yml
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.ts
  src/app/home-page/home-page.module.ts
  src/app/home-page/recent-item-list/recent-item-list.component.html
  src/app/home-page/recent-item-list/recent-item-list.component.scss
  src/app/home-page/recent-item-list/recent-item-list.component.spec.ts
  src/app/home-page/recent-item-list/recent-item-list.component.ts
  src/assets/i18n/en.json5
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/homepage-config.interface.ts
  src/environments/environment.test.ts
Labels: component: Discovery, new feature

#1820 Ensure `yarn test:rest` reads all JSON data, not just first chunk
  scripts/test-rest.ts
Labels: bug, configuration, 1 APPROVAL

#1824 Add an optional `NavigationExtras` argument to `PaginationService.updateRoute`
  src/app/core/pagination/pagination.service.spec.ts
  src/app/core/pagination/pagination.service.ts
Labels: improvement, 1 APPROVAL

#1814 Repair config issues
  package.json
  scripts/serve.ts
  server.ts
  src/app/init.service.ts
  src/config/config.server.ts
  src/modules/app/browser-init.service.ts
  startup-message.ts
Labels: bug, high priority, configuration, e/4

#1816 Cookie consent shows analytics usage also when GA is disabled
  src/app/shared/cookies/browser-klaro.service.spec.ts
  src/app/shared/cookies/browser-klaro.service.ts
Labels: bug, component: statistics

#1297 Kazakh Translation
  src/assets/i18n/kk.json5
Labels: i18n / l10n

#1831 Enable Kazakh translation by default
  config/config.example.yml
  src/config/default-app-config.ts
Labels: i18n / l10n

#1819 Greek support for frontend
  config/config.example.yml
  src/assets/i18n/el.json5
  src/config/default-app-config.ts
  src/environments/environment.test.ts
Labels: i18n / l10n

#1803 Make no. of communities per pagination / expansion configurable
  config/config.example.yml
  src/app/community-list-page/community-list-service.spec.ts
  src/app/community-list-page/community-list-service.ts
  src/app/home-page/top-level-community-list/top-level-community-list.component.spec.ts
  src/app/home-page/top-level-community-list/top-level-community-list.component.ts
  src/config/app-config.interface.ts
  src/config/community-list-config.interface.ts
  src/config/default-app-config.ts
  src/config/homepage-config.interface.ts
  src/environments/environment.test.ts
Labels: usability, configuration, 1 APPROVAL

#1835 Creative Commons selector is not loading
  src/app/core/submission/submission-cc-license-data.service.spec.ts
  src/app/core/submission/submission-cc-license-data.service.ts
Labels: bug, component: submission, 1 APPROVAL, integration: Creative Commons

#1771 Make the size of a browse result page configurable.
  config/config.example.yml
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.spec.ts
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.spec.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.spec.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
  src/config/browse-by-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
Labels: improvement, component: Discovery, quick win, configuration, 1 APPROVAL

#1821 Search events bug-fix
  src/app/core/shared/search/search.service.spec.ts
  src/app/core/shared/search/search.service.ts
  src/app/search-page/search-page.component.html
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
Labels: bug, component: Discovery, component: statistics, 1 APPROVAL

#1776 Make password minimum requirements stronger
  src/app/forgot-password/forgot-password-form/forgot-password-form.component.spec.ts
  src/app/forgot-password/forgot-password-form/forgot-password-form.component.ts
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.html
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.spec.ts
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.ts
  src/app/register-page/create-profile/create-profile.component.spec.ts
  src/assets/i18n/en.json5
Labels: bug, authentication: general, authentication: password, 1 APPROVAL

#1748 New theme-able components
  src/app/community-page/community-page.component.html
  src/app/community-page/community-page.module.ts
  src/app/community-page/sub-collection-list/community-page-sub-collection-list.component.ts
  src/app/community-page/sub-collection-list/themed-community-page-sub-collection-list.component.ts
  src/app/community-page/sub-community-list/community-page-sub-community-list.component.ts
  src/app/community-page/sub-community-list/themed-community-page-sub-community-list.component.ts
  src/themes/custom/app/community-page/sub-collection-list/community-page-sub-collection-list.component.html
  src/themes/custom/app/community-page/sub-collection-list/community-page-sub-collection-list.component.scss
  src/themes/custom/app/community-page/sub-collection-list/community-page-sub-collection-list.component.ts
  src/themes/custom/app/community-page/sub-community-list/community-page-sub-community-list.component.html
  src/themes/custom/app/community-page/sub-community-list/community-page-sub-community-list.component.scss
  src/themes/custom/app/community-page/sub-community-list/community-page-sub-community-list.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: improvement, themes

#1848 Regression fixes
  src/app/core/auth/auth-request.service.spec.ts
  src/app/core/auth/auth-request.service.ts
  src/app/page-error/themed-page-error.component.ts
  src/app/page-internal-server-error/themed-page-internal-server-error.component.ts
  src/app/pagenotfound/themed-pagenotfound.component.ts
  src/app/shared/theme-support/theme.service.spec.ts
  src/app/shared/theme-support/theme.service.ts
Labels: bug, high priority, configuration, error handling, themes, 1 APPROVAL

#1844 Issue 1843 - Fix default bundles example in config.example.yml
  config/config.example.yml
Labels: configuration, 1 APPROVAL

#1694 Support restricted thumbnails
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/collection-search-result/collection-admin-search-result-grid-element.component.spec.ts
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/community-search-result/community-admin-search-result-grid-element.component.spec.ts
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/item-search-result/item-admin-search-result-grid-element.component.spec.ts
  src/app/shared/loading/loading.component.html
  src/app/shared/loading/loading.component.scss
  src/app/shared/loading/loading.component.ts
  src/app/shared/loading/themed-loading.component.ts
  src/app/shared/testing/authorization-service.stub.ts
  src/app/shared/testing/file-service.stub.ts
  src/app/thumbnail/thumbnail.component.html
  src/app/thumbnail/thumbnail.component.scss
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
Labels: bug, authorization, component: Item

#1839 Full item page of entities missing title/name
  src/app/core/breadcrumbs/dso-name.service.ts
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-issue/journal-issue-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-volume/journal-volume-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal/journal-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/org-unit/org-unit-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/person/person-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/project/project-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/org-unit/org-unit-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.ts
  src/app/entity-groups/research-entities/item-list-elements/sidebar-search-list-elements/org-unit/org-unit-sidebar-search-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/sidebar-search-list-elements/org-unit/org-unit-sidebar-search-list-element.component.ts
  src/app/entity-groups/research-entities/item-list-elements/sidebar-search-list-elements/person/person-sidebar-search-list-element.component.spec.ts
  src/app/entity-groups/research-entities/item-list-elements/sidebar-search-list-elements/person/person-sidebar-search-list-element.component.ts
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.ts
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.ts
  src/app/item-page/item-page.module.ts
  src/app/item-page/simple/field-components/specific-field/title/item-page-title-field.component.html
  src/app/item-page/simple/field-components/specific-field/title/item-page-title-field.component.ts
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.ts
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.html
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.spec.ts
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.ts
  src/app/shared/shared.module.ts
Labels: bug, component: configurable entities, high priority, 1 APPROVAL, e/6, component: Item

#1837 Swedish translation file modified
  src/assets/i18n/en.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/sv.json5
Labels: i18n / l10n, 1 APPROVAL

#1804 Ask current password to user when setting a new password
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.spec.ts
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.ts
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
  src/assets/i18n/en.json5
Labels: bug, authentication: general, authentication: password, 1 APPROVAL

#1860 Fix recent submissions list thumbnails
  src/app/home-page/home-page.module.ts
  src/app/home-page/recent-item-list/recent-item-list.component.html
  src/app/home-page/recent-item-list/recent-item-list.component.spec.ts
  src/app/home-page/recent-item-list/recent-item-list.component.ts
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
Labels: bug, high priority, themes

#1857 Updated the Brazilian Portuguese translation.
  src/assets/i18n/pt-BR.json5
Labels: i18n / l10n, 1 APPROVAL

#1823 After drag & drop: Redirect the user and remove the notification
  src/app/my-dspace-page/my-dspace-new-submission/my-dspace-new-submission.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/fr.json5
Labels: improvement, usability, component: submission, 1 APPROVAL

#1832 make search-settings.component themed
  src/app/shared/search/search-settings/themed-search-settings.component.ts
  src/app/shared/search/search-sidebar/search-sidebar.component.html
  src/app/shared/search/search.module.ts
  src/themes/custom/app/shared/search/search-settings/search-settings.component.html
  src/themes/custom/app/shared/search/search-settings/search-settings.component.scss
  src/themes/custom/app/shared/search/search-settings/search-settings.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: component: Discovery, themes, 1 APPROVAL

#1846 Track dependencies in order to invalidate them when an object is invalidated
  src/app/core/cache/object-cache.actions.ts
  src/app/core/cache/object-cache.reducer.spec.ts
  src/app/core/cache/object-cache.reducer.ts
  src/app/core/cache/object-cache.service.spec.ts
  src/app/core/cache/object-cache.service.ts
  src/app/core/data/base/base-data.service.spec.ts
  src/app/core/data/base/base-data.service.ts
  src/app/core/data/base/patch-data.spec.ts
  src/app/core/data/base/patch-data.ts
  src/app/core/data/feature-authorization/authorization-data.service.spec.ts
  src/app/core/data/feature-authorization/authorization-data.service.ts
  src/app/core/eperson/group-data.service.spec.ts
  src/app/shared/mocks/object-cache.service.mock.ts
Labels: bug, usability, high priority, performance / caching, component: Item, e/12

#1850 Use values from x-forwarded headers in getOrigin server side
  server.ts
  src/app/core/services/browser-hard-redirect.service.spec.ts
  src/app/core/services/browser-hard-redirect.service.ts
  src/config/config.util.spec.ts
  src/config/default-app-config.ts
  src/config/ui-server-config.interface.ts
  src/environments/environment.test.ts
Labels: bug, component: SEO, high priority, 1 APPROVAL

#1863 Registration page password validation
  src/app/register-page/create-profile/create-profile.component.ts
Labels: bug, authentication: password, 1 APPROVAL

#1847 Bug fix for multiple IIIF image property
  src/app/item-page/mirador-viewer/mirador-viewer.component.spec.ts
  src/app/item-page/mirador-viewer/mirador-viewer.component.ts
  src/app/item-page/mirador-viewer/mirador-viewer.service.ts
Labels: bug, 1 APPROVAL, integration: IIIF

#1842 additional themed components
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-date-page/themed-browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/browse-by/browse-by-metadata-page/themed-browse-by-metadata-page.component.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
  src/app/browse-by/browse-by-title-page/themed-browse-by-title-page.component.ts
  src/app/browse-by/browse-by.module.ts
  src/app/collection-page/collection-page.component.html
  src/app/community-page/community-page.component.html
  src/app/community-page/sub-collection-list/community-page-sub-collection-list.component.spec.ts
  src/app/community-page/sub-community-list/community-page-sub-community-list.component.spec.ts
  src/app/header/header.component.html
  src/app/home-page/top-level-community-list/top-level-community-list.component.spec.ts
  src/app/search-navbar/themed-search-navbar.component.ts
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/comcol/comcol-page-handle/themed-comcol-page-handle.component.ts
  src/app/shared/comcol/comcol.module.ts
  src/app/shared/object-collection/object-collection.component.html
  src/app/shared/object-list/themed-object-list.component.ts
  src/app/shared/shared.module.ts
  src/themes/custom/app/browse-by/browse-by-date-page/browse-by-date-page.component.html
  src/themes/custom/app/browse-by/browse-by-date-page/browse-by-date-page.component.scss
  src/themes/custom/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/themes/custom/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/themes/custom/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.scss
  src/themes/custom/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/themes/custom/app/browse-by/browse-by-title-page/browse-by-title-page.component.html
  src/themes/custom/app/browse-by/browse-by-title-page/browse-by-title-page.component.scss
  src/themes/custom/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
  src/themes/custom/app/search-navbar/search-navbar.component.html
  src/themes/custom/app/search-navbar/search-navbar.component.scss
  src/themes/custom/app/search-navbar/search-navbar.component.ts
  src/themes/custom/app/shared/comcol-page-browse-by/comcol-page-browse-by.component.html
  src/themes/custom/app/shared/comcol-page-browse-by/comcol-page-browse-by.component.scss
  src/themes/custom/app/shared/comcol-page-browse-by/comcol-page-browse-by.component.ts
  src/themes/custom/app/shared/comcol-page-handle/comcol-page-handle.component.html
  src/themes/custom/app/shared/comcol-page-handle/comcol-page-handle.component.scss
  src/themes/custom/app/shared/comcol-page-handle/comcol-page-handle.component.ts
  src/themes/custom/app/shared/object-list/collection-list-element/collection-list-element.component.html
  src/themes/custom/app/shared/object-list/collection-list-element/collection-list-element.component.scss
  src/themes/custom/app/shared/object-list/collection-list-element/collection-list-element.component.ts
  src/themes/custom/app/shared/object-list/community-list-element/community-list-element.component.html
  src/themes/custom/app/shared/object-list/community-list-element/community-list-element.component.scss
  src/themes/custom/app/shared/object-list/community-list-element/community-list-element.component.ts
  src/themes/custom/app/shared/object-list/object-list.component.html
  src/themes/custom/app/shared/object-list/object-list.component.scss
  src/themes/custom/app/shared/object-list/object-list.component.ts
  src/themes/custom/eager-theme.module.ts
  src/themes/custom/lazy-theme.module.ts
Labels: themes

#1826 Update Google Analytics to version 4
  src/app/app.component.spec.ts
  src/app/root/root.component.spec.ts
  src/app/root/root.component.ts
  src/app/shared/cookies/browser-klaro.service.spec.ts
  src/app/shared/cookies/browser-klaro.service.ts
  src/app/shared/cookies/klaro-configuration.ts
  src/app/shared/cookies/klaro.service.ts
  src/app/statistics/google-analytics.service.spec.ts
  src/app/statistics/google-analytics.service.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
Labels: improvement, component: statistics, 1 APPROVAL

#1851 Add support for line breaks markdown and mathjax in metadata
  package.json
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html
  src/app/item-page/field-components/metadata-values/metadata-values.component.html
  src/app/item-page/field-components/metadata-values/metadata-values.component.spec.ts
  src/app/item-page/field-components/metadata-values/metadata-values.component.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.html
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/truncatable/truncatable-part/truncatable-part.component.html
  src/app/shared/utils/markdown.pipe.spec.ts
  src/app/shared/utils/markdown.pipe.ts
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/markdown-config.interface.ts
  src/environments/environment.test.ts
  src/styles/_global-styles.scss
  yarn.lock
Labels: bug, high priority, new feature, e/8, ux

#1838 Clarify that submission page may be closed while REST processes uploads
  src/app/shared/uploader/uploader.component.html
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
Labels: improvement, component: submission, quick win, 1 APPROVAL

#1873 Fix infinite loop when deleting an EPerson
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/group-registry/groups-registry.component.ts
Labels: bug, high priority, component: administrative tools

#1872 repair tests bis
  src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.spec.ts
  src/app/item-page/field-components/metadata-values/metadata-values.component.spec.ts
  src/app/item-page/field-components/metadata-values/metadata-values.component.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts
Labels: bug, testing framework

#1866 pt-BR translation contribution
  src/assets/i18n/pt-BR.json5
Labels: i18n / l10n, 1 APPROVAL

#1827 Create new batch export/import page to/from ZIP
  src/app/admin/admin-import-batch-page/batch-import-page.component.html
  src/app/admin/admin-import-batch-page/batch-import-page.component.spec.ts
  src/app/admin/admin-import-batch-page/batch-import-page.component.ts
  src/app/admin/admin-routing.module.ts
  src/app/admin/admin.module.ts
  src/app/core/data/processes/script-data.service.ts
  src/app/menu.resolver.spec.ts
  src/app/menu.resolver.ts
  src/app/shared/dso-selector/modal-wrappers/dso-selector-modal-wrapper.component.ts
  src/app/shared/dso-selector/modal-wrappers/export-batch-selector/export-batch-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/export-batch-selector/export-batch-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/import-batch-selector/import-batch-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/import-batch-selector/import-batch-selector.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
Labels: new feature, tools: import, tools:processes

#1864 Adding missing language parameters in french translations file (fr.json5)
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL
