Repository DSpace/dspace-angular, pull requests merged in 2022-04, with the labels that each got.

#1574 Pad date range sliders to fix search facet animation issues
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss
Labels: component: Discovery, quick win, 1 APPROVAL

#1552 [CST-5449] "Browse by" pages are missing "Now showing" contextual information
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/shared/browse-by/browse-by.component.html
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/browse-by/browse-by.component.ts
  src/app/shared/object-collection/object-collection.component.html
  src/app/shared/object-collection/object-collection.component.ts
  src/app/shared/object-detail/object-detail.component.html
  src/app/shared/object-detail/object-detail.component.ts
  src/app/shared/object-grid/object-grid.component.html
  src/app/shared/object-grid/object-grid.component.ts
  src/app/shared/object-list/object-list.component.html
  src/app/shared/object-list/object-list.component.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/pagination/pagination.component.spec.ts
  src/app/shared/pagination/pagination.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, component: Discovery

#1580 French translation reviewed and updated
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL

#1582 Updated German translation
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL

#1597 Fix for embargoed file links on Google Scholar Meta Tag "citation_pdf_url"
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
  src/app/core/shared/operators.ts
Labels: bug, component: SEO, high priority, 1 APPROVAL

#1599 Disable redux devtools support in prod mode
  angular.json
  src/app/app.module.ts
  src/config/store/devtools.prod.ts
  src/config/store/devtools.ts
Labels: bug, high priority, 1 APPROVAL, e/1

#1600 Fix for menu issues
  src/app/admin/admin-sidebar/admin-sidebar.component.spec.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/core/data/processes/script-data.service.ts
  src/app/shared/menu/menu-item/link-menu-item.component.html
  src/app/shared/menu/menu-item/link-menu-item.component.spec.ts
  src/app/shared/menu/menu-item/models/link.model.ts
Labels: bug, usability, high priority, tools: export, 1 APPROVAL, e/4

#1598 Fix search field on search hierarchy filter component
  src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.html
  src/app/shared/input-suggestions/input-suggestions.component.scss
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/app/shared/search/search.utils.spec.ts
  src/app/shared/search/search.utils.ts
Labels: bug, component: Discovery, high priority, 1 APPROVAL, e/4

#1469 Support external links in menus
  src/app/shared/menu/menu-item-type.model.ts
  src/app/shared/menu/menu-item/external-link-menu-item.component.html
  src/app/shared/menu/menu-item/external-link-menu-item.component.spec.ts
  src/app/shared/menu/menu-item/external-link-menu-item.component.ts
  src/app/shared/menu/menu-item/link-menu-item.component.spec.ts
  src/app/shared/menu/menu-item/models/external-link.model.ts
  src/app/shared/menu/menu.module.ts
  src/app/shared/shared.module.ts
Labels: improvement, 1 APPROVAL

#1606 Fix router-outlet destroy issue
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/app.component.ts
  src/app/root/root.component.html
  src/app/shared/resource-policies/form/eperson-group-list/group-search-box/group-search-box.component.ts
Labels: bug, authorization, 1 APPROVAL

#1613 Fix Dockerfile for Angular 13 updates
  Dockerfile
Labels: bug, high priority, backend: Docker

#1605 Add standard bundles in upload bitstream
  config/config.example.yml
  src/app/item-page/bitstreams/upload/upload-bitstream.component.html
  src/app/item-page/bitstreams/upload/upload-bitstream.component.spec.ts
  src/app/item-page/bitstreams/upload/upload-bitstream.component.ts
  src/assets/i18n/en.json5
  src/config/app-config.interface.ts
  src/config/bundle-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
Labels: usability, high priority, new feature, 1 APPROVAL, e/3

#1519 Turkish Translation
  src/assets/i18n/tr.json5
Labels: i18n / l10n

#1622 Enable Turkish lang pack in dropdown list
  config/config.example.yml
  src/config/default-app-config.ts
Labels: i18n / l10n, configuration, 1 APPROVAL

#1561 Browse clarify filter functionality
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/browse-by/browse-by-routing.module.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
  src/app/shared/browse-by/browse-by.component.html
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/browse-by/browse-by.component.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/starts-with/date/starts-with-date.component.spec.ts
  src/app/shared/starts-with/date/starts-with-date.component.ts
  src/app/shared/starts-with/starts-with-abstract.component.ts
  src/app/shared/starts-with/text/starts-with-text.component.html
  src/app/shared/starts-with/text/starts-with-text.component.spec.ts
  src/app/shared/starts-with/text/starts-with-text.component.ts
  src/app/shared/testing/route-service.stub.ts
  src/assets/i18n/en.json5
Labels: bug, usability, component: Discovery, high priority, 1 APPROVAL

#1620 Enabled search scope selector
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html
  src/app/shared/search-form/search-form.component.html
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
Labels: bug, 1 APPROVAL

#1623 Issue #1381 - DSO sub route titles fix
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
Labels: bug, usability, high priority, 1 APPROVAL

#1625 Radio buttons in submission
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html
Labels: bug, component: submission, 1 APPROVAL, e/4

#1629 Mirador webpack build fix.
  src/mirador-viewer/mirador.html
  webpack/webpack.mirador.config.ts
Labels: bug, 1 APPROVAL, integration: IIIF

#1628 Bitstream edit page fixes
  src/app/bitstream-page/bitstream-page-routing.module.ts
  src/app/bitstream-page/bitstream-page.resolver.ts
  src/app/core/breadcrumbs/bitstream-breadcrumb.resolver.ts
  src/app/core/breadcrumbs/bitstream-breadcrumbs.service.ts
  src/app/core/breadcrumbs/dso-breadcrumbs.service.ts
  src/app/core/shared/bitstream.model.ts
  src/app/shared/resource-policies/resource-policies.component.html
Labels: bug, 1 APPROVAL
