Repository DSpace/dspace-angular, pull requests merged in 2022-03, with the labels that each got.

#1533 Fix so newly added value on resource policy result in ADD patch, not REPLACE
  src/app/core/data/default-change-analyzer.service.ts
  src/app/core/dspace-rest/dspace-not-null.serializer.ts
Labels: bug, authorization, 1 APPROVAL

#1536 Adding missing parameters to fr.json5
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL

#1535 [CST-5316] "Browsing by issue date" is stuck on loading
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/shared/date.util.ts
Labels: bug, component: Discovery, 1 APPROVAL

#1524 Fix forced re-init due to out-of-scope fields
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
Labels: bug, component: submission, 1 APPROVAL

#1534 Invalidate the authorization cache before retrieving token for auth cookie.
  src/app/core/auth/auth.effects.spec.ts
  src/app/core/auth/auth.effects.ts
Labels: bug, authorization, 1 APPROVAL

#1546 Redirect to 404 page for forgot password or registration link with used tokens
  src/app/core/data/eperson-registration.service.spec.ts
  src/app/core/data/eperson-registration.service.ts
  src/app/forgot-password/forgot-password-form/forgot-password-form.component.html
  src/app/forgot-password/forgot-password-form/forgot-password-form.component.spec.ts
  src/app/forgot-password/forgot-password-form/forgot-password-form.component.ts
  src/app/forgot-password/forgot-password-routing.module.ts
  src/app/register-email-form/registration.resolver.spec.ts
  src/app/register-email-form/registration.resolver.ts
  src/app/register-page/create-profile/create-profile.component.html
  src/app/register-page/create-profile/create-profile.component.spec.ts
  src/app/register-page/create-profile/create-profile.component.ts
  src/app/register-page/register-page-routing.module.ts
  src/app/register-page/registration.guard.spec.ts
  src/app/register-page/registration.guard.ts
Labels: bug, high priority, authentication: password, testathon

#1521 Fixed notifications duplicate issue
  src/app/root/root.component.html
Labels: bug, 1 APPROVAL

#1555 [Issue 1527] Set default env preboot to false
  src/environments/environment.ts
Labels: bug, high priority, 1 APPROVAL

#1513 Enhance e2e test infrastructure. Add initial tests for authenticated actions like submission, mydspace, etc.
  README.md
  cypress.json
  cypress/integration/homepage.spec.ts
  cypress/integration/login-modal.spec.ts
  cypress/integration/my-dspace.spec.ts
  cypress/integration/search-navbar.spec.ts
  cypress/integration/search-page.spec.ts
  cypress/integration/submission.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  docker/cli.assetstore.yml
  docker/db.entities.yml
  docker/docker-compose-ci.yml
  package.json
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-issue/journal-issue-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-volume/journal-volume-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal/journal-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/org-unit/org-unit-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/person/person-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/project/project-search-result-grid-element.component.html
  src/app/my-dspace-page/my-dspace-new-submission/my-dspace-new-external-dropdown/my-dspace-new-external-dropdown.component.html
  src/app/my-dspace-page/my-dspace-new-submission/my-dspace-new-external-dropdown/my-dspace-new-external-dropdown.component.scss
  src/app/my-dspace-page/my-dspace-new-submission/my-dspace-new-submission-dropdown/my-dspace-new-submission-dropdown.component.html
  src/app/search-navbar/search-navbar.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/methods/password/log-in-password.component.html
  src/app/shared/log-out/log-out.component.html
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html
  src/app/shared/number-picker/number-picker.component.html
  src/app/shared/number-picker/number-picker.component.spec.ts
  src/app/shared/number-picker/number-picker.component.ts
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.html
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.spec.ts
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.html
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.spec.ts
  src/app/shared/object-grid/object-grid.component.html
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.spec.ts
  src/app/shared/object-list/object-list.component.html
  src/app/shared/search-form/search-form.component.html
  src/app/shared/view-mode-switch/view-mode-switch.component.html
  src/app/submission/form/footer/submission-form-footer.component.html
  src/assets/i18n/en.json5
  yarn.lock
Labels: improvement, testing framework

#1572 updated German translation
  src/assets/i18n/de.json5
Labels: i18n / l10n

#1556 Withdrawn item tombstone
  src/app/item-page/full/full-item-page.component.html
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/full/full-item-page.component.ts
  src/app/item-page/simple/item-page.component.html
  src/app/item-page/simple/item-page.component.spec.ts
  src/app/item-page/simple/item-page.component.ts
  src/app/shared/alert/alert.component.html
  src/app/shared/item/item-alerts/item-alerts.component.html
Labels: bug, high priority, authorization, 1 APPROVAL

#1564 Fix embargoed files download link not working on edit item page
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.ts
Labels: bug, high priority, authorization, 1 APPROVAL, e/4

#1581 Enable Bengali by default
  config/config.example.yml
  src/config/default-app-config.ts
  src/environments/environment.test.ts
Labels: i18n / l10n, code task
