Repository DSpace/dspace-angular, pull requests merged in 2022-12, with the labels that each got.

#1937 Addition of missing params
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL

#1991 Add CONTRIBUTING docs and resync with PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: 1 APPROVAL

#1989 Update to use GitHub CodeQL for code scanning (Angular UI)
  .github/workflows/codescan.yml
Labels: code task

#1955 The number of bitstreams on item pages are now configurable
  config/config.example.yml
  src/app/item-page/full/field-components/file-section/full-file-section.component.spec.ts
  src/app/item-page/full/field-components/file-section/full-file-section.component.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.ts
  src/config/default-app-config.ts
  src/config/item-config.interface.ts
  src/environments/environment.test.ts
Labels: improvement, 1 APPROVAL

#1977 [CST-7693] Missing Translations added
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
  src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html
  src/assets/i18n/en.json5
  src/themes/custom/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
Labels: i18n / l10n, 1 APPROVAL

#1984 Fix email validation regex to use email validation regex from HTML5 specs
  src/app/register-email-form/register-email-form.component.spec.ts
  src/app/register-email-form/register-email-form.component.ts
Labels: bug, 1 APPROVAL

#1946 Support Node v18
  .github/workflows/build.yml
  Dockerfile
  README.md
  cypress.json
  docker/docker-compose-ci.yml
  package.json
  yarn.lock
Labels: dependencies, quick win, code task

#2000 Update to latest Angular 13 & Remove unused dependencies
  angular.json
  package.json
  src/app/statistics-page/statistics-table/statistics-table.component.html
  src/app/thumbnail/thumbnail.component.scss
  src/styles/_functions.scss
  yarn.lock
Labels: dependencies, high priority

#1957 Use full community, collection and item names in breadcrumb navigation
  src/app/breadcrumbs/breadcrumbs.component.html
Labels: bug, usability, 1 APPROVAL

#2002 Fix Docker arm64 build
  Dockerfile
Labels: bug, backend: Docker

#1939 Make the CollectionDropdownComponent themeable
  src/app/my-dspace-page/collection-selector/collection-selector.component.html
  src/app/my-dspace-page/collection-selector/collection-selector.component.spec.ts
  src/app/shared/collection-dropdown/themed-collection-dropdown.component.ts
  src/app/shared/shared.module.ts
  src/app/submission/form/collection/submission-form-collection.component.html
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.html
  src/app/submission/import-external/import-external-collection/submission-import-external-collection.component.spec.ts
  src/themes/custom/app/shared/collection-dropdown/collection-dropdown.component.html
  src/themes/custom/app/shared/collection-dropdown/collection-dropdown.component.scss
  src/themes/custom/app/shared/collection-dropdown/collection-dropdown.component.ts
  src/themes/custom/eager-theme.module.ts
Labels: improvement, themes, 1 APPROVAL

#1942 make the ExternalSourceEntryImportModalComponent themeable by default
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/external-source-entry-import-modal/themed-external-source-entry-import-modal.component.ts
  src/app/shared/form/form.module.ts
  src/app/shared/theme-support/themed.component.ts
  src/themes/custom/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/external-source-entry-import-modal/external-source-entry-import-modal.component.html
  src/themes/custom/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/external-source-entry-import-modal/external-source-entry-import-modal.component.scss
  src/themes/custom/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/external-source-entry-import-modal/external-source-entry-import-modal.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: improvement, themes, 1 APPROVAL

#1981 Server side language headers
  src/app/core/locale/locale.service.ts
  src/app/core/locale/server-locale.service.ts
Labels: bug, 1 APPROVAL

#1992 Make it easier to know which theme is being used for a component
  src/app/shared/theme-support/themed.component.spec.ts
  src/app/shared/theme-support/themed.component.ts
Labels: themes, 1 APPROVAL

#1993 Fix statistics option position in header on different DSO pages
  src/app/collection-page/collection-page-routing.module.ts
  src/app/community-page/community-page-routing.module.ts
  src/app/item-page/item-page-routing.module.ts
Labels: bug, usability, 1 APPROVAL

#1987 Fix for related item thumbnail images.
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-relation-list-element/existing-relation-list-element.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-relation-list-element/existing-relation-list-element.component.spec.ts
Labels: bug, component: submission, high priority, 1 APPROVAL

#1976 Common Extendend Regex format for submission-forms
  src/app/shared/form/builder/parsers/field-parser.ts
  src/app/shared/form/builder/parsers/onebox-field-parser.spec.ts
Labels: bug, component: submission, 1 APPROVAL

#2003 Enable / disable spellcheck for textarea inputs via config
  config/config.example.yml
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/admin/admin-registries/bitstream-formats/format-form/format-form.component.ts
  src/app/collection-page/collection-form/collection-form.models.ts
  src/app/community-page/community-form/community-form.component.ts
  src/app/shared/form/builder/parsers/textarea-field-parser.ts
  src/config/default-app-config.ts
  src/config/form-config.interfaces.ts
  src/environments/environment.test.ts
Labels: new feature, 1 APPROVAL

#2008 Enable Polish language by default
  config/config.example.yml
  src/config/default-app-config.ts
Labels: i18n / l10n, code task
