Repository DSpace/dspace-angular, pull requests merged in 2023-10, with the labels that each got.

#2537 Translate community as 'Bereich' in de.json5
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2531 Fix browse by visual bug
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
Labels: bug, component: Discovery, 1 APPROVAL, port to dspace-7_x

#2536 Issue 2535 hide add more button submission if no disabled sections 7.x
  src/app/submission/form/section-add/submission-form-section-add.component.html
Labels: bug, component: submission, 1 APPROVAL, port to main

#2454 Check cssRules before css variables are read from stylesheet
  src/app/shared/sass-helper/css-variable.service.ts
Labels: bug, themes, 1 APPROVAL, port to dspace-7_x

#2504 Fix Angular SSR menu issues
  src/app/core/core.effects.ts
  src/app/shared/menu/menu.actions.ts
  src/app/shared/menu/menu.effects.spec.ts
  src/app/shared/menu/menu.effects.ts
  src/app/shared/menu/menu.reducer.spec.ts
  src/app/shared/menu/menu.reducer.ts
  src/app/shared/menu/menu.service.spec.ts
  src/app/shared/menu/menu.service.ts
Labels: bug, 1 APPROVAL, port to main

#2558 Revert 2454 "Check cssRules before css variables are read from stylesheet"
  src/app/shared/sass-helper/css-variable.service.ts
Labels: bug, high priority, 1 APPROVAL, port to dspace-7_x

#2439 Fix Request-a-Copy grant form optional message not optional in form validation
  src/app/request-copy/email-request-copy/email-request-copy.component.html
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2561 Fix RequestService test sometimes failing in CICD
  src/app/core/data/request.service.spec.ts
Labels: quick win, code task, 1 APPROVAL, testing framework, port to dspace-7_x

#2527 Minor header button improvements
  src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.html
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts
  src/app/header/context-help-toggle/context-help-toggle.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
  src/app/navbar/expandable-navbar-section/themed-expandable-navbar-section.component.ts
  src/app/navbar/navbar-section/navbar-section.component.ts
  src/app/navbar/navbar.component.html
  src/app/search-navbar/search-navbar.component.html
  src/app/search-navbar/search-navbar.component.scss
  src/app/shared/animations/slide.ts
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/dso-page/dso-edit-menu/dso-edit-expandable-menu-section/dso-edit-menu-expandable-section.component.ts
  src/app/shared/dso-page/dso-edit-menu/dso-edit-menu-section/dso-edit-menu-section.component.ts
  src/app/shared/impersonate-navbar/impersonate-navbar.component.html
  src/app/shared/impersonate-navbar/impersonate-navbar.component.spec.ts
  src/app/shared/impersonate-navbar/impersonate-navbar.component.ts
  src/app/shared/lang-switch/lang-switch.component.html
  src/app/shared/lang-switch/lang-switch.component.ts
  src/app/shared/lang-switch/themed-lang-switch.component.ts
  src/app/shared/shared.module.ts
  src/styles/_global-styles.scss
  src/themes/custom/app/shared/lang-switch/lang-switch.component.html
  src/themes/custom/app/shared/lang-switch/lang-switch.component.scss
  src/themes/custom/app/shared/lang-switch/lang-switch.component.ts
  src/themes/custom/eager-theme.module.ts
  src/themes/dspace/app/header/header.component.html
  src/themes/dspace/app/header/header.component.scss
  src/themes/dspace/app/navbar/navbar.component.html
  src/themes/dspace/app/navbar/navbar.component.scss
Labels: accessibility, themes, low priority, port to dspace-7_x

#2553 Added Serbian Cyrillic translation and corrected Serbian Latin translаtion
  config/config.example.yml
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/config/default-app-config.ts
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2530 Fix display LogInComponent turning blank when entering wrong username/password combination
  src/app/core/data/feature-authorization/authorization-data.service.ts
  src/app/core/data/feature-authorization/authorization-utils.ts
  src/app/shared/log-in/container/log-in-container.component.ts
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.ts
  src/app/shared/log-in/methods/log-in.methods-decorator.ts
Labels: bug, high priority, authentication: general, port to dspace-7_x

#2362 Making user menu component themeable
  src/app/navbar/navbar.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/themed-user-menu.component.ts
  src/app/shared/shared.module.ts
  src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.html
  src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.scss
  src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: themes, 1 APPROVAL, port to dspace-7_x

#2575 [Port to dspace-7_x] Fix display LogInComponent turning blank when entering wrong username/password combination
  src/app/core/data/feature-authorization/authorization-data.service.ts
  src/app/core/data/feature-authorization/authorization-utils.ts
  src/app/shared/log-in/container/log-in-container.component.ts
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.ts
  src/app/shared/log-in/methods/log-in.methods-decorator.ts
Labels: bug, high priority, authentication: general

#2576 [Port dspace-7_x] Making user menu component themeable
  src/app/navbar/navbar.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/themed-user-menu.component.ts
  src/app/shared/shared.module.ts
  src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.html
  src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.scss
  src/themes/custom/app/shared/auth-nav-menu/user-menu/user-menu.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: themes, 1 APPROVAL

#2423 Fix inherit policies at item move (Angular)
  src/app/item-page/edit-item-page/item-move/item-move.component.html
  src/assets/i18n/en.json5
Labels: bug, authorization, 1 APPROVAL

#2458 [Port to dspace-7_x] Fix inherit policies at item move (Angular)
  src/app/item-page/edit-item-page/item-move/item-move.component.html
  src/assets/i18n/en.json5
Labels: bug, authorization, 1 APPROVAL

#2542 Fix i18n labels and alignment in vocabulary-treeview
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2464 i18n production improvements
  package.json
  src/ngx-translate-loaders/translate-browser.loader.ts
  src/ngx-translate-loaders/translate-server.loader.ts
  webpack/helpers.ts
  webpack/webpack.common.ts
Labels: improvement, i18n / l10n, high priority, new feature, performance / caching, ux, port to main

#2506 allow insertion of multi-line scope notes in MD field registry
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.ts
Labels: bug, improvement, 1 APPROVAL, port to dspace-7_x

#2391 Created separate ePerson pages for create/edit
  src/app/access-control/access-control-routing-paths.ts
  src/app/access-control/access-control-routing.module.ts
  src/app/access-control/epeople-registry/epeople-registry.component.html
  src/app/access-control/epeople-registry/epeople-registry.component.spec.ts
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/access-control/epeople-registry/eperson-resolver.service.ts
  src/app/access-control/group-registry/group-form/group-form.component.html
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/eperson/group-data.service.ts
  src/app/shared/resource-policies/entry/resource-policy-entry.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, authorization, medium priority

#2551 [Port main] Created separate ePerson pages for create/edit
  src/app/access-control/access-control-routing-paths.ts
  src/app/access-control/access-control-routing.module.ts
  src/app/access-control/epeople-registry/epeople-registry.component.html
  src/app/access-control/epeople-registry/epeople-registry.component.spec.ts
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/access-control/epeople-registry/eperson-resolver.service.ts
  src/app/access-control/group-registry/group-form/group-form.component.html
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/eperson/group-data.service.ts
  src/app/shared/resource-policies/entry/resource-policy-entry.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, authorization, medium priority

#2441 Minor css variables fixes for header & navbar
  src/app/breadcrumbs/breadcrumbs.component.scss
  src/app/header/header.component.scss
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.scss
  src/app/navbar/navbar.component.scss
  src/styles/_custom_variables.scss
  src/themes/dspace/app/navbar/navbar.component.scss
Labels: bug, themes, 1 APPROVAL, port to dspace-7_x

#2442 New themed components & minor CSS fixes
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/browse-by/browse-by.module.ts
  src/app/forgot-password/forgot-password-email/forgot-email.component.html
  src/app/home-page/recent-item-list/recent-item-list.component.html
  src/app/login-page/login-page.component.html
  src/app/navbar/navbar.component.scss
  src/app/register-email-form/register-email-form.module.ts
  src/app/register-email-form/themed-registry-email-form.component.ts
  src/app/register-page/register-email/register-email.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/browse-by/shared-browse-by.module.ts
  src/app/shared/browse-by/themed-browse-by.component.ts
  src/app/shared/log-in/log-in.component.spec.ts
  src/app/shared/log-in/themed-log-in.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-filter.component.scss
  src/app/shared/shared.module.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.scss
  src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.ts
  src/themes/custom/app/login-page/login-page.component.html
  src/themes/custom/app/register-email-form/register-email-form.component.html
  src/themes/custom/app/register-email-form/register-email-form.component.ts
  src/themes/custom/app/shared/browse-by/browse-by.component.html
  src/themes/custom/app/shared/browse-by/browse-by.component.scss
  src/themes/custom/app/shared/browse-by/browse-by.component.ts
  src/themes/custom/app/shared/log-in/log-in.component.html
  src/themes/custom/app/shared/log-in/log-in.component.scss
  src/themes/custom/app/shared/log-in/log-in.component.ts
  src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html
  src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.scss
  src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.ts
  src/themes/custom/eager-theme.module.ts
  src/themes/custom/lazy-theme.module.ts
  src/themes/dspace/app/navbar/navbar.component.scss
Labels: themes, 1 APPROVAL, port to dspace-7_x

#2585 [Port dspace-7_x] New themed components & minor CSS fixes
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/browse-by/browse-by.module.ts
  src/app/forgot-password/forgot-password-email/forgot-email.component.html
  src/app/home-page/recent-item-list/recent-item-list.component.html
  src/app/login-page/login-page.component.html
  src/app/navbar/navbar.component.scss
  src/app/register-email-form/register-email-form.module.ts
  src/app/register-email-form/themed-registry-email-form.component.ts
  src/app/register-page/register-email/register-email.component.html
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/browse-by/shared-browse-by.module.ts
  src/app/shared/browse-by/themed-browse-by.component.ts
  src/app/shared/log-in/log-in.component.spec.ts
  src/app/shared/log-in/themed-log-in.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-filter.component.scss
  src/app/shared/shared.module.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.scss
  src/themes/custom/app/entity-groups/research-entities/item-pages/person/person.component.ts
  src/themes/custom/app/login-page/login-page.component.html
  src/themes/custom/app/register-email-form/register-email-form.component.html
  src/themes/custom/app/register-email-form/register-email-form.component.ts
  src/themes/custom/app/shared/browse-by/browse-by.component.html
  src/themes/custom/app/shared/browse-by/browse-by.component.scss
  src/themes/custom/app/shared/browse-by/browse-by.component.ts
  src/themes/custom/app/shared/log-in/log-in.component.html
  src/themes/custom/app/shared/log-in/log-in.component.scss
  src/themes/custom/app/shared/log-in/log-in.component.ts
  src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html
  src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.scss
  src/themes/custom/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.ts
  src/themes/custom/eager-theme.module.ts
  src/themes/custom/lazy-theme.module.ts
  src/themes/dspace/app/navbar/navbar.component.scss
Labels: themes, 1 APPROVAL

#2580 Check cssRules before css variables are read from stylesheet (again)
  src/app/shared/sass-helper/css-variable.service.ts
Labels: bug, high priority, themes, port to dspace-7_x
