Repository DSpace/dspace-angular, pull requests merged in 2023-02, with the labels that each got.

#2052 Update spanish translation
  src/assets/i18n/es.json5
Labels: i18n / l10n

#2053 Catalan translation
  config/config.example.yml
  src/assets/i18n/ca.json5
  src/config/default-app-config.ts
Labels: i18n / l10n

#2062 fixed ID 470077. Purpose of the link is not clear in context
  src/app/item-page/edit-item-page/item-operation/item-operation.component.html
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
Labels: bug, accessibility, 1 APPROVAL, component: Item

#1999 Fix user authorization issues with admin sidebar
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/menu.resolver.spec.ts
  src/app/menu.resolver.ts
  src/app/root/root.component.ts
  src/app/shared/menu/menu.service.spec.ts
  src/app/shared/menu/menu.service.ts
  src/app/shared/testing/menu-service.stub.ts
Labels: bug, usability, high priority, authorization, claimed: Atmire

#2028 Edit metadata redesign
  src/app/collection-page/collection-page.module.ts
  src/app/collection-page/edit-item-template-page/edit-item-template-page.component.html
  src/app/core/data/array-move-change-analyzer.service.spec.ts
  src/app/core/data/array-move-change-analyzer.service.ts
  src/app/core/data/object-updates/patch-operation-service/operations/metadata/metadata-patch-move-operation.model.ts
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/core/shared/operators.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-field-values/dso-edit-metadata-field-values.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-field-values/dso-edit-metadata-field-values.component.scss
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-field-values/dso-edit-metadata-field-values.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-field-values/dso-edit-metadata-field-values.component.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-form.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-form.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-headers/dso-edit-metadata-headers.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-headers/dso-edit-metadata-headers.component.scss
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-headers/dso-edit-metadata-headers.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-headers/dso-edit-metadata-headers.component.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-shared/dso-edit-metadata-cells.scss
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value-headers/dso-edit-metadata-value-headers.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value-headers/dso-edit-metadata-value-headers.component.scss
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value-headers/dso-edit-metadata-value-headers.component.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.scss
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.scss
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.html
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.scss
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
  src/app/dso-shared/dso-edit-metadata/themed-dso-edit-metadata.component.ts
  src/app/dso-shared/dso-shared.module.ts
  src/app/item-page/edit-item-page/edit-item-page.module.ts
  src/app/item-page/edit-item-page/edit-item-page.routing.module.ts
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.html
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.scss
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.spec.ts
  src/app/item-page/edit-item-page/item-metadata/edit-in-place-field/edit-in-place-field.component.ts
  src/app/item-page/edit-item-page/item-metadata/item-metadata.component.html
  src/app/item-page/edit-item-page/item-metadata/item-metadata.component.scss
  src/app/item-page/edit-item-page/item-metadata/item-metadata.component.spec.ts
  src/app/item-page/edit-item-page/item-metadata/item-metadata.component.ts
  src/app/item-page/edit-item-page/item-metadata/themed-item-metadata.component.ts
  src/app/item-page/simple/metadata-representation-list/metadata-representation-list.component.spec.ts
  src/app/item-page/simple/metadata-representation-list/metadata-representation-list.component.ts
  src/assets/i18n/en.json5
  src/styles/_bootstrap_variables_mapping.scss
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
  src/themes/custom/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.html
  src/themes/custom/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.scss
  src/themes/custom/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.ts
  src/themes/custom/app/item-page/edit-item-page/item-metadata/item-metadata.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: bug, usability, component: configurable entities, high priority, component: administrative tools

#2063 aria-selected added to Item Edit "Status" Tab. Fixed ID: 470076
  src/app/item-page/edit-item-page/edit-item-page.component.html
Labels: bug, 1 APPROVAL

#2076 XSRF Token to ServerAuthRequestService
  src/app/core/auth/auth-request.service.spec.ts
  src/app/core/auth/auth-request.service.ts
  src/app/core/auth/browser-auth-request.service.spec.ts
  src/app/core/auth/browser-auth-request.service.ts
  src/app/core/auth/server-auth-request.service.spec.ts
  src/app/core/auth/server-auth-request.service.ts
  src/app/core/services/server-xhr.service.ts
  src/app/core/xsrf/xsrf.interceptor.ts
  src/modules/app/server-app.module.ts
Labels: bug, authorization, 1 APPROVAL

#2016 Self register domain restriction
  src/app/core/data/eperson-registration.service.ts
  src/app/forgot-password/forgot-password-email/forgot-email.component.html
  src/app/forgot-password/forgot-password-email/forgot-email.component.ts
  src/app/register-email-form/register-email-form.component.html
  src/app/register-email-form/register-email-form.component.spec.ts
  src/app/register-email-form/register-email-form.component.ts
  src/app/register-page/register-email/register-email.component.html
  src/app/register-page/register-email/register-email.component.ts
  src/assets/i18n/en.json5
Labels: bug, high priority, authentication: general, authentication: password, 1 APPROVAL

#2033 Add Caching of SSR public pages. Update default Cache-Control HTTP header
  config/config.example.yml
  package.json
  server.ts
  src/config/cache-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
  src/index.html
  yarn.lock
Labels: high priority, performance / caching

#2072 Fixes DSpace/dspace-angular#2071
  src/app/home-page/recent-item-list/recent-item-list.component.ts
Labels: bug, 1 APPROVAL

#2025 System-wide alerts
  src/app/admin/admin-routing.module.ts
  src/app/core/data/system-wide-alert-data.service.spec.ts
  src/app/core/data/system-wide-alert-data.service.ts
  src/app/menu.resolver.ts
  src/app/root.module.ts
  src/app/root/root.component.html
  src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.html
  src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.scss
  src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.spec.ts
  src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.ts
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.html
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.scss
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.spec.ts
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.ts
  src/app/system-wide-alert/system-wide-alert-routing.module.ts
  src/app/system-wide-alert/system-wide-alert.model.ts
  src/app/system-wide-alert/system-wide-alert.module.ts
  src/app/system-wide-alert/system-wide-alert.resource-type.ts
  src/assets/i18n/en.json5
  src/themes/custom/lazy-theme.module.ts
Labels: new feature

#2018 Improve facet badges alignment
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.scss
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-range-option/search-facet-range-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-range-option/search-facet-range-option.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.scss
  src/app/shared/shared.module.ts
  src/app/shared/utils/short-number.pipe.spec.ts
  src/app/shared/utils/short-number.pipe.ts
Labels: bug

#2078 Let the production server "serve for direct CSR" if SSR is disabled or fails
  server.ts
  src/index.csr.html
  src/main.browser.ts
Labels: bug, high priority, performance / caching

#2079 Remove unnecessary subscriptions
  src/app/header/context-help-toggle/context-help-toggle.component.ts
  src/app/shared/context-help-wrapper/context-help-wrapper.component.ts
Labels: bug, 1 APPROVAL

#2017 Manage Subscriptions interface
  src/app/app-routing-paths.ts
  src/app/app-routing.module.ts
  src/app/collection-page/collection-page.component.html
  src/app/community-page/community-page.component.html
  src/app/core/core.module.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.html
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.ts
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.html
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.scss
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.spec.ts
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/subscriptions/models/subscription.model.ts
  src/app/shared/subscriptions/models/subscription.resource-type.ts
  src/app/shared/subscriptions/subscription-modal/subscription-modal.component.html
  src/app/shared/subscriptions/subscription-modal/subscription-modal.component.scss
  src/app/shared/subscriptions/subscription-modal/subscription-modal.component.spec.ts
  src/app/shared/subscriptions/subscription-modal/subscription-modal.component.ts
  src/app/shared/subscriptions/subscription-view/subscription-view.component.html
  src/app/shared/subscriptions/subscription-view/subscription-view.component.scss
  src/app/shared/subscriptions/subscription-view/subscription-view.component.spec.ts
  src/app/shared/subscriptions/subscription-view/subscription-view.component.ts
  src/app/shared/subscriptions/subscriptions-data.service.spec.ts
  src/app/shared/subscriptions/subscriptions-data.service.ts
  src/app/shared/subscriptions/subscriptions.module.ts
  src/app/shared/testing/router.stub.ts
  src/app/shared/testing/subscriptions-data.mock.ts
  src/app/shared/testing/test-module.ts
  src/app/subscriptions-page/subscriptions-page-routing.module.ts
  src/app/subscriptions-page/subscriptions-page.component.html
  src/app/subscriptions-page/subscriptions-page.component.scss
  src/app/subscriptions-page/subscriptions-page.component.spec.ts
  src/app/subscriptions-page/subscriptions-page.component.ts
  src/app/subscriptions-page/subscriptions-page.module.ts
  src/assets/i18n/en.json5
Labels: new feature, 1 APPROVAL

#2061 Collection in workflow tasks
  src/app/my-dspace-page/my-dspace-search.module.ts
  src/app/shared/object-collection/shared/mydspace-item-collection/item-collection.component.html
  src/app/shared/object-collection/shared/mydspace-item-collection/item-collection.component.scss
  src/app/shared/object-collection/shared/mydspace-item-collection/item-collection.component.ts
  src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.html
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/themed-item-list-preview.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.html
Labels: bug, 1 APPROVAL

#2091 Fix for "cannot read properties of undefined" error for Withdrawn Items
  src/app/core/breadcrumbs/dso-breadcrumbs.service.ts
Labels: bug, high priority, 1 APPROVAL

#2075 Pass `ng-content` to themed child components
  src/app/item-page/full/field-components/file-section/full-file-section.component.html
  src/app/item-page/simple/field-components/file-section/file-section.component.html
  src/app/item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/process-page/detail/process-detail.component.html
  src/app/shared/file-download-link/themed-file-download-link.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/theme-support/themed.component.html
  src/app/shared/theme-support/themed.component.ts
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/themes/custom/app/shared/file-download-link/file-download-link.component.html
  src/themes/custom/app/shared/file-download-link/file-download-link.component.scss
  src/themes/custom/app/shared/file-download-link/file-download-link.component.ts
  src/themes/custom/eager-theme.module.ts
Labels: themes, 1 APPROVAL, low priority

#2093 Add flag to show/hide csv export button
  src/app/search-page/search-page.component.html
  src/app/shared/search/search-results/search-results.component.html
  src/app/shared/search/search-results/search-results.component.ts
  src/app/shared/search/search-results/themed-search-results.component.ts
  src/app/shared/search/search.component.html
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
Labels: bug, 1 APPROVAL

#2100 Fix issue with missing matcher providers
  src/app/app.module.ts
  src/app/shared/form/form.module.ts
Labels: bug, high priority, 1 APPROVAL

#2098 German translation fixes in security form
  src/assets/i18n/de.json5
Labels: i18n / l10n

#2102 Fix for "No option appears for Bundle when the user is loading a bitstream of an item"
  src/app/shared/shared.module.ts
Labels: bug, high priority, 1 APPROVAL

#2107 Fix issue with admin reset password functionality
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
Labels: bug, high priority

#2104 [CST-8952] Fix issue with admin reset password functionality
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
Labels: bug, high priority, 1 APPROVAL

#2117 Fixed UI issues #2087 and #2088
  src/app/item-page/simple/field-components/file-section/file-section.component.html
  src/app/shared/file-download-link/file-download-link.component.html
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html
Labels: bug, 1 APPROVAL

#2113 avoiding error when user unselect a filter option
  src/app/shared/search/search-labels/search-label/search-label.component.ts
  src/app/shared/search/search-labels/search-labels.component.ts
Labels: bug, 1 APPROVAL

#2121 avoiding drag and drop in put for multiple select option
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
Labels: bug, 1 APPROVAL

#2111 Fix false positive tests caused by `fixture.debugElement.query().toBeDefined()` & `toBeUndefined()`
  src/app/access-control/group-registry/group-form/members-list/members-list.component.spec.ts
  src/app/access-control/group-registry/group-form/members-list/members-list.component.ts
  src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.spec.ts
  src/app/core/locale/locale.interceptor.spec.ts
  src/app/core/xsrf/xsrf.interceptor.spec.ts
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/mirador-viewer/mirador-viewer.component.spec.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts
  src/app/menu.resolver.spec.ts
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/lang-switch/lang-switch.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/edit-metadata/claimed-task-actions-edit-metadata.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/reject/claimed-task-actions-reject.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/return-to-pool/claimed-task-actions-return-to-pool.component.spec.ts
  src/app/shared/mydspace-actions/pool-task/pool-task-actions.component.spec.ts
  src/app/shared/mydspace-actions/workflowitem/workflowitem-actions.component.spec.ts
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.spec.ts
  src/app/shared/object-collection/object-collection.component.spec.ts
  src/app/shared/object-collection/shared/mydspace-item-status/my-dspace-item-status.component.spec.ts
  src/app/shared/object-collection/shared/mydspace-item-submitter/item-submitter.component.spec.ts
  src/app/shared/page-size-selector/page-size-selector.component.spec.ts
  src/app/shared/search/search-settings/search-settings.component.spec.ts
  src/app/shared/search/search-switch-configuration/search-switch-configuration.component.spec.ts
  src/app/submission/form/section-add/submission-form-section-add.component.spec.ts
  src/app/submission/sections/container/section-container.component.spec.ts
Labels: bug, code task, low priority, e/4, testing framework, claimed: Atmire

#2084 ul and li replaced to role list and listitem
  src/app/shared/form/chips/chips.component.html
  src/app/shared/form/chips/chips.component.spec.ts
Labels: bug, accessibility, 1 APPROVAL
