Repository DSpace/dspace-angular, pull requests merged in 2023-06, with the labels that each got.

#2286 Remove scripts/webpack.js
  README.md
  scripts/webpack.js
Labels: bug, 1 APPROVAL

#2287 Contribution to the Portuguese (pt-PT) translation of DSpace
  src/assets/i18n/pt-PT.json5
Labels: i18n / l10n, 1 APPROVAL

#2243 Handled collection step visibility on a submission form
  src/app/submission/form/collection/submission-form-collection.component.html
  src/app/submission/form/collection/submission-form-collection.component.spec.ts
  src/app/submission/form/collection/submission-form-collection.component.ts
  src/app/submission/form/submission-form.component.html
  src/app/submission/form/submission-form.component.spec.ts
  src/app/submission/form/submission-form.component.ts
  src/app/submission/sections/sections-type.ts
  src/app/submission/sections/visibility-type.ts
Labels: bug, component: submission, 1 APPROVAL, claimed: 4Science

#2036 Adding themed components for EditBitstreamPageComponent and ItemStatusComponent
  src/app/bitstream-page/bitstream-page-routing.module.ts
  src/app/bitstream-page/bitstream-page.module.ts
  src/app/bitstream-page/edit-bitstream-page/themed-edit-bitstream-page.component.ts
  src/app/item-page/edit-item-page/edit-item-page.module.ts
  src/app/item-page/edit-item-page/edit-item-page.routing.module.ts
  src/app/item-page/edit-item-page/item-status/themed-item-status.component.ts
  src/themes/custom/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html
  src/themes/custom/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.scss
  src/themes/custom/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/themes/custom/app/item-page/edit-item-page/item-status/item-status.component.html
  src/themes/custom/app/item-page/edit-item-page/item-status/item-status.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: 1 APPROVAL, low priority

#2231 Possible fix for browse-by-date links
  src/app/shared/starts-with/date/starts-with-date.component.ts
  src/app/shared/starts-with/starts-with-abstract.component.ts
Labels: bug, component: Discovery, 1 APPROVAL

#2202 Themeable `SubmissionSectionUploadFileComponent`
  src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
  src/app/submission/sections/upload/file/themed-section-upload-file.component.ts
  src/app/submission/sections/upload/section-upload.component.html
  src/app/submission/submission.module.ts
  src/themes/custom/app/submission/sections/upload/file/section-upload-file.component.html
  src/themes/custom/app/submission/sections/upload/file/section-upload-file.component.scss
  src/themes/custom/app/submission/sections/upload/file/section-upload-file.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: improvement, component: submission, themes

#2274 src/assets/i18n: fix English permission string
  src/assets/i18n/en.json5
Labels: i18n / l10n, quick win, 1 APPROVAL

#2255 Add label to starts-with-text input field
  src/app/shared/starts-with/text/starts-with-text.component.html
  src/assets/i18n/en.json5
Labels: accessibility, 1 APPROVAL

#2246 Add filter name to search filter button aria-label.
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
Labels: bug, accessibility, 1 APPROVAL

#2272 src/assets: add i18n string for publisher
  src/assets/i18n/en.json5
Labels: i18n / l10n, tools:import-sources

#2215 Browse by Controlled Vocabulary Page
  src/app/browse-by/browse-by-guard.spec.ts
  src/app/browse-by/browse-by-switcher/browse-by-decorator.ts
  src/app/browse-by/browse-by-switcher/browse-by-switcher.component.spec.ts
  src/app/browse-by/browse-by-switcher/browse-by-switcher.component.ts
  src/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.html
  src/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.scss
  src/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.spec.ts
  src/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.ts
  src/app/browse-by/browse-by-taxonomy-page/themed-browse-by-taxonomy-page.component.ts
  src/app/browse-by/browse-by.module.ts
  src/app/core/browse/browse-definition-data.service.ts
  src/app/core/browse/browse.service.spec.ts
  src/app/core/browse/browse.service.ts
  src/app/core/core.module.ts
  src/app/core/data/browse-response-parsing.service.spec.ts
  src/app/core/data/browse-response-parsing.service.ts
  src/app/core/data/dso-response-parsing.service.ts
  src/app/core/data/request.models.ts
  src/app/core/shared/browse-definition.model.ts
  src/app/core/shared/flat-browse-definition.model.ts
  src/app/core/shared/flat-browse-definition.resource-type.ts
  src/app/core/shared/hierarchical-browse-definition.model.ts
  src/app/core/shared/hierarchical-browse-definition.resource-type.ts
  src/app/core/shared/non-hierarchical-browse-definition.ts
  src/app/core/shared/value-list-browse-definition.model.ts
  src/app/core/shared/value-list-browse-definition.resource-type.ts
  src/app/core/submission/vocabularies/vocabulary.service.ts
  src/app/item-page/field-components/metadata-values/metadata-values.component.ts
  src/app/navbar/navbar.component.spec.ts
  src/app/shared/dso-page/dso-edit-menu.resolver.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.ts
  src/app/shared/form/form.module.ts
  src/app/shared/form/vocabulary-treeview-modal/vocabulary-treeview-modal.component.html
  src/app/shared/form/vocabulary-treeview-modal/vocabulary-treeview-modal.component.scss
  src/app/shared/form/vocabulary-treeview-modal/vocabulary-treeview-modal.component.spec.ts
  src/app/shared/form/vocabulary-treeview-modal/vocabulary-treeview-modal.component.ts
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview-node.model.ts
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.scss
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.spec.ts
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.service.spec.ts
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.service.ts
  src/app/shared/object-list/metadata-representation-list-element/browse-link/browse-link-metadata-list-element.component.ts
  src/app/shared/object-list/metadata-representation-list-element/plain-text/plain-text-metadata-list-element.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/app/shared/testing/browse-definition-data-service.stub.ts
  src/assets/i18n/en.json5
  src/modules/app/browser-app.module.ts
  src/themes/custom/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.html
  src/themes/custom/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.scss
  src/themes/custom/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: component: Discovery, new feature

#2280 Fix multiple bitstream deletion not working
  src/app/core/data/bitstream-data.service.spec.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/shared/testing/bitstream-data-service.stub.ts
Labels: bug, high priority, 1 APPROVAL, e/24, claimed: Atmire

#2021 "default" search configuration fix
  src/app/shared/search/search.component.ts
Labels: bug, 1 APPROVAL

#2228 [DURACOM-131] Show output files in separate lines and a refresh spinner if status is running
  src/app/process-page/detail/process-detail.component.html
  src/app/process-page/detail/process-detail.component.spec.ts
  src/app/process-page/detail/process-detail.component.ts
Labels: bug, usability, 1 APPROVAL, tools:processes

#2177 Added input validation for new metadata field submissions & fixed some other small bugs
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.spec.ts
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.ts
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.spec.ts
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, 1 APPROVAL, medium priority, claimed: Atmire

#2234 Update of mirador configuration and webpack
  .gitignore
  src/mirador-viewer/config.default.js
  webpack/webpack.mirador.config.ts
Labels: improvement, 1 APPROVAL, integration: IIIF

#2296 Browse by Controlled Vocab on Community/Collection homepages
  src/app/browse-by/browse-by-taxonomy-page/browse-by-taxonomy-page.component.html
  src/assets/i18n/en.json5
Labels: bug, component: Discovery

#2293 Delete EPerson from "Edit EPerson" form
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/core/data/request.service.ts
Labels: bug, high priority, claimed: 4Science

#2248 Implement Signposting on angular side
  server.ts
  src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.spec.ts
  src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.ts
  src/app/core/data/signposting-data.service.spec.ts
  src/app/core/data/signposting-data.service.ts
  src/app/core/data/signposting-links.model.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/core/services/server-response.service.ts
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/full/full-item-page.component.ts
  src/app/item-page/simple/item-page.component.spec.ts
  src/app/item-page/simple/item-page.component.ts
  src/modules/app/server-init.service.ts
Labels: new feature, 1 APPROVAL, claimed: 4Science

#2301 [CST-5729] fix issue with signposting endpoint url replace
  src/app/core/data/signposting-data.service.spec.ts
  src/app/core/data/signposting-data.service.ts
Labels: bug, 1 APPROVAL

#2212 Import saf via URL
  src/app/admin/admin-import-batch-page/batch-import-page.component.html
  src/app/admin/admin-import-batch-page/batch-import-page.component.spec.ts
  src/app/admin/admin-import-batch-page/batch-import-page.component.ts
  src/app/admin/admin.module.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL, claimed: 4Science

#2299 Fix Proxy Timeouts on browse by pages
  src/app/browse-by/browse-by-guard.spec.ts
  src/app/browse-by/browse-by-guard.ts
Labels: bug, component: Discovery, high priority, 1 APPROVAL

#2306 src/assets/i18n/en.json5: lint
  src/assets/i18n/en.json5
Labels: improvement, i18n / l10n, quick win, 1 APPROVAL

#2305 src/assets: update fi.json5
  src/assets/i18n/fi.json5
Labels: i18n / l10n, quick win

#2213 Primary bitstream toggle implementation
  src/app/bitstream-page/bitstream-page.resolver.ts
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/app/core/data/primary-bitstream.service.spec.ts
  src/app/core/data/primary-bitstream.service.ts
  src/assets/i18n/en.json5
Labels: bug, high priority, component: Item, e/60, claimed: Atmire, needs funding

#2244 Make request-copy grant message an optional addition; main text is in backend.
  src/app/request-copy/email-request-copy/email-request-copy.component.html
  src/app/request-copy/grant-request-copy/grant-request-copy.component.spec.ts
  src/app/request-copy/grant-request-copy/grant-request-copy.component.ts
  src/assets/i18n/en.json5
Labels: improvement, 1 APPROVAL

#2250 Displaying item counts at Communities and Collections list view.
  src/app/community-list-page/community-list/community-list.component.html
  src/app/core/shared/collection.model.ts
  src/app/core/shared/community.model.ts
  src/app/shared/object-list/collection-list-element/collection-list-element.component.html
  src/app/shared/object-list/collection-list-element/collection-list-element.component.spec.ts
  src/app/shared/object-list/community-list-element/community-list-element.component.html
Labels: bug, component: Discovery, new feature, 1 APPROVAL

#2304 Add possibility to store response's headers into the SSR cache
  server.ts
  src/config/cache-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
Labels: bug, 1 APPROVAL

#2313 [CST-5729] Fix duplicate links for download page
  src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.ts
Labels: bug, 1 APPROVAL

#2252 Adding/removing relationships in the submission form does not update the view automatically
  src/app/shared/form/form.component.html
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
Labels: bug, component: submission, component: configurable entities, high priority, 1 APPROVAL, e/20, claimed: Atmire

#2318 resolve German translation inconsistency in scopenote
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL

#2311 Multiple uploaders in the same page don't work
  src/app/shared/upload/uploader/uploader.component.html
Labels: bug, 1 APPROVAL

#2297 Fixed read-only visibility for submission form fields
  src/app/core/submission/submission-field-scope-type.ts
  src/app/core/submission/submission-scope-type.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/ds-dynamic-concat.model.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/ds-dynamic-input.model.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.scss
  src/app/shared/form/builder/models/form-field.model.ts
  src/app/shared/form/builder/parsers/concat-field-parser.ts
  src/app/shared/form/builder/parsers/field-parser.ts
  src/app/shared/form/builder/parsers/onebox-field-parser.ts
  src/app/shared/form/builder/parsers/row-parser.ts
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
  src/app/submission/sections/sections.service.ts
Labels: bug, 1 APPROVAL

#2308 Edit section in sidebar menu: edit page of selected item / collection / community does not refresh
  src/app/collection-page/collection-form/collection-form.component.ts
  src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.spec.ts
  src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.ts
  src/app/community-page/community-form/community-form.component.ts
  src/app/item-page/edit-item-page/item-status/item-status.component.ts
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-metadata/comcol-metadata.component.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/edit-comcol-page.component.ts
Labels: bug, component: administrative tools, performance / caching, 1 APPROVAL

#2292 Portuguese (pt_PT) translation keys update
  src/assets/i18n/pt-PT.json5
Labels: i18n / l10n, 1 APPROVAL

#2319 Fix typo for the word Series
  src/assets/i18n/en.json5
Labels: i18n / l10n, 1 APPROVAL

#2288 Add referrer to pageview event
  src/app/core/services/browser.referrer.service.spec.ts
  src/app/core/services/browser.referrer.service.ts
  src/app/core/services/referrer.service.ts
  src/app/core/services/server.referrer.service.spec.ts
  src/app/core/services/server.referrer.service.ts
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-issue/journal-issue-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal-volume/journal-volume-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-grid-elements/search-result-grid-elements/journal/journal-search-result-grid-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-issue/journal-issue-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal-volume/journal-volume-search-result-list-element.component.html
  src/app/entity-groups/journal-entities/item-list-elements/search-result-list-elements/journal/journal-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/org-unit/org-unit-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/person/person-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-grid-elements/search-result-grid-elements/project/project-search-result-grid-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/org-unit/org-unit-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.html
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/project/project-search-result-list-element.component.html
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.html
  src/app/shared/object-grid/collection-grid-element/collection-grid-element.component.html
  src/app/shared/object-grid/community-grid-element/community-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.html
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.html
  src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html
  src/app/shared/object-list/collection-list-element/collection-list-element.component.html
  src/app/shared/object-list/community-list-element/community-list-element.component.html
  src/app/shared/object-list/search-result-list-element/collection-search-result/collection-search-result-list-element.component.html
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.html
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.html
  src/app/statistics/angulartics/dspace-provider.spec.ts
  src/app/statistics/angulartics/dspace-provider.ts
  src/app/statistics/angulartics/dspace/view-tracker.component.ts
  src/app/statistics/statistics.service.spec.ts
  src/app/statistics/statistics.service.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
Labels: bug, component: statistics, 1 APPROVAL, claimed: Atmire

#2322 src/assets/i18n: update English strings
  src/assets/i18n/en.json5
Labels: i18n / l10n, quick win

#2326 [DURACOM-160] Hide "Send feedback" link when CanSendFeedback is false
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
Labels: bug, 1 APPROVAL

#2316 src/app: adjust item count style
  src/app/community-list-page/community-list/community-list.component.html
  src/app/shared/object-list/collection-list-element/collection-list-element.component.html
  src/app/shared/object-list/community-list-element/community-list-element.component.html
Labels: quick win, 1 APPROVAL

#2245 Make some request-copy components themeable.
  src/app/request-copy/deny-request-copy/deny-request-copy.component.html
  src/app/request-copy/deny-request-copy/themed-deny-request-copy.component.ts
  src/app/request-copy/email-request-copy/themed-email-request-copy.component.ts
  src/app/request-copy/grant-request-copy/grant-request-copy.component.html
  src/app/request-copy/grant-request-copy/themed-grant-request-copy.component.ts
  src/app/request-copy/request-copy-routing.module.ts
  src/app/request-copy/request-copy.module.ts
  src/themes/custom/app/request-copy/deny-request-copy/deny-request-copy.component.html
  src/themes/custom/app/request-copy/deny-request-copy/deny-request-copy.component.scss
  src/themes/custom/app/request-copy/deny-request-copy/deny-request-copy.component.ts
  src/themes/custom/app/request-copy/email-request-copy/email-request-copy.component.html
  src/themes/custom/app/request-copy/email-request-copy/email-request-copy.component.scss
  src/themes/custom/app/request-copy/email-request-copy/email-request-copy.component.ts
  src/themes/custom/app/request-copy/grant-request-copy/grant-request-copy.component.html
  src/themes/custom/app/request-copy/grant-request-copy/grant-request-copy.component.scss
  src/themes/custom/app/request-copy/grant-request-copy/grant-request-copy.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: themes, 1 APPROVAL

#2277 new project metadata representation component
  src/app/entity-groups/research-entities/metadata-representations/project/project-item-metadata-list-element.component.html
  src/app/entity-groups/research-entities/metadata-representations/project/project-item-metadata-list-element.component.spec.ts
  src/app/entity-groups/research-entities/metadata-representations/project/project-item-metadata-list-element.component.ts
  src/app/entity-groups/research-entities/research-entities.module.ts
Labels: bug, component: configurable entities, 1 APPROVAL

#2332 "Add Collection" form loads
  src/app/collection-page/collection-form/collection-form.component.ts
Labels: bug, 1 APPROVAL

#2330 Add the ability to expand / collapse via keyboard
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
Labels: bug, accessibility, 1 APPROVAL

#2334 fix for bitstreams are not visible to crawlers when caching is enabled
  server.ts
Labels: bug, component: SEO, 1 APPROVAL

#2331 Implement basic 301 Redirect for DSpace 6.x URLs when SSR is used.
  src/app/core/data/dso-redirect.service.spec.ts
  src/app/core/data/dso-redirect.service.ts
  src/app/core/services/hard-redirect.service.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
Labels: bug, component: SEO
