Repository DSpace/dspace-angular, pull requests merged in 2023-03, with the labels that each got.

#2092 Buttons have same name but different actions.
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html
  src/assets/i18n/en.json5
Labels: bug, accessibility, 1 APPROVAL

#2085 ID 469871. List or list item is not marked up properly.
  src/app/shared/collection-dropdown/collection-dropdown.component.html
  src/app/submission/form/collection/submission-form-collection.component.ts
Labels: bug, accessibility, 1 APPROVAL

#2109 Spanish translation contribution
  src/assets/i18n/es.json5
Labels: i18n / l10n

#2132 Fixed: Clear metadata if value has not set. Reference issue no #1612
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
Labels: bug, 1 APPROVAL

#2141 pageSize applied in Recent Submissions
  src/app/collection-page/collection-page.component.ts
Labels: bug, 1 APPROVAL

#2139 browse-by-metadata-page works correctly on numeric 'value' param
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
Labels: bug, component: Discovery, 1 APPROVAL

#2130 EPerson creation page changed
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL

#2142 Update hu language file with dspace7.5 strings
  src/assets/i18n/hu.json5
Labels: i18n / l10n, 1 APPROVAL

#2151 New themed components
  src/app/app-routing.module.ts
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
  src/app/info/feedback/feedback-form/themed-feedback-form.component.ts
  src/app/info/feedback/feedback.component.html
  src/app/info/info.module.ts
  src/app/item-page/full/full-item-page.component.html
  src/app/item-page/item-page.module.ts
  src/app/item-page/media-viewer/media-viewer-image/media-viewer-image.component.ts
  src/app/item-page/media-viewer/media-viewer-image/themed-media-viewer-image.component.ts
  src/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.ts
  src/app/item-page/media-viewer/media-viewer-video/themed-media-viewer-video.component.ts
  src/app/item-page/media-viewer/media-viewer.component.html
  src/app/item-page/media-viewer/media-viewer.component.spec.ts
  src/app/item-page/media-viewer/media-viewer.component.ts
  src/app/item-page/media-viewer/themed-media-viewer.component.ts
  src/app/item-page/simple/field-components/specific-field/title/themed-item-page-field.component.ts
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html
  src/app/shared/rss-feed/rss.component.ts
  src/app/shared/shared.module.ts
  src/themes/custom/app/info/feedback/feedback-form/feedback-form.component.html
  src/themes/custom/app/info/feedback/feedback-form/feedback-form.component.scss
  src/themes/custom/app/info/feedback/feedback-form/feedback-form.component.ts
  src/themes/custom/app/item-page/media-viewer/media-viewer-image/media-viewer-image.component.html
  src/themes/custom/app/item-page/media-viewer/media-viewer-image/media-viewer-image.component.scss
  src/themes/custom/app/item-page/media-viewer/media-viewer-image/media-viewer-image.component.ts
  src/themes/custom/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.html
  src/themes/custom/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.scss
  src/themes/custom/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.ts
  src/themes/custom/app/item-page/media-viewer/media-viewer.component.html
  src/themes/custom/app/item-page/media-viewer/media-viewer.component.scss
  src/themes/custom/app/item-page/media-viewer/media-viewer.component.ts
  src/themes/custom/app/item-page/simple/field-components/specific-field/title/item-page-title-field.component.html
  src/themes/custom/app/item-page/simple/field-components/specific-field/title/item-page-title-field.component.ts
  src/themes/custom/lazy-theme.module.ts
Labels: themes

#2126 Ensure cookie language is valid
  src/app/core/locale/locale.service.spec.ts
  src/app/core/locale/locale.service.ts
  src/environments/environment.test.ts
Labels: bug, i18n / l10n, 1 APPROVAL

#2166 Update en.json5
  src/assets/i18n/en.json5
  src/assets/i18n/fi.json5
Labels: i18n / l10n, 1 APPROVAL

#2149 Media viewer thumbnails don't take viewport width into account
  src/app/item-page/media-viewer/media-viewer-image/media-viewer-image.component.scss
  src/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.scss
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
Labels: bug, 1 APPROVAL, component: Item

#2154 Update to fixe french labels for System-wide alert
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL

#2171 Added upper limit to browse by date (year)
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.spec.ts
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/core/browse/browse.service.ts
Labels: bug, component: Discovery, 1 APPROVAL

#2143 disabled the posibility to change the collection for workflow items to prevent errors
  src/app/submission/edit/submission-edit.component.html
  src/app/submission/edit/submission-edit.component.ts
  src/app/submission/form/collection/submission-form-collection.component.html
  src/app/submission/form/collection/submission-form-collection.component.ts
  src/app/submission/form/submission-form.component.html
  src/app/submission/form/submission-form.component.ts
  src/app/workflowitems-edit-page/workflowitems-edit-page-routing.module.ts
Labels: bug, component: workflow, 1 APPROVAL
