Repository DSpace/dspace-angular, pull requests merged in 2023-09, with the labels that each got.

#2448 Spanish translation updated to 7.6
  src/assets/i18n/es.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2432 Fix to Value of dropdown changes automatically on item submission page
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
Labels: bug, component: submission, 1 APPROVAL, port to dspace-7_x

#2457 config/config.example.yml: fix example syntax
  config/config.example.yml
Labels: quick win, configuration, port to dspace-7_x

#2361 Fix tree not updating when switching between "Browse by Vocabulary" pages
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
  src/assets/i18n/en.json5
Labels: bug, usability, component: Discovery, performance / caching, port to dspace-7_x

#2366 CSV export fixes
  src/app/item-page/simple/related-entities/related-entities-search/related-entities-search.component.html
  src/app/shared/search/search-export-csv/search-export-csv.component.ts
Labels: bug, tools: export, 1 APPROVAL, port to dspace-7_x

#2376 Search query is not set by default when opening an external sources tab
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/themed-dynamic-lookup-relation-external-source-tab.component.ts
Labels: bug, tools: import, 1 APPROVAL, tools:import-sources

#2396 [Port dspace-7_x] Search query is not set by default when opening an external sources tab
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/dynamic-lookup-relation-external-source-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/external-source-tab/themed-dynamic-lookup-relation-external-source-tab.component.ts
Labels: bug, tools: import, 1 APPROVAL, tools:import-sources

#2349 Fix `setStaleByHrefSubstring` not emitting true when all requests are stale
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
Labels: bug, 1 APPROVAL

#2404 [Port dspace-7_x] Fix `setStaleByHrefSubstring` not emitting true when all requests are stale
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
Labels: bug, 1 APPROVAL

#2412 remove redundant cache default values from server.ts
  server.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2421 🚸remove thumbnail from file-upload section and show bitstream format …
  src/app/core/submission/models/workspaceitem-section-upload-file.model.ts
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/app/submission/sections/upload/file/view/section-upload-file-view.component.html
  src/app/submission/sections/upload/file/view/section-upload-file-view.component.ts
Labels: bug, component: submission, port to dspace-7_x

#2445 Fix to Metadata Registry create new metadata schema doesn't appear without reload #1081
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.ts
Labels: bug, high priority, performance / caching, 1 APPROVAL, port to dspace-7_x

#2414 Made it possible to reorder the login methods
  src/app/core/auth/auth.interceptor.ts
  src/app/core/auth/auth.reducer.spec.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/models/auth.method.ts
  src/app/shared/log-in/container/log-in-container.component.spec.ts
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.spec.ts
  src/app/shared/log-in/log-in.component.ts
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.html
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.spec.ts
  src/app/shared/log-in/methods/password/log-in-password.component.html
  src/app/shared/log-in/methods/password/log-in-password.component.scss
  src/app/shared/log-in/methods/password/log-in-password.component.spec.ts
  src/app/shared/log-in/methods/password/log-in-password.component.ts
  src/app/shared/testing/auth-service.stub.ts
  src/assets/i18n/en.json5
Labels: bug, authentication: general, authentication: LDAP, authentication: password, authentication: Shibboleth, medium priority, claimed: Atmire

#2488 [Port dspace-7_x] Made it possible to reorder the login methods
  src/app/core/auth/auth.interceptor.ts
  src/app/core/auth/auth.reducer.spec.ts
  src/app/core/auth/auth.reducer.ts
  src/app/core/auth/models/auth.method.ts
  src/app/shared/log-in/container/log-in-container.component.spec.ts
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.spec.ts
  src/app/shared/log-in/log-in.component.ts
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.html
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.spec.ts
  src/app/shared/log-in/methods/password/log-in-password.component.html
  src/app/shared/log-in/methods/password/log-in-password.component.scss
  src/app/shared/log-in/methods/password/log-in-password.component.spec.ts
  src/app/shared/log-in/methods/password/log-in-password.component.ts
  src/app/shared/testing/auth-service.stub.ts
  src/assets/i18n/en.json5
Labels: bug, authentication: general, authentication: LDAP, authentication: password, authentication: Shibboleth, medium priority, claimed: Atmire

#2493 Correct text of help info on edit group page
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2451 Graceful shutdown on SIGINT (e.g. from 'pm2 stop').
  package.json
  server.ts
  yarn.lock
Labels: improvement, port to dspace-7_x

#2505 remove obsolete label element in metadata-schema.component.html
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2422 Update fi.json5
  src/assets/i18n/fi.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2502 Don't capitalize metadata values in search
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-selected-option/search-facet-selected-option.component.html
  src/app/shared/search/search-labels/search-label/search-label.component.html
Labels: bug, component: Discovery, quick win, port to main

#2508 Serbian (Latin) translation
  config/config.example.yml
  src/assets/i18n/sr-lat.json5
  src/config/default-app-config.ts
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2473 Fix some routes not using the correct baseHref
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.spec.ts
  src/app/shared/cookies/klaro-configuration.ts
Labels: bug, quick win, medium priority, component: Item, port to dspace-7_x

#2518 Fix missing or wrong Italian translations
  src/assets/i18n/it.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2510 Fix multiple api calls on route change
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
  src/app/core/data/root-data.service.spec.ts
  src/app/core/data/root-data.service.ts
  src/app/core/server-check/server-check.guard.spec.ts
  src/app/core/server-check/server-check.guard.ts
  src/modules/app/browser-init.service.ts
Labels: bug, high priority, performance / caching, port to main

#2385 Move subscription button to DSO edit menu
  src/app/collection-page/collection-page.component.html
  src/app/community-page/community-page.component.html
  src/app/shared/dso-page/dso-edit-menu.resolver.spec.ts
  src/app/shared/dso-page/dso-edit-menu.resolver.ts
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.html
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.scss
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.spec.ts
  src/app/shared/dso-page/dso-page-subscription-button/dso-page-subscription-button.component.ts
  src/app/shared/shared.module.ts
Labels: bug, 1 APPROVAL, ux, integration: syndication feed, port to dspace-7_x

#2529 [Port main] Fix multiple api calls on route change
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
  src/app/core/data/root-data.service.spec.ts
  src/app/core/data/root-data.service.ts
  src/app/core/server-check/server-check.guard.spec.ts
  src/app/core/server-check/server-check.guard.ts
  src/modules/app/browser-init.service.ts
Labels: bug, high priority, performance / caching
