Repository DSpace/dspace-angular, pull requests merged in 2023-01, with the labels that each got.

#1923 Customizability of theme colours
  src/app/navbar/navbar.component.scss
  src/app/shared/object-collection/shared/mydspace-item-status/my-dspace-item-status.component.spec.ts
  src/app/shared/object-collection/shared/mydspace-item-status/my-dspace-item-status.component.ts
  src/styles/_global-styles.scss
  src/themes/dspace/app/navbar/navbar.component.scss
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
  src/themes/dspace/styles/_theme_sass_variable_overrides.scss
Labels: bug, themes, 1 APPROVAL

#2031 Fix Klaro i18n messages
  src/app/shared/cookies/browser-klaro.service.ts
Labels: bug, i18n / l10n, high priority, 1 APPROVAL

#1967 Add captioning support for video/audio files
  src/app/core/shared/media-viewer-item.model.ts
  src/app/item-page/media-viewer/media-viewer-video/caption-info.ts
  src/app/item-page/media-viewer/media-viewer-video/language-helper.ts
  src/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.html
  src/app/item-page/media-viewer/media-viewer-video/media-viewer-video.component.ts
  src/app/item-page/media-viewer/media-viewer.component.ts
Labels: improvement, 1 APPROVAL, component: viewer

#2029 Fix breadcrumb css issue
  src/app/breadcrumbs/breadcrumbs.component.scss
Labels: 1 APPROVAL

#2038 Add DataCite to i18n list of sources
  src/assets/i18n/en.json5
Labels: i18n / l10n, tools:import-sources

#1973 Restored highlighting of title in search results
  src/app/core/breadcrumbs/dso-name.service.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.ts
  src/app/shared/mocks/dso-name.service.mock.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.ts
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.spec.ts
  src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts
Labels: bug, component: Discovery, 1 APPROVAL

#1949 Login menu refactoring
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.html
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.scss
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.spec.ts
  src/app/shared/log-in/methods/log-in-external-provider/log-in-external-provider.component.ts
  src/app/shared/log-in/methods/oidc/log-in-oidc.component.html
  src/app/shared/log-in/methods/oidc/log-in-oidc.component.spec.ts
  src/app/shared/log-in/methods/oidc/log-in-oidc.component.ts
  src/app/shared/log-in/methods/orcid/log-in-orcid.component.html
  src/app/shared/log-in/methods/orcid/log-in-orcid.component.ts
  src/app/shared/log-in/methods/shibboleth/log-in-shibboleth.component.html
  src/app/shared/log-in/methods/shibboleth/log-in-shibboleth.component.spec.ts
  src/app/shared/log-in/methods/shibboleth/log-in-shibboleth.component.ts
  src/app/shared/shared.module.ts
Labels: improvement, authentication: general, 1 APPROVAL

#2045 Add a yarn clean script for the .angular/cache folder
  package.json
Labels: 1 APPROVAL

#1988 Issue 815 controlled vocabulary hierarchical facets 7.4
  config/config.example.yml
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.spec.ts
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/assets/i18n/en.json5
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/filter-vocabulary-config.ts
  src/environments/environment.test.ts
  src/modules/app/browser-app.module.ts
Labels: component: Discovery, component: controlled vocabulary, 1 APPROVAL

#2013 Group description edit
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
Labels: bug, 1 APPROVAL

#2040 Fix duplicate GA page_view events
  src/app/statistics/angulartics/dspace-provider.spec.ts
  src/app/statistics/angulartics/dspace-provider.ts
  src/app/statistics/angulartics/dspace/view-tracker.component.ts
  src/app/statistics/google-analytics.service.spec.ts
  src/app/statistics/google-analytics.service.ts
  src/modules/app/server-app.module.ts
Labels: bug, component: statistics, high priority, 1 APPROVAL, claimed: Atmire

#2032 Ignore IP authentication method in login component.
  src/app/shared/log-in/log-in.component.html
  src/app/shared/log-in/log-in.component.ts
Labels: bug, authentication: general, 1 APPROVAL

#1995 Back to results button in item view
  src/app/browse-by/browse-by-page.module.ts
  src/app/browse-by/browse-by.module.ts
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.scss
  src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.spec.ts
  src/app/entity-groups/journal-entities/journal-entities.module.ts
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
  src/app/entity-groups/research-entities/research-entities.module.ts
  src/app/item-page/item-page.module.ts
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/publication/publication.component.scss
  src/app/item-page/simple/item-types/publication/publication.component.spec.ts
  src/app/item-page/simple/item-types/shared/item.component.spec.ts
  src/app/item-page/simple/item-types/shared/item.component.ts
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.scss
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.spec.ts
  src/app/item-page/simple/item-types/versioned-item/versioned-item.component.ts
  src/app/shared/browse-by/browse-by.component.html
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/browse-by/browse-by.component.ts
  src/app/shared/browse-by/shared-browse-by.module.ts
  src/app/shared/results-back-button/results-back-button.component.html
  src/app/shared/results-back-button/results-back-button.component.scss
  src/app/shared/results-back-button/results-back-button.component.spec.ts
  src/app/shared/results-back-button/results-back-button.component.ts
  src/app/shared/results-back-button/results-back-button.module.ts
  src/app/shared/results-back-button/themed-results-back-button.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
  src/themes/custom/app/shared/results-back-button/results-back-button.component.html
  src/themes/custom/app/shared/results-back-button/results-back-button.component.scss
  src/themes/custom/app/shared/results-back-button/results-back-button.component.ts
  src/themes/custom/eager-theme.module.ts
  src/themes/custom/lazy-theme.module.ts
  src/themes/dspace/eager-theme.module.ts
  src/themes/dspace/lazy-theme.module.ts
Labels: improvement, new feature

#2037 Add support for fully qualified sitemap urls
  package.json
  server.ts
  src/robots.txt.ejs
  webpack/webpack.common.ts
  yarn.lock
Labels: bug, component: SEO, high priority, 1 APPROVAL, e/4, claimed: Atmire

#2060 adding space in es.json5 for pagination.showing.label
  src/assets/i18n/es.json5
Labels: i18n / l10n, 1 APPROVAL

#2049 CST-8165 show logo when browsing collections
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.spec.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
Labels: bug, 1 APPROVAL, component: Community, component: Collection

#2065 Only check 1 page of bitstreams when generating the citation_pdf_url tag
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
Labels: bug, high priority, 1 APPROVAL, claimed: Atmire
