Repository DSpace/dspace-angular, pull requests merged in 2023-08, with the labels that each got.

#2381 refactor: rename aletr-type.ts to alert-type.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/collection-page/edit-item-template-page/edit-item-template-page.component.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.ts
  src/app/health-page/health-panel/health-component/health-component.component.ts
  src/app/item-page/alerts/item-alerts.component.ts
  src/app/item-page/edit-item-page/item-version-history/item-version-history.component.ts
  src/app/item-page/orcid-page/orcid-queue/orcid-queue.component.ts
  src/app/item-page/versions/item-versions.component.ts
  src/app/item-page/versions/notice/item-versions-notice.component.ts
  src/app/process-page/detail/process-detail.component.ts
  src/app/register-email-form/register-email-form.component.ts
  src/app/shared/access-control-form-container/access-control-form-container.component.ts
  src/app/shared/alert/alert-type.ts
  src/app/shared/alert/alert.component.spec.ts
  src/app/shared/alert/alert.component.ts
  src/app/shared/error/error.component.ts
  src/app/submission/sections/container/section-container.component.ts
  src/app/submission/sections/identifiers/section-identifiers.component.ts
  src/app/submission/sections/sherpa-policies/publisher-policy/publisher-policy.component.ts
  src/app/submission/sections/sherpa-policies/section-sherpa-policies.component.ts
  src/app/submission/sections/upload/section-upload.component.ts
Labels: bug, code task, 1 APPROVAL, port to dspace-7_x

#2347 src/assets/i18n: update Finnish language strings
  src/assets/i18n/fi.json5
Labels: i18n / l10n, 1 APPROVAL, port to main

#2344 Catch and handle unsuccessful "convert rels to items" responses
  src/app/item-page/simple/item-types/shared/item-relationships-utils.ts
Labels: bug, quick win, error handling, 1 APPROVAL, port to dspace-7_x

#2397 Fixed MathJax code being displayed twice by `dsMarkdown` pipe
  src/app/shared/utils/markdown.pipe.ts
Labels: bug, usability, medium priority, ux

#2392 [Port dspace-7_x] Fixed MathJax code being displayed twice by `dsMarkdown` pipe
  src/app/shared/utils/markdown.pipe.ts
Labels: bug, usability, 1 APPROVAL, medium priority, ux

#2378 Show error message from the password validation response
  src/app/profile-page/profile-page.component.ts
Labels: bug, authentication: password, 1 APPROVAL, port to dspace-7_x

#2388 fix(i18n): add and update missing status strings
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: i18n / l10n, component: MyDSpace, 1 APPROVAL, port to dspace-7_x

#2420 [Port dspace-7_x] fix(i18n): add and update missing status strings
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: i18n / l10n, component: MyDSpace, 1 APPROVAL

#2350 Fix minor collection form bugs
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/group-registry/group-form/group-form.component.html
  src/app/collection-page/collection-form/collection-form.component.ts
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.html
Labels: bug, usability, component: configurable entities, high priority, component: Collection, claimed: Atmire

#2405 [Port dspace-7_x] Fix minor collection form bugs
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/group-registry/group-form/group-form.component.html
  src/app/collection-page/collection-form/collection-form.component.ts
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.html
Labels: bug, usability, component: configurable entities, high priority, component: Collection, claimed: Atmire

#2424 Enable early release of backport-action to test korthout/backport-action#372
  .github/workflows/port_merged_pull_request.yml
Labels: code task, 1 APPROVAL

#2426 Revert "Enable early release of backport-action to test korthout/backport-action#372"
  .github/workflows/port_merged_pull_request.yml
Labels: bug, code task

#2427 [Port dspace-7_x] ProcessDetailComponent test improvement
  src/app/process-page/detail/process-detail.component.spec.ts
Labels: bug, 1 APPROVAL, testing framework

#2452 Replace mentions of demo7.dspace.org and api7.dspace.org with new demo URLs
  README.md
  config/config.example.yml
  config/config.yml
  docker/README.md
  docker/docker-compose-dist.yml
  docs/Configuration.md
  src/app/core/services/browser-hard-redirect.service.ts
  src/app/core/services/hard-redirect.service.ts
  src/app/core/services/server-hard-redirect.service.ts
Labels: code task, 1 APPROVAL

#2438 2437 Correct and clarify commented-out code in several custom components
  src/themes/custom/app/footer/footer.component.ts
  src/themes/custom/app/header-nav-wrapper/header-navbar-wrapper.component.ts
  src/themes/custom/app/shared/auth-nav-menu/auth-nav-menu.component.ts
  src/themes/custom/app/shared/object-list/object-list.component.ts
  src/themes/custom/app/workflowitems-edit-page/workflow-item-send-back/workflow-item-send-back.component.ts
Labels: bug, code task, themes, 1 APPROVAL, port to dspace-7_x

#2456 [GitHub Actions] When porting a PR, skip any merge commits
  .github/workflows/port_merged_pull_request.yml
Labels: code task

#2453 [Port dspace-7_x] Replace mentions of demo7.dspace.org and api7.dspace.org with new demo URLs
  README.md
  config/config.example.yml
  config/config.yml
  docker/README.md
  docker/docker-compose-dist.yml
  docs/Configuration.md
  src/app/core/services/browser-hard-redirect.service.ts
  src/app/core/services/hard-redirect.service.ts
  src/app/core/services/server-hard-redirect.service.ts
Labels: code task, 1 APPROVAL

#2449 Update pl.json5
  src/assets/i18n/pl.json5
Labels: i18n / l10n, port to dspace-7_x

#2434 Input type list doesn't work correctly if multiple value-pairs have the same pair value
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.ts
Labels: bug, component: submission, quick win, 1 APPROVAL, claimed: Atmire, port to dspace-7_x

#2395 Fix themed components duplicating themself when switching themes
  src/app/shared/theme-support/theme.service.ts
  src/app/shared/theme-support/themed.component.ts
  src/config/config.util.ts
Labels: bug, high priority, themes, claimed: Atmire, port to dspace-7_x

#2462 [Port dspace-7_x] Fix themed components duplicating themself when switching themes
  src/app/shared/theme-support/theme.service.ts
  src/app/shared/theme-support/themed.component.ts
  src/config/config.util.ts
Labels: bug, high priority, themes, 1 APPROVAL

#2463 Fix to Pagination position is retained between searches #2159
  src/app/shared/search-form/search-form.component.spec.ts
  src/app/shared/search-form/search-form.component.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2447 2251 accessibility issues on the community list page
  src/app/community-list-page/community-list-page.component.html
  src/app/community-list-page/community-list-service.ts
  src/app/community-list-page/community-list/community-list.component.html
  src/app/community-list-page/community-list/community-list.component.ts
  src/app/community-list-page/show-more-flat-node.model.ts
Labels: bug, accessibility, 1 APPROVAL, component: Community, port to dspace-7_x

#2399 fix(i18n): curation-task.task.registerdoi.label
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/vi.json5
Labels: bug, i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2468 Minor Accessibility Fixes & Enable accessibility scan on more pages
  cypress/e2e/community-list.cy.ts
  cypress/e2e/header.cy.ts
  cypress/e2e/item-page.cy.ts
  cypress/e2e/login-modal.cy.ts
  cypress/e2e/my-dspace.cy.ts
  cypress/e2e/pagenotfound.cy.ts
  cypress/e2e/search-page.cy.ts
  package.json
  src/app/item-page/simple/field-components/specific-field/title/item-page-title-field.component.html
  src/app/shared/metadata-field-wrapper/metadata-field-wrapper.component.html
  src/app/shared/metadata-field-wrapper/metadata-field-wrapper.component.scss
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/shared/sidebar/sidebar-dropdown.component.html
  src/styles/_vendor.scss
  src/themes/dspace/styles/_global-styles.scss
  yarn.lock
Labels: bug, accessibility, 1 APPROVAL, testing framework, port to dspace-7_x
