Repository DSpace/dspace-angular, pull requests merged in 2024-12, with the labels that each got.

#3182 [Port dspace-7_x] Orcid Authorization / Synchronization Page Fixes
  src/app/item-page/orcid-page/orcid-auth/orcid-auth.component.ts
  src/app/item-page/orcid-page/orcid-page.component.ts
  src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.spec.ts
  src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.ts
Labels: bug, high priority, authentication: general, 1 APPROVAL, integration: ORCID

#3693 Removed unauthorized metadata-export-search request on search page
  src/app/shared/search/search-export-csv/search-export-csv.component.spec.ts
  src/app/shared/search/search-export-csv/search-export-csv.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
Labels: bug, component: Discovery, claimed: Atmire, port to dspace-7_x, port to dspace-8_x

#3711 [Port dspace-8_x] Removed unauthorized metadata-export-search request on search page
  src/app/shared/search/search-export-csv/search-export-csv.component.spec.ts
  src/app/shared/search/search-export-csv/search-export-csv.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
Labels: bug, component: Discovery, 1 APPROVAL

#3677 Fix infinite loading on item pages and optimize menu resolver usage
  cypress/e2e/item-edit.cy.ts
  src/app/browse-by/browse-by-page-routes.ts
  src/app/collection-page/collection-page-routes.ts
  src/app/community-page/community-page-routes.ts
  src/app/core/data/base/base-data.service.spec.ts
  src/app/core/data/base/base-data.service.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/item-page-routes.ts
  src/app/shared/dso-page/dso-edit-menu-resolver.service.ts
Labels: bug, high priority, performance / caching, error handling, claimed: Atmire, port to dspace-8_x

#3755 [Port dspace-8_x][GitHub Actions][Docker] Update Docker scripts & GitHub Actions to use ghcr.io instead of docker.io
  .github/workflows/build.yml
  .github/workflows/docker.yml
  Dockerfile
  Dockerfile.dist
  docker/cli.yml
  docker/db.entities.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-dist.yml
  docker/docker-compose-rest.yml
  docker/docker-compose.yml
Labels: code task, 1 APPROVAL, backend: Docker

#3720 Embed the community/collection on the edit EPerson page
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.ts
Labels: bug, authorization, performance / caching

#3464 Edit Item, Bitstreams tab: Accessibility improvements
  src/app/core/data/object-updates/object-updates.service.stub.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.scss
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.stub.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.scss
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-drag-handle/item-edit-bitstream-drag-handle.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-drag-handle/item-edit-bitstream-drag-handle.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.ts
  src/app/shared/live-region/live-region.service.stub.ts
  src/app/shared/notifications/models/notification-options.model.ts
  src/app/shared/notifications/notifications-board/notifications-board.component.spec.ts
  src/app/shared/notifications/notifications-board/notifications-board.component.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.spec.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.ts
  src/assets/i18n/en.json5
Labels: bug, accessibility, claimed: Atmire, funded

#3721 [Port dspace-7_x] Removed observable function calls from template (part 1)
  src/app/access-control/epeople-registry/epeople-registry.component.html
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/access-control/group-registry/group-form/group-form.component.html
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.html
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.spec.ts
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.ts
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.html
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.spec.ts
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.ts
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.spec.ts
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.spec.ts
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.html
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/pagination/pagination.component.ts
  src/app/shared/testing/registry.service.stub.ts
Labels: bug, high priority, performance / caching, component: Item, claimed: Atmire

#3466 [Port dspace-7_x] Edit Item, Bitstreams tab: Accessibility improvements
  src/app/core/data/object-updates/object-updates.service.stub.ts
  src/app/item-page/edit-item-page/edit-item-page.module.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.scss
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.stub.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.scss
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-drag-handle/item-edit-bitstream-drag-handle.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-drag-handle/item-edit-bitstream-drag-handle.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.ts
  src/app/shared/live-region/live-region.service.stub.ts
  src/app/shared/notifications/models/notification-options.model.ts
  src/app/shared/notifications/notifications-board/notifications-board.component.spec.ts
  src/app/shared/notifications/notifications-board/notifications-board.component.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.spec.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.ts
  src/assets/i18n/en.json5
Labels: bug, accessibility, high priority, funded

#3716 [Port dspace-7_x] Fix infinite loading on item pages and optimize menu resolver usage
  src/app/collection-page/collection-page-routing.module.ts
  src/app/community-page/community-page-routing.module.ts
  src/app/core/data/base/base-data.service.spec.ts
  src/app/core/data/base/base-data.service.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/item-page-routing.module.ts
Labels: bug, high priority, performance / caching, error handling, claimed: Atmire

#3224 Close user profile menu after menu entry is selected
  src/app/shared/auth-nav-menu/auth-nav-menu.component.html
  src/app/shared/auth-nav-menu/user-menu/themed-user-menu.component.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.html
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.ts
Labels: bug, accessibility, 1 APPROVAL, claimed: 4Science, port to dspace-7_x, port to dspace-8_x, funded

#3276 Fix issue with submission sections visibility
  src/app/core/config/models/config-submission-section.model.ts
  src/app/submission/form/submission-form.component.ts
  src/app/submission/objects/section-visibility.model.ts
  src/app/submission/objects/submission-objects.actions.ts
  src/app/submission/objects/submission-objects.effects.spec.ts
  src/app/submission/objects/submission-objects.effects.ts
  src/app/submission/objects/submission-objects.reducer.spec.ts
  src/app/submission/objects/submission-objects.reducer.ts
  src/app/submission/objects/submission-section-object.model.ts
  src/app/submission/sections/sections.service.spec.ts
  src/app/submission/sections/sections.service.ts
  src/app/submission/submission.service.spec.ts
  src/app/submission/submission.service.ts
Labels: bug, component: submission, port to dspace-7_x, port to dspace-8_x

#3264 More accessible file download link for users who use a screen reader
  src/app/shared/file-download-link/file-download-link.component.html
  src/app/shared/file-download-link/file-download-link.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3762 [Port dspace-8_x] More accessible file download link for users who use a screen reader
  src/app/shared/file-download-link/file-download-link.component.html
  src/app/shared/file-download-link/file-download-link.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, 1 APPROVAL

#3763 [Port dspace-7_x] More accessible file download link for users who use a screen reader
  src/app/shared/file-download-link/file-download-link.component.html
  src/app/shared/file-download-link/file-download-link.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, 1 APPROVAL

#3227 RSS feed from search results (Angular)
  src/app/app-routes.ts
  src/app/shared/rss-feed/rss.component.html
  src/app/shared/rss-feed/rss.component.spec.ts
  src/app/shared/rss-feed/rss.component.ts
Labels: component: Discovery, new feature, integration: syndication feed

#2972 fix: linkName from decorator assign value to the correct property
  src/app/core/cache/builders/link.service.spec.ts
  src/app/core/cache/builders/link.service.ts
  src/app/core/data/base/base-data.service.spec.ts
  src/app/core/data/base/base-data.service.ts
Labels: bug, code task, port to dspace-7_x, port to dspace-8_x

#3367 Accessibility in vocabulary treeview
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
Labels: bug, accessibility, component: controlled vocabulary, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3766 [Port dspace-7_x] fix #3241: Configuring the URI link target
  src/app/item-page/field-components/metadata-values/metadata-values.component.html
  src/app/item-page/field-components/metadata-values/metadata-values.component.spec.ts
  src/app/item-page/field-components/metadata-values/metadata-values.component.ts
Labels: bug, component: Item

#3768 [Port dspace-7_x] Accessibility in vocabulary treeview
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.ts
Labels: bug, accessibility, component: controlled vocabulary, 1 APPROVAL

#3654 #3624 - Fix Multi-Row Drag-and-Drop Issue for Chips in Item Submission Form
  src/app/shared/form/chips/chips.component.html
  src/app/shared/form/chips/chips.component.scss
  src/app/shared/form/chips/chips.component.spec.ts
  src/app/shared/form/chips/chips.component.ts
Labels: bug, component: submission, 1 APPROVAL, port to main, port to dspace-7_x

#3679 #3678, #3217 - Fix ordering and changing values of repeatable inputs in submission form
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.ts
Labels: bug, component: submission, 1 APPROVAL, claimed: 4Science, port to dspace-7_x, port to dspace-8_x

#3714 Updating Hungarian translations for DSpace 8.0
  src/assets/i18n/hu.json5
Labels: i18n / l10n, 1 APPROVAL, port to main
