Repository DSpace/dspace-angular, pull requests merged in 2024-04, with the labels that each got.

#2886 Ensures CSRF token is initialized prior to first modifying (non-`GET`) request
  .github/workflows/build.yml
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-list-element/workflow-item/workflow-item-search-result-admin-workflow-list-element.component.spec.ts
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
  src/app/core/xsrf/browser-xsrf.service.spec.ts
  src/app/core/xsrf/browser-xsrf.service.ts
  src/app/core/xsrf/server-xsrf.service.spec.ts
  src/app/core/xsrf/server-xsrf.service.ts
  src/app/core/xsrf/xsrf.service.spec.ts
  src/app/core/xsrf/xsrf.service.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/login-page/login-page.component.spec.ts
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/relation-group/dynamic-relation-group.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts
  src/app/shared/form/form.component.spec.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.spec.ts
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.spec.ts
  src/app/shared/search/search.component.spec.ts
  src/app/submission/edit/submission-edit.component.spec.ts
  src/app/submission/sections/accesses/section-accesses.component.spec.ts
  src/app/submission/sections/license/section-license.component.spec.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
Labels: bug, high priority, 1 APPROVAL

#2887 Renaming DSpace to DSpace 8
  src/app/home-page/home-news/home-news.component.html
  src/themes/dspace/app/home-page/home-news/home-news.component.html
Labels: 1 APPROVAL

#2893 [Port dspace-7_x] Bump express from 4.18.2 to 4.19.2
  package.json
  yarn.lock
Labels: dependencies, code task, 1 APPROVAL

#2895 [Port dspace-7_x] Bump webpack-dev-middleware from 5.3.3 to 5.3.4
  yarn.lock
Labels: dependencies, 1 APPROVAL

#2892 [Port dspace-7_x] Bump follow-redirects from 1.15.5 to 1.15.6
  yarn.lock
Labels: bug, dependencies, 1 APPROVAL

#2896 [Port dspace-7_x] Bump axios to 1.6.8
  yarn.lock
Labels: dependencies, 1 APPROVAL

#2067 Add configuration option to disable inlined CSS in SSR HTML
  config/config.example.yml
  server.ts
  src/config/universal-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.ts
Labels: bug, improvement, high priority, performance / caching, port to dspace-7_x

#2910 Update all GitHub Actions & add token for Codecov.io
  .github/workflows/build.yml
  .github/workflows/issue_opened.yml
  .github/workflows/pull_request_opened.yml
Labels: code task, port to dspace-7_x

#2911 [Port dspace-7_x] Update all GitHub Actions & add token for Codecov.io
  .github/workflows/build.yml
  .github/workflows/issue_opened.yml
  .github/workflows/pull_request_opened.yml
Labels: code task, 1 APPROVAL

#2897 Fixes for #2891 #2889
  src/app/core/cache/builders/link.service.spec.ts
  src/app/core/cache/builders/link.service.ts
  src/app/core/data-services-map.ts
  src/app/core/data/request.effects.ts
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
  src/app/core/lazy-data-service.ts
  src/app/core/lazy-service.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.ts
  src/app/shared/eperson-group-list/eperson-group-list.component.spec.ts
  src/app/shared/eperson-group-list/eperson-group-list.component.ts
  src/app/shared/resource-policies/resolvers/resource-policy-target.resolver.ts
  src/config/app-config.interface.ts
Labels: bug, 1 APPROVAL

#2782 Fixed Font Awesome CSS Pseudo-elements not rendering in v6.x
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-suggestions/org-unit-input-suggestions.component.scss
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-suggestions/person-input-suggestions.component.scss
Labels: bug, accessibility, quick win, 1 APPROVAL, port to dspace-7_x

#2905 Fix for submission describe warning contribution bug
  src/app/submission/sections/form/section-form.component.spec.ts
  src/app/submission/sections/form/section-form.component.ts
Labels: bug, component: submission, 1 APPROVAL, port to dspace-7_x

#2926 typo in role name
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html
Labels: bug, 1 APPROVAL

#2844 Fixed home page issues
  config/config.example.yml
  src/app/admin/admin-search-page/admin-search-page.component.html
  src/app/admin/admin-search-page/admin-search-page.component.spec.ts
  src/app/admin/admin-search-page/admin-search-page.component.ts
  src/app/admin/admin-workflow-page/admin-workflow-page.component.html
  src/app/admin/admin-workflow-page/admin-workflow-page.component.spec.ts
  src/app/admin/admin-workflow-page/admin-workflow-page.component.ts
  src/app/app-routing-paths.ts
  src/app/community-list-page/community-list/community-list.component.html
  src/app/core/coar-notify/notify-info/notify-info.component.scss
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/home-page/home-coar/home-coar.component.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.scss
  src/app/home-page/home-page.component.ts
  src/app/info/info-routes.ts
  src/app/info/info-routing-paths.ts
  src/app/info/notify-info/notify-info.component.html
  src/app/info/notify-info/notify-info.component.scss
  src/app/info/notify-info/notify-info.component.spec.ts
  src/app/info/notify-info/notify-info.component.ts
  src/app/item-page/simple/related-entities/related-entities-search/related-entities-search.component.html
  src/app/item-page/simple/related-entities/related-entities-search/related-entities-search.component.spec.ts
  src/app/item-page/simple/related-entities/related-entities-search/related-entities-search.component.ts
  src/app/notifications/suggestions.service.ts
  src/app/search-page/themed-configuration-search-page.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search.component.html
  src/app/shared/sidebar/page-with-sidebar.component.html
  src/app/shared/sidebar/page-with-sidebar.component.ts
  src/assets/i18n/en.json5
  src/config/default-app-config.ts
  src/config/info-config.interface.ts
  src/environments/environment.test.ts
  src/themes/custom/app/home-page/home-page.component.ts
Labels: improvement, 1 APPROVAL

#2931 Add check for registration verification to the register email form.
  src/app/register-email-form/register-email-form.component.html
Labels: bug, high priority, 1 APPROVAL, port to dspace-7_x

#2934 Upgrade to angular 17
  .gitignore
  angular.json
  cypress/tsconfig.json
  package.json
  server.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/forward-client-ip/forward-client-ip.interceptor.spec.ts
  src/app/core/forward-client-ip/forward-client-ip.interceptor.ts
  src/app/core/locale/server-locale.service.ts
  src/app/core/services/cookie.service.spec.ts
  src/app/core/services/cookie.service.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/core/services/server-response.service.ts
  src/app/core/services/server.referrer.service.ts
  src/app/core/shared/operators.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/versions/item-versions-row-element-version/item-versions-row-element-version.component.html
  src/app/item-page/versions/item-versions-row-element-version/item-versions-row-element-version.component.scss
  src/app/item-page/versions/item-versions-row-element-version/item-versions-row-element-version.component.spec.ts
  src/app/item-page/versions/item-versions-row-element-version/item-versions-row-element-version.component.ts
  src/app/item-page/versions/item-versions.component.html
  src/app/item-page/versions/item-versions.component.scss
  src/app/item-page/versions/item-versions.component.spec.ts
  src/app/item-page/versions/item-versions.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/utils/browser-only.directive.ts
  src/config/build-config.interface.ts
  src/config/default-app-config.ts
  src/config/ssr-config.interface.ts
  src/config/store/devtools.ts
  src/config/universal-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/express.tokens.ts
  src/main.server.ts
  src/modules/app/browser-app.config.ts
  src/themes/dspace/app/home-page/home-news/home-news.component.html
  yarn.lock
Labels: dependencies, high priority

#2945 Fixed home page links being unclickable
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.scss
  src/app/home-page/home-page.component.ts
  src/app/shared/search/search.component.html
Labels: bug, testathon

#2768 Fix infinite scroll
  src/app/shared/dso-selector/dso-selector/dso-selector.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
Labels: bug, component: MyDSpace, 1 APPROVAL, port to dspace-7_x

#2816 Return 404 Not Found status code on missing identifiers
  src/app/lookup-by-id/objectnotfound/objectnotfound.component.spec.ts
  src/app/lookup-by-id/objectnotfound/objectnotfound.component.ts
Labels: bug, component: SEO, 1 APPROVAL, port to dspace-7_x

#2965 [Port dspace-7_x] Return 404 Not Found status code on missing identifiers
  src/app/lookup-by-id/objectnotfound/objectnotfound.component.spec.ts
  src/app/lookup-by-id/objectnotfound/objectnotfound.component.ts
Labels: bug, component: SEO, 1 APPROVAL

#2968 [Port dspace-7_x] Fixed pagination issues on item mapper
  src/app/access-control/bulk-access/browse/bulk-access-browse.component.html
  src/app/access-control/epeople-registry/epeople-registry.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/group-registry/group-form/members-list/members-list.component.html
  src/app/access-control/group-registry/group-form/subgroup-list/subgroups-list.component.html
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html
  src/app/collection-page/collection-item-mapper/collection-item-mapper.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/paginated-drag-and-drop-bitstream-list/paginated-drag-and-drop-bitstream-list.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html
  src/app/item-page/full/field-components/file-section/full-file-section.component.html
  src/app/item-page/versions/item-versions.component.html
  src/app/process-page/overview/process-overview.component.html
  src/app/shared/object-detail/object-detail.component.html
  src/app/shared/object-grid/object-grid.component.html
  src/app/shared/object-list/object-list.component.html
  src/app/shared/object-select/collection-select/collection-select.component.html
  src/app/shared/object-select/collection-select/collection-select.component.ts
  src/app/shared/object-select/item-select/item-select.component.html
  src/app/shared/object-select/item-select/item-select.component.spec.ts
  src/app/shared/object-select/item-select/item-select.component.ts
  src/app/shared/object-select/object-select.model.ts
  src/app/shared/object-select/object-select/object-select.component.ts
  src/app/shared/pagination/pagination.component.ts
Labels: bug, component: Discovery, 1 APPROVAL, medium priority, component: Collection, testathon, claimed: Atmire

#2969 [Port dspace-7_x] Added missing/incomplete breadcrumbs on create community/collection/item pages
  src/app/collection-page/collection-page-routing.module.ts
  src/app/community-page/community-page-routing.module.ts
  src/app/core/breadcrumbs/community-breadcrumb.resolver.ts
  src/app/core/breadcrumbs/dso-breadcrumb.resolver.spec.ts
  src/app/core/breadcrumbs/dso-breadcrumb.resolver.ts
  src/app/core/core.module.ts
  src/app/core/submission/resolver/submission-links-to-follow.ts
  src/app/core/submission/resolver/submission-object.resolver.ts
  src/app/core/submission/resolver/submission-parent-breadcrumb.resolver.ts
  src/app/core/submission/submission-parent-breadcrumb.service.ts
  src/app/submission/submission.service.ts
  src/app/workflowitems-edit-page/item-from-workflow-breadcrumb.resolver.ts
  src/app/workflowitems-edit-page/item-from-workflow.resolver.spec.ts
  src/app/workflowitems-edit-page/item-from-workflow.resolver.ts
  src/app/workflowitems-edit-page/workflowitems-edit-page-routing.module.ts
  src/app/workspaceitems-edit-page/item-from-workspace-breadcrumb.resolver.ts
  src/app/workspaceitems-edit-page/item-from-workspace.resolver.spec.ts
  src/app/workspaceitems-edit-page/item-from-workspace.resolver.ts
  src/app/workspaceitems-edit-page/workspaceitems-edit-page-routing.module.ts
  src/assets/i18n/en.json5
Labels: bug, component: Discovery, 1 APPROVAL, medium priority, component: Collection, testathon, claimed: Atmire

#2967 Update REST and CI docker compose scripts to sync with 7.x backend
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
Labels: bug, 1 APPROVAL, backend: Docker

#2966 Update REST and CI docker compose scripts to sync with 8.0 backend
  docker/README.md
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
Labels: bug, 1 APPROVAL, backend: Docker

#2962 Fix submission lost changes after save
  src/app/core/submission/submission-json-patch-operations.service.spec.ts
  src/app/core/submission/submission-json-patch-operations.service.ts
Labels: bug, component: submission, 1 APPROVAL

#2984 Synced the imports of the custom theme with the imports of the base component so custom theme works again
  src/themes/custom/app/browse-by/browse-by-taxonomy/browse-by-taxonomy.component.ts
  src/themes/custom/app/collection-page/collection-page.component.ts
  src/themes/custom/app/collection-page/edit-item-template-page/edit-item-template-page.component.ts
  src/themes/custom/app/community-page/community-page.component.ts
  src/themes/custom/app/community-page/sections/sub-com-col-section/sub-collection-list/community-page-sub-collection-list.component.ts
  src/themes/custom/app/forgot-password/forgot-password-email/forgot-email.component.ts
  src/themes/custom/app/forgot-password/forgot-password-form/forgot-password-form.component.ts
  src/themes/custom/app/header/header.component.ts
  src/themes/custom/app/home-page/home-page.component.ts
  src/themes/custom/app/item-page/simple/item-page.component.ts
  src/themes/custom/app/item-page/simple/item-types/publication/publication.component.ts
  src/themes/custom/app/item-page/simple/item-types/untyped-item/untyped-item.component.ts
  src/themes/custom/app/login-page/login-page.component.ts
  src/themes/custom/app/my-dspace-page/my-dspace-page.component.ts
  src/themes/custom/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
  src/themes/custom/app/profile-page/profile-page.component.ts
  src/themes/custom/app/register-page/register-email/register-email.component.ts
  src/themes/custom/app/shared/browse-by/browse-by.component.ts
  src/themes/custom/app/shared/comcol-page-browse-by/comcol-page-browse-by.component.ts
  src/themes/custom/app/shared/lang-switch/lang-switch.component.ts
  src/themes/custom/app/shared/loading/loading.component.ts
  src/themes/custom/app/shared/object-list/object-list.component.ts
Labels: bug, high priority, themes, 1 APPROVAL

#2985 Fixed the problem that creating template item results in page which never finishes loading
  cypress/e2e/item-template.cy.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.ts
Labels: bug, high priority, component: administrative tools, 1 APPROVAL, component: Collection

#2675 Multiline selected facet badge on search page
  src/app/shared/search/search-labels/search-label/search-label.component.html
  src/app/shared/search/search-labels/search-label/search-label.component.scss
  src/app/shared/search/search-labels/search-label/search-label.component.ts
  src/app/shared/search/search-labels/search-labels.component.scss
  src/app/shared/search/search.component.html
Labels: bug, component: Discovery, 1 APPROVAL, port to dspace-7_x

#2710 Update robots.txt.ejs
  src/robots.txt.ejs
Labels: bug, component: SEO, high priority, performance / caching, 1 APPROVAL, port to dspace-7_x

#2989 [Port to dspace-7_x] Multiline selected facet badge on search page
  src/app/shared/search/search-labels/search-label/search-label.component.html
  src/app/shared/search/search-labels/search-label/search-label.component.scss
  src/app/shared/search/search-labels/search-label/search-label.component.ts
  src/app/shared/search/search-labels/search-labels.component.scss
  src/app/shared/search/search.component.html
Labels: bug, component: Discovery, 1 APPROVAL

#2976 Fix issue with the admin sidebar scrollbar on Firefox/Windows
  src/app/admin/admin-sidebar/admin-sidebar.component.scss
  src/app/root/root.component.html
  src/app/root/root.component.ts
  src/themes/custom/app/root/root.component.ts
Labels: bug, themes, 1 APPROVAL
