Repository DSpace/dspace-angular, pull requests merged in 2024-10, with the labels that each got.

#3375 Always sanitize HTML passed to dsMarkdown even if markdown rendering is disabled
  src/app/shared/utils/markdown.directive.spec.ts
  src/app/shared/utils/markdown.directive.ts
Labels: bug, quick win, 1 APPROVAL, port to dspace-8_x

#3148 Accessibility of the status page
  src/app/item-page/edit-item-page/item-operation/item-operation.component.html
  src/app/item-page/edit-item-page/item-status/item-status.component.html
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3382 [Port dspace-7_x] Accessibility of the status page
  src/app/item-page/edit-item-page/item-operation/item-operation.component.html
  src/app/item-page/edit-item-page/item-status/item-status.component.html
Labels: bug, accessibility, 1 APPROVAL

#3386 Update fr.json5 to add capitalization
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3221 Removed unnecessary *ngVars from ThumbnailComponent
  src/app/thumbnail/thumbnail.component.html
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
Labels: bug, 1 APPROVAL, component: Item, claimed: Atmire, port to dspace-7_x, affects: 8.x, affects: 7.x, port to dspace-8_x

#3392 [Port dspace-8_x] Removed unnecessary *ngVars from ThumbnailComponent
  src/app/thumbnail/thumbnail.component.html
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
Labels: bug, 1 APPROVAL, component: Item, claimed: Atmire, affects: 8.x, affects: 7.x

#3396 [Port dspace-8_x] Bump rollup from 4.21.2 to 4.24.0
  yarn.lock
Labels: dependencies

#3315 Upgrade to Cypress 13.15.0
  cypress.config.ts
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/login-modal.cy.ts
  cypress/support/commands.ts
  package-lock.json
  package.json
Labels: dependencies, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3397 [Port dspace-8_x] Upgrade to Cypress 13.15.0
  cypress.config.ts
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/login-modal.cy.ts
  cypress/support/commands.ts
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL, testing framework, port to dspace-7_x

#3400 Fixed #3399 - minor typo
  src/app/home-page/top-level-community-list/top-level-community-list.component.html
Labels: bug, i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3402 [Port dspace-7_x] Fixed #3399 - minor typo
  src/app/home-page/top-level-community-list/top-level-community-list.component.html
Labels: bug, i18n / l10n, 1 APPROVAL

#3403 [Port dspace-8_x] Bump send, express, browser-sync and serve-static
  package.json
  yarn.lock
Labels: dependencies

#3404 [Port dspace-7_x] Bump send, express and serve-static
  package.json
  yarn.lock
Labels: dependencies

#3368 [Port dspace-7_x] Fixed Edit Item's Version History crashing
  src/app/item-page/versions/item-versions.component.html
  src/app/item-page/versions/item-versions.component.ts
Labels: bug, component: versioning, performance / caching, claimed: Atmire

#3409 [Port dspace-7_x] Bump cookie, cookie-parser and socket.io
  package.json
  yarn.lock
Labels: dependencies

#3405 [Port dspace-7_x] Implement e2e accessibility tests for pages in DSpace User Interface
  cypress.config.ts
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-curation-tasks.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
  cypress/e2e/admin-search-page.cy.ts
  cypress/e2e/admin-workflow-page.cy.ts
  cypress/e2e/batch-import-page.cy.ts
  cypress/e2e/bitstreams-format.cy.ts
  cypress/e2e/bulk-access.cy.ts
  cypress/e2e/collection-page.cy.ts
  cypress/e2e/community-statistics.cy.ts
  cypress/e2e/create-eperson.cy.ts
  cypress/e2e/create-group.cy.ts
  cypress/e2e/edit-eperson.cy.ts
  cypress/e2e/edit-group.cy.ts
  cypress/e2e/end-user-agreement.cy.ts
  cypress/e2e/epeople-registry.cy.ts
  cypress/e2e/feedback.cy.ts
  cypress/e2e/groups-registry.cy.ts
  cypress/e2e/health-page.cy.ts
  cypress/e2e/homepage-statistics.cy.ts
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/item-page.cy.ts
  cypress/e2e/item-statistics.cy.ts
  cypress/e2e/metadata-import-page.cy.ts
  cypress/e2e/metadata-registry.cy.ts
  cypress/e2e/metadata-schema.cy.ts
  cypress/e2e/new-process.cy.ts
  cypress/e2e/privacy.cy.ts
  cypress/e2e/processes-overview.cy.ts
  cypress/e2e/profile-page.cy.ts
  cypress/e2e/system-wide-alert.cy.ts
  src/app/header/context-help-toggle/context-help-toggle.component.html
  src/app/health-page/health-page.component.html
  src/app/info/end-user-agreement/end-user-agreement-content/end-user-agreement-content.component.html
  src/app/info/privacy/privacy-content/privacy-content.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.html
  src/app/shared/menu/menu-item/onclick-menu-item.component.html
  src/app/shared/pagination/pagination.component.html
  src/assets/i18n/en.json5
  src/styles/_global-styles.scss
Labels: bug, accessibility, high priority, claimed: 4Science, funded

#3412 [Port dspace-8_x] Fixed Edit Item's Version History crashing
  src/app/item-page/versions/item-versions.component.html
  src/app/item-page/versions/item-versions.component.ts
Labels: bug, component: versioning, performance / caching, claimed: Atmire

#3411 Fix browse by date's year dropdown being empty on DSpace 7.6.2+
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/browse-by/browse-by.component.ts
Labels: bug, component: Discovery, high priority, claimed: Atmire, affects: 7.x

#3417 [dspace-8_x] Bump body-parser from 1.20.2 to 1.20.3
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3144 Update Arabic Translation
  src/assets/i18n/ar.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3176 Add German translations (metadata import)
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3420 Configure Dependabot to also attempt minor/patch updates for dependencies
  .github/dependabot.yml
Labels: dependencies, 1 APPROVAL

#3457 Bump all `@typescript-eslint/*` dependencies to 7.18.0
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies, 1 APPROVAL

#3460 [dspace-7_x] Fix Collection Page e2e test. Wait on Recent Submissions
  cypress/e2e/collection-page.cy.ts
Labels: 1 APPROVAL, testing framework

#3461 Add basic e2e testing for i18n
  cypress/e2e/header.cy.ts
  src/app/shared/lang-switch/lang-switch.component.html
Labels: i18n / l10n, 1 APPROVAL, testing framework, port to dspace-7_x, port to dspace-8_x

#3468 [Port dspace-7_x] Add basic e2e testing for i18n
  cypress/e2e/header.cy.ts
  src/app/shared/lang-switch/lang-switch.component.html
Labels: i18n / l10n, 1 APPROVAL, testing framework

#3471 [dspace-7_x] Fix flakey Item page accessibility tests by waiting for pages to fuly load
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/item-page.cy.ts
Labels: accessibility, 1 APPROVAL, testing framework

#3482 Update dependabot.yml with new PR groups for eslint, testing dependencies, postcss, sass, webpack
  .github/dependabot.yml
Labels: code task, 1 APPROVAL

#3209 Update pt-PT.json5
  src/assets/i18n/pt-PT.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3509 Remove unused dependencies (sortablejs, sanitize-html, webfontloader)
  angular.json
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3511 [Port main] Remove unused dependencies (sortablejs, sanitize-html, webfontloader)
  angular.json
  package-lock.json
  package.json
Labels: dependencies, 1 APPROVAL

#3481 Fix code scanning alert no. 6: Incomplete string escaping or encoding
  src/app/core/shared/metadata.utils.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3544 Remove unused `@types/sanitize-html` dependency
  package-lock.json
  package.json
Labels: dependencies

#3549 [Port dspace-7_x] Remove unused PostCSS plugins
  package.json
  postcss.config.js
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3552 [Port dspace-7_x] Bump http-proxy-middleware from 1.0.5 to 2.0.7
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3524 Aligning the browse button
  src/app/shared/upload/uploader/uploader.component.html
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3547 Remove unused PostCSS plugins
  package-lock.json
  package.json
  postcss.config.js
Labels: dependencies, 1 APPROVAL, port to dspace-8_x

#3550 Bump http-proxy-middleware from 1.0.5 to 2.0.7
  package-lock.json
  package.json
Labels: dependencies, 1 APPROVAL, port to dspace-8_x

#3548 [Port dspace-8_x] Remove unused PostCSS plugins
  package.json
  postcss.config.js
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3551 [Port dspace-8_x] Bump http-proxy-middleware from 1.0.5 to 2.0.7
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3573 [Port dspace-8_x] Remove unused dependencies (& additional Mirador dependency cleanup)
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL, integration: IIIF

#3574 [Port dspace-7_x] Remove unused dependencies (& additional Mirador dependency cleanup)
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL, integration: IIIF

#3580 Bump tough-cookie from 4.1.2 to 4.1.4
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3579 Bump dompurify from 2.4.5 to 2.5.7
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3378 Changing the bitstream title in the submission form to use the view c…
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/app/submission/sections/upload/file/view/section-upload-file-view.component.html
  src/app/submission/sections/upload/file/view/section-upload-file-view.component.ts
Labels: bug, component: submission, 1 APPROVAL, port to dspace-8_x

#3587 Update fr.json5
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3415 Added support for caching embedded objects without a self link & null responses
  src/app/core/breadcrumbs/item-breadcrumb.resolver.ts
  src/app/core/browse/browse.service.spec.ts
  src/app/core/browse/browse.service.ts
  src/app/core/cache/object-cache.reducer.ts
  src/app/core/cache/object-cache.service.ts
  src/app/core/data/dspace-rest-response-parsing.service.ts
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/core/data/version-history-data.service.ts
  src/app/core/index/index.effects.ts
  src/app/home-page/recent-item-list/recent-item-list.component.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-delete/item-delete.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/item-page.resolver.ts
  src/app/item-page/item.resolver.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/utils/relation-query.utils.ts
Labels: bug, component: Discovery, high priority, performance / caching, claimed: Atmire, port to dspace-7_x, port to dspace-8_x
