Repository DSpace/dspace-angular, pull requests merged in 2024-07, with the labels that each got.

#3063 [Port dspace-7_x] Ensures CSRF token is initialized prior to first modifying (non-GET) request
  .github/workflows/build.yml
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-list-element/workflow-item/workflow-item-search-result-admin-workflow-list-element.component.spec.ts
  src/app/core/data/request.effects.ts
  src/app/core/data/request.service.spec.ts
  src/app/core/data/request.service.ts
  src/app/core/xsrf/browser-xsrf.service.spec.ts
  src/app/core/xsrf/browser-xsrf.service.ts
  src/app/core/xsrf/server-xsrf.service.spec.ts
  src/app/core/xsrf/server-xsrf.service.ts
  src/app/core/xsrf/xsrf.service.spec.ts
  src/app/core/xsrf/xsrf.service.ts
  src/app/entity-groups/research-entities/submission/item-list-elements/person/person-search-result-list-submission-element.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/login-page/login-page.component.spec.ts
  src/app/shared/auth-nav-menu/auth-nav-menu.component.spec.ts
  src/app/shared/auth-nav-menu/user-menu/user-menu.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/relation-group/dynamic-relation-group.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts
  src/app/shared/form/form.component.spec.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/item-detail-preview/item-detail-preview.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/collection-search-result/collection-search-result-grid-element.component.spec.ts
  src/app/shared/object-grid/search-result-grid-element/community-search-result/community-search-result-grid-element.component.spec.ts
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.spec.ts
  src/app/shared/search/search.component.spec.ts
  src/app/submission/edit/submission-edit.component.spec.ts
  src/app/submission/sections/accesses/section-accesses.component.spec.ts
  src/app/submission/sections/license/section-license.component.spec.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts
  src/modules/app/browser-app.module.ts
  src/modules/app/server-app.module.ts
Labels: bug, component: statistics, high priority, 1 APPROVAL

#3152 Forward client's user-agent instead of Node's
  src/app/core/forward-client-ip/forward-client-ip.interceptor.ts
Labels: bug, 1 APPROVAL, port to main, port to dspace-8_x

#3158 Docker compose syntax changes
  docker/README.md
  docker/docker-compose-rest.yml
Labels: code task, 1 APPROVAL, backend: Docker, port to dspace-7_x, port to dspace-8_x

#3155 Accessibility on the Edit metadata tab
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.html
Labels: bug, accessibility, 1 APPROVAL, component: Item, port to dspace-7_x, port to dspace-8_x

#3147 [Port dspace-7_x] Fixed bug when declining Google ReCaptcha cookie preferences
  src/app/shared/cookies/klaro-configuration.ts
Labels: bug, 1 APPROVAL

#3146 Fixed bug when declining Google ReCaptcha cookie preferences
  src/app/shared/cookies/klaro-configuration.ts
Labels: bug, 1 APPROVAL, port to dspace-8_x

#3179 [Port dspace-8_x] Fixed bug when declining Google ReCaptcha cookie preferences
  src/app/shared/cookies/klaro-configuration.ts
Labels: bug, 1 APPROVAL

#3166 fixes image path for dspace-postgres-pgcrypto
  docker/db.entities.yml
Labels: bug, 1 APPROVAL, backend: Docker, port to dspace-8_x

#3172 Minor fix in french translation file
  .github/pull_request_template.md
  src/assets/i18n/fr.json5
Labels: bug, i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3188 [Port dspace-8_x] Minor fix in french translation file
  src/assets/i18n/fr.json5
Labels: bug, i18n / l10n, 1 APPROVAL

#3187 [Port dspace-7_x] Minor fix in french translation file
  src/assets/i18n/fr.json5
Labels: bug, i18n / l10n, 1 APPROVAL

#3186 Docker build: fix FromAsCasing warning
  Dockerfile.dist
Labels: bug, 1 APPROVAL, backend: Docker, port to dspace-7_x, port to dspace-8_x

#3112 [#3111] fix markdown rendering applying before mathjax rendering
  src/app/core/shared/client-math.service.ts
  src/app/core/shared/math.service.spec.ts
  src/app/core/shared/math.service.ts
  src/app/core/shared/server-math.service.ts
  src/app/shared/utils/markdown.directive.ts
Labels: bug, 1 APPROVAL, component: Item, port to dspace-7_x, port to dspace-8_x
