Repository DSpace/dspace-angular, pull requests merged in 2024-01, with the labels that each got.

#2670 Ensure HALEndpointService doesn't use stale responses
  src/app/core/data/base/base-data.service.spec.ts
  src/app/core/data/base/base-data.service.ts
  src/app/core/data/request-entry-state.model.spec.ts
  src/app/core/data/request-entry-state.model.ts
  src/app/core/data/request.reducer.spec.ts
  src/app/core/data/request.reducer.ts
  src/app/core/data/request.service.ts
  src/app/core/server-check/server-check.guard.spec.ts
  src/app/core/server-check/server-check.guard.ts
  src/app/core/shared/hal-endpoint.service.spec.ts
  src/app/core/shared/hal-endpoint.service.ts
Labels: bug, high priority, authentication: Shibboleth, performance / caching, port to main

#2662 Fixed ePerson link on edit group page
  src/app/access-control/group-registry/group-form/members-list/members-list.component.html
  src/app/access-control/group-registry/group-form/members-list/members-list.component.spec.ts
  src/app/access-control/group-registry/group-form/members-list/members-list.component.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.spec.ts
Labels: bug, authorization, 1 APPROVAL, claimed: Atmire, port to dspace-7_x

#2587 Deque Analysis Color Contrast fixes
  src/app/shared/alert/alert.component.scss
  src/app/shared/notifications/notification/notification.component.scss
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss
  src/styles/_bootstrap_variables.scss
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
  src/themes/dspace/styles/_theme_sass_variable_overrides.scss
Labels: accessibility, 1 APPROVAL, port to dspace-7_x

#2743 [Port to dspace-7_x] Deque Analysis Color Contrast fixes #2587
  src/app/shared/alert/alert.component.scss
  src/app/shared/notifications/notification/notification.component.scss
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.scss
  src/styles/_bootstrap_variables.scss
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
  src/themes/dspace/styles/_theme_sass_variable_overrides.scss
Labels: accessibility, 1 APPROVAL

#2711 Add more automated accessibility scanning to e2e tests & fix a few minor accessibility bugs
  cypress.config.ts
  cypress/e2e/admin-sidebar.cy.ts
  cypress/e2e/breadcrumbs.cy.ts
  cypress/e2e/collection-edit.cy.ts
  cypress/e2e/collection-page.cy.ts
  cypress/e2e/collection-statistics.cy.ts
  cypress/e2e/community-edit.cy.ts
  cypress/e2e/community-page.cy.ts
  cypress/e2e/community-statistics.cy.ts
  cypress/e2e/homepage-statistics.cy.ts
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/item-page.cy.ts
  cypress/e2e/item-statistics.cy.ts
  cypress/e2e/login-modal.cy.ts
  cypress/e2e/my-dspace.cy.ts
  cypress/e2e/search-navbar.cy.ts
  cypress/e2e/search-page.cy.ts
  cypress/e2e/submission.cy.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  src/app/collection-page/collection-item-mapper/collection-item-mapper.component.html
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.html
  src/app/collection-page/edit-collection-page/collection-source/collection-source.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.spec.ts
  src/app/item-page/edit-item-page/edit-item-page.component.html
  src/app/item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.html
  src/app/shared/comcol/comcol-forms/edit-comcol-page/edit-comcol-page.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/number-picker/number-picker.component.html
  src/app/shared/form/number-picker/number-picker.component.spec.ts
  src/app/shared/form/number-picker/number-picker.component.ts
  src/assets/i18n/en.json5
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x

#2721 Fix whitespace in links due to newlines
  src/app/community-list-page/community-list/community-list.component.html
  src/app/item-page/field-components/metadata-values/metadata-values.component.html
Labels: bug, design, 1 APPROVAL, low priority, port to dspace-7_x

#2338 Made ConfirmationModalComponent more generic
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/admin/admin-workflow-page/admin-workflow-search-results/actions/workspace-item/workspace-item-admin-workflow-actions.component.ts
  src/app/shared/confirmation-modal/confirmation-modal.component.html
  src/app/shared/confirmation-modal/confirmation-modal.component.ts
  src/app/shared/dso-selector/modal-wrappers/export-batch-selector/export-batch-selector.component.ts
  src/app/shared/dso-selector/modal-wrappers/export-metadata-selector/export-metadata-selector.component.ts
  src/app/shared/subscriptions/subscription-view/subscription-view.component.ts
Labels: improvement, code task, 1 APPROVAL

#2764 [Port dspace-7_x] Use keyboard to select values
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
Labels: bug, accessibility, component: submission, 1 APPROVAL

#2769 fixed typo in info.feedback.page_help
  src/assets/i18n/en.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2755 Add logo max constraints
  src/app/shared/comcol/comcol-page-logo/comcol-page-logo.component.html
  src/app/shared/comcol/comcol-page-logo/comcol-page-logo.component.scss
  src/styles/_custom_variables.scss
Labels: bug, themes, 1 APPROVAL, component: Community, component: Collection, port to dspace-7_x
