Repository DSpace/dspace-angular, pull requests merged in 2024-06, with the labels that each got.

#3074 Fix advanced workflows throwing 404
  src/app/access-control/group-registry/group-form/members-list/members-list.component.html
  src/app/access-control/group-registry/group-form/members-list/members-list.component.spec.ts
  src/app/access-control/group-registry/group-form/members-list/members-list.component.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/item-page/edit-item-page/modify-item-overview/modify-item-overview.component.spec.ts
  src/app/item-page/edit-item-page/modify-item-overview/modify-item-overview.component.ts
  src/app/shared/mydspace-actions/claimed-task/abstract/claimed-task-actions-abstract.component.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.ts
  src/app/shared/mydspace-actions/claimed-task/decline-task/claimed-task-actions-decline-task.component.ts
  src/app/shared/mydspace-actions/claimed-task/edit-metadata/claimed-task-actions-edit-metadata.component.ts
  src/app/shared/mydspace-actions/claimed-task/rating/advanced-claimed-task-action-rating.component.ts
  src/app/shared/mydspace-actions/claimed-task/reject/claimed-task-actions-reject.component.ts
  src/app/shared/mydspace-actions/claimed-task/return-to-pool/claimed-task-actions-return-to-pool.component.ts
  src/app/shared/mydspace-actions/claimed-task/select-reviewer/advanced-claimed-task-action-select-reviewer.component.ts
  src/app/shared/mydspace-actions/claimed-task/switcher/claimed-task-actions-decorator.ts
  src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.spec.ts
  src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-action-select-reviewer/reviewers-list/reviewers-list.component.ts
  src/app/workflowitems-edit-page/workflow-item-action-page.component.ts
Labels: bug, component: workflow, testathon, claimed: Atmire

#2929 Fixed edit item relationships tab not displaying tilted relationships
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
Labels: bug, component: configurable entities, 1 APPROVAL, claimed: Atmire, port to dspace-7_x

#2853 Avoid metadata representation element is rendered twice when checking the browse configuration
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/app/item-page/simple/metadata-representation-list/metadata-representation-list.component.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#3102 [Port dspace-7_x] Avoid metadata representation element is rendered twice when checking the browse configuration
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/app/item-page/simple/metadata-representation-list/metadata-representation-list.component.ts
Labels: bug, 1 APPROVAL, component: Item

#3092 Update ar.json5
  src/assets/i18n/ar.json5
Labels: i18n / l10n, 1 APPROVAL

#3098 Fixed item edit relationships with same type name but different entities all being shown under same label
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
Labels: bug, component: configurable entities, high priority, configuration, claimed: Atmire, port to dspace-7_x

#3107 [Port dspace-7_x] Fixed item edit relationships with same type name but different entities all being shown under same label
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
Labels: bug, component: configurable entities, high priority, configuration

#3106 Fixed caching & same entity type relationship with different left/rightwardtype bugs on edit item relationships
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.scss
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.html
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/item-page/simple/item-types/shared/item-relationships-utils.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/themed-dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
Labels: bug, component: configurable entities

#3109 [Port dspace-7_x] Fixed caching & same entity type relationship with different left/rightwardtype bugs on edit item relationships
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/item-page/edit-item-page/edit-item-page.module.ts
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.scss
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list-wrapper/edit-relationship-list-wrapper.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.html
  src/app/item-page/simple/item-types/shared/item-relationships-utils.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/themed-dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
Labels: bug, component: configurable entities

#3115 Fixes: Site hangs when selecting items via keyboard from the hamburger menu
  src/app/shared/menu/menu-item/link-menu-item.component.html
Labels: bug, accessibility, 1 APPROVAL, testathon, port to dspace-7_x

#3099 Improving accessibility of the ds-loading component
  src/app/shared/loading/loading.component.html
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x

#3067 Fix "Browse by Author" remaining serious accessibility issues
  src/app/shared/starts-with/text/starts-with-text.component.html
  src/app/shared/starts-with/text/starts-with-text.component.scss
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x

#3039 Fix - Change color Contrast in cookie settings box
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
Labels: bug, accessibility, 1 APPROVAL, port to main

#3120 [Port main] Fix - Change color Contrast in cookie settings box
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
Labels: bug, accessibility, 1 APPROVAL

#3126 [Port dspace-7_x] Bump braces from 3.0.2 to 3.0.3
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#3128 [Port dspace-7_x] Bump tar to 6.2.1
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#3130 Bump express from 4.18.2 to 4.19.2
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#3131 [Port dspace-7_x] Bump postcss to 8.4.38
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#3133 [Port dspace-7_x] Bump ws from 7.5.9 to 7.5.10
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#3127 [Port main] Remove Bitstreams on edit-item-page doesn't work
  src/app/bitstream-page/bitstream-page-routes.ts
  src/app/collection-page/edit-collection-page/collection-source/collection-source.component.html
  src/app/collection-page/edit-collection-page/collection-source/collection-source.component.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/shared/trackable/abstract-trackable.component.spec.ts
  src/app/shared/trackable/abstract-trackable.component.ts
Labels: bug, high priority, component: Item

#3121 Remove Bitstreams on edit-item-page doesn't work
  src/app/collection-page/edit-collection-page/collection-source/collection-source.component.html
  src/app/collection-page/edit-collection-page/collection-source/collection-source.component.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/shared/trackable/abstract-trackable.component.spec.ts
  src/app/shared/trackable/abstract-trackable.component.ts
Labels: bug, high priority, component: Item

#3100 Minor updates to i18n text for OpenAIRE external sources.
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, 1 APPROVAL

#3081 Spanish translation updated
  src/assets/i18n/es.json5
Labels: i18n / l10n, 1 APPROVAL

#3077 Update pt-BR translation for DSpace 8.0 release
  src/assets/i18n/pt-BR.json5
Labels: i18n / l10n, 1 APPROVAL

#3029 src/assets/i18n: CrossRef → Crossref
  src/assets/i18n/ar.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/vi.json5
Labels: i18n / l10n, 1 APPROVAL, low priority, port to dspace-7_x

#3132 Bump Angular to 17.3.11 and Angular-CLI to 17.3.8
  package.json
  src/app/notifications/suggestion-targets/suggestion-targets.effects.ts
  yarn.lock
Labels: dependencies, high priority, 1 APPROVAL

#3138 Fix error which prevent submitter to deposit a new item
  src/app/core/json-patch/json-patch-operations.reducer.spec.ts
  src/app/core/json-patch/json-patch-operations.reducer.ts
  src/app/core/submission/submission-parent-breadcrumb.service.ts
  src/app/core/submission/submission-rest.service.ts
  src/app/submission/sections/upload/section-upload.component.ts
Labels: bug, component: submission, high priority, 1 APPROVAL, port to dspace-7_x

#3139 [Port dspace-7_x] Fix error which prevent submitter to deposit a new item
  src/app/core/json-patch/json-patch-operations.reducer.spec.ts
  src/app/core/json-patch/json-patch-operations.reducer.ts
  src/app/core/submission/submission-parent-breadcrumb.service.ts
  src/app/core/submission/submission-rest.service.ts
Labels: bug, component: submission, high priority, 1 APPROVAL

#3151 [GitHub Config] Minor updates to Contribution docs & issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: code task
