Repository DSpace/dspace-angular, pull requests merged in 2024-05, with the labels that each got.

#2991 Remove obsolete "version" tag from Docker Compose files (Angular version)
  docker/cli.assetstore.yml
  docker/cli.ingest.yml
  docker/cli.yml
  docker/db.entities.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-dist.yml
  docker/docker-compose-rest.yml
  docker/docker-compose.yml
Labels: code task, 1 APPROVAL, backend: Docker, port to dspace-7_x

#2640 More meaningful regex error messages
  src/app/shared/form/builder/form-builder.service.spec.ts
  src/app/shared/form/builder/parsers/concat-field-parser.ts
  src/app/shared/form/builder/parsers/date-field-parser.spec.ts
  src/app/shared/form/builder/parsers/disabled-field-parser.spec.ts
  src/app/shared/form/builder/parsers/dropdown-field-parser.spec.ts
  src/app/shared/form/builder/parsers/dropdown-field-parser.ts
  src/app/shared/form/builder/parsers/field-parser.ts
  src/app/shared/form/builder/parsers/list-field-parser.spec.ts
  src/app/shared/form/builder/parsers/lookup-field-parser.spec.ts
  src/app/shared/form/builder/parsers/lookup-name-field-parser.spec.ts
  src/app/shared/form/builder/parsers/name-field-parser.spec.ts
  src/app/shared/form/builder/parsers/name-field-parser.ts
  src/app/shared/form/builder/parsers/onebox-field-parser.spec.ts
  src/app/shared/form/builder/parsers/parser-factory.ts
  src/app/shared/form/builder/parsers/relation-group-field-parser.spec.ts
  src/app/shared/form/builder/parsers/row-parser.spec.ts
  src/app/shared/form/builder/parsers/series-field-parser.spec.ts
  src/app/shared/form/builder/parsers/series-field-parser.ts
  src/app/shared/form/builder/parsers/tag-field-parser.spec.ts
  src/app/shared/form/builder/parsers/textarea-field-parser.spec.ts
Labels: bug, component: submission, error handling, 1 APPROVAL, needs documentation

#2641 [Port dspace-7_x] More meaningful regex error messages
  src/app/shared/form/builder/form-builder.service.spec.ts
  src/app/shared/form/builder/parsers/concat-field-parser.ts
  src/app/shared/form/builder/parsers/date-field-parser.spec.ts
  src/app/shared/form/builder/parsers/disabled-field-parser.spec.ts
  src/app/shared/form/builder/parsers/dropdown-field-parser.spec.ts
  src/app/shared/form/builder/parsers/dropdown-field-parser.ts
  src/app/shared/form/builder/parsers/field-parser.ts
  src/app/shared/form/builder/parsers/list-field-parser.spec.ts
  src/app/shared/form/builder/parsers/lookup-field-parser.spec.ts
  src/app/shared/form/builder/parsers/lookup-name-field-parser.spec.ts
  src/app/shared/form/builder/parsers/name-field-parser.spec.ts
  src/app/shared/form/builder/parsers/name-field-parser.ts
  src/app/shared/form/builder/parsers/onebox-field-parser.spec.ts
  src/app/shared/form/builder/parsers/parser-factory.ts
  src/app/shared/form/builder/parsers/relation-group-field-parser.spec.ts
  src/app/shared/form/builder/parsers/row-parser.spec.ts
  src/app/shared/form/builder/parsers/series-field-parser.spec.ts
  src/app/shared/form/builder/parsers/series-field-parser.ts
  src/app/shared/form/builder/parsers/tag-field-parser.spec.ts
  src/app/shared/form/builder/parsers/textarea-field-parser.spec.ts
Labels: component: submission, error handling, 1 APPROVAL

#2933 Reset dropdown values
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2980 Clicking save on create community and collection pages provides user feedback
  cypress/e2e/collection-create.cy.ts
  cypress/e2e/community-create.cy.ts
  src/app/collection-page/create-collection-page/create-collection-page.component.html
  src/app/collection-page/create-collection-page/create-collection-page.component.ts
  src/app/community-page/create-community-page/create-community-page.component.html
  src/app/community-page/create-community-page/create-community-page.component.ts
  src/app/shared/comcol/comcol-forms/create-comcol-page/create-comcol-page.component.ts
Labels: bug, usability, component: Community, component: Collection, testathon, claimed: Atmire

#3001 [Port dspace-7_x] Reset dropdown values
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL

#3004 Fix `TypeError: Cannot read properties of undefined (reading 'userAgent')`
  src/app/root/root.component.ts
Labels: bug, 1 APPROVAL

#2831 French translations for missing parameters (access control and batch loading)
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2651 Fixed ItemSearchResultListElementComponent not fully themable
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.html
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.spec.ts
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.ts
  src/app/shared/testing/truncatable-service.stub.ts
Labels: bug, themes, 1 APPROVAL, claimed: Atmire, port to dspace-7_x

#2930 Fix sync-i18n script throwing a compile error & added some missing translation keys
  scripts/sync-i18n-files.ts
  src/app/item-page/edit-item-page/item-move/item-move.component.html
  src/app/shared/dso-selector/dso-selector/dso-selector.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/nl.json5
Labels: bug, i18n / l10n, 1 APPROVAL, claimed: Atmire

#2863 Added Arabic Translation
  config/config.example.yml
  src/assets/i18n/ar.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#3008 [Port dspace-7_x] Added Arabic Translation
  config/config.example.yml
  src/assets/i18n/ar.json5
Labels: i18n / l10n

#3009 [Port dspace-7_x] Bump ejs from 3.1.9 to 3.1.10
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL

#2988 Submission performance
  src/app/core/submission/submission-rest.service.spec.ts
  src/app/core/submission/submission-rest.service.ts
Labels: bug, component: submission, component: workflow, 1 APPROVAL

#2987 7.x - Submission performance
  src/app/core/submission/submission-rest.service.spec.ts
  src/app/core/submission/submission-rest.service.ts
Labels: bug, component: submission, component: workflow, 1 APPROVAL

#3016 Ensure `item` is also embedded in submission form
  src/app/core/submission/submission-rest.service.spec.ts
  src/app/core/submission/submission-rest.service.ts
Labels: bug, component: submission, high priority, 1 APPROVAL, port to dspace-7_x

#2979 Add missing i18n keys for OpenAIRE external sources.
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, 1 APPROVAL

#3014 Handle Null Users Gracefully in Process Overview Page
  src/app/process-page/form/process-form.component.ts
  src/app/process-page/overview/table/process-overview-table.component.spec.ts
  src/app/process-page/overview/table/process-overview-table.component.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL, tools:processes

#3013 [Port dspace-7_x] Handle Null Users Gracefully in Process Overview Page
  src/app/process-page/overview/process-overview.component.spec.ts
  src/app/process-page/overview/process-overview.component.ts
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL, tools:processes

#2875 Moved MetadataValue methods to separate service
  src/app/app.component.spec.ts
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/core/metadata/head-tag.service.spec.ts
  src/app/core/metadata/head-tag.service.ts
  src/app/core/metadata/metadata.service.spec.ts
  src/app/core/metadata/metadata.service.ts
  src/app/core/shared/metadata.models.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts
  src/app/init.service.spec.ts
  src/app/init.service.ts
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/simple/item-page.component.spec.ts
  src/app/item-page/simple/metadata-representation-list/metadata-representation-list.component.ts
  src/app/root/root.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/mocks/head-tag-service.mock.ts
  src/modules/app/browser-init.service.ts
  src/modules/app/server-init.service.ts
Labels: bug, code task, needs documentation

#2866 Allow opening ds-metadata-uri-values links in a new window
  src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.html
  src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.spec.ts
  src/app/item-page/field-components/metadata-uri-values/metadata-uri-values.component.ts
Labels: improvement, 1 APPROVAL, low priority, claimed: Atmire

#2900 Error loading the initial value when editing an authority field in edit item page
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts
Labels: bug, 1 APPROVAL, component: authority control

#3024 [DURACOM-259] add correct metadata
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
Labels: bug, 1 APPROVAL, integration: COAR Notify / LDN

#3010 Item page cc license field
  src/app/item-page/simple/field-components/specific-field/cc-license/item-page-cc-license-field.component.html
  src/app/item-page/simple/field-components/specific-field/cc-license/item-page-cc-license-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/cc-license/item-page-cc-license-field.component.ts
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.ts
  src/assets/i18n/en.json5
  src/assets/images/cc-licenses/by-nc-nd.png
  src/assets/images/cc-licenses/by-nc-sa.png
  src/assets/images/cc-licenses/by-nc.png
  src/assets/images/cc-licenses/by-nd.png
  src/assets/images/cc-licenses/by-sa.png
  src/assets/images/cc-licenses/by.png
  src/assets/images/cc-licenses/zero.png
  src/themes/custom/app/item-page/simple/item-types/untyped-item/untyped-item.component.ts
Labels: improvement, 1 APPROVAL, component: Item, integration: Creative Commons

#3030 Allow submitter users to accept/ignore suggestions
  src/app/notifications/qa/events/quality-assurance-events.component.html
  src/app/notifications/qa/events/quality-assurance-events.component.ts
  src/assets/i18n/ar.json5
  src/assets/i18n/en.json5
Labels: bug, 1 APPROVAL, integration: COAR Notify / LDN

#2725 Encode all `RequestParam` values
  src/app/core/cache/models/request-param.model.ts
  src/app/core/data/relationship-data.service.ts
  src/app/core/data/relationship-type-data.service.ts
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/notifications/qa/events/quality-assurance-event-data.service.spec.ts
  src/app/core/notifications/qa/events/quality-assurance-event-data.service.ts
  src/app/core/statistics/usage-report-data.service.ts
  src/app/core/submission/correctiontype-data.service.ts
  src/app/core/submission/submission-cc-license-url-data.service.ts
  src/app/core/submission/vocabularies/vocabulary.data.service.spec.ts
  src/app/core/submission/vocabularies/vocabulary.data.service.ts
  src/app/core/submission/workflowitem-data.service.ts
  src/app/core/submission/workspaceitem-data.service.spec.ts
  src/app/core/submission/workspaceitem-data.service.ts
Labels: bug, component: submission, component: SEO, testathon, claimed: Atmire, port to dspace-7_x

#2951 Fix display of dso names for EPersons
  src/app/core/breadcrumbs/dso-name.service.spec.ts
  src/app/core/eperson/models/eperson.model.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2954 Live import preview should show all metadata values, not only the first one
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.html
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.spec.ts
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.ts
Labels: bug, 1 APPROVAL, tools:import-sources, port to dspace-7_x

#3034 [Port dspace-7_x] Live import preview should show all metadata values, not only the first one
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.html
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.spec.ts
  src/app/submission/import-external/import-external-preview/submission-import-external-preview.component.ts
Labels: bug, 1 APPROVAL, tools:import-sources

#2973 added maxlength and hint to resource policy
  src/app/shared/resource-policies/form/resource-policy-form.model.ts
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: bug, authorization, 1 APPROVAL, port to main

#3037 Remove unnecessary console.log
  src/app/shared/eperson-group-list/eperson-group-list.component.ts
Labels: code task, 1 APPROVAL

#2771 Layout improvement in feedback form page
  src/app/info/feedback/feedback-form/feedback-form.component.html
Labels: bug, 1 APPROVAL, port to dspace-7_x

#3038 [Port dspace-7_x] improved layout of feedback form (increase vertical spacing)
  src/app/info/feedback/feedback-form/feedback-form.component.html
Labels: bug, 1 APPROVAL

#3027 [Port dspace-7_x] Multiple discovery backports
  src/app/search-page/configuration-search-page.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.spec.ts
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.html
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.spec.ts
  src/app/shared/object-list/item-list-element/item-types/item/item-list-element.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/sidebar/page-with-sidebar.component.html
  src/app/shared/testing/truncatable-service.stub.ts
  src/app/statistics/angulartics/dspace-provider.ts
Labels: bug, component: Discovery, ux

#2983 Fix Author search result without co-author
  src/app/shared/object-list/search-result-list-element/search-result-list-element.component.ts
Labels: bug, component: Discovery, 1 APPROVAL, port to main

#3007 After English, reorder languages alphabetically by language code
  config/config.example.yml
  src/config/default-app-config.ts
Labels: code task, 1 APPROVAL, port to dspace-7_x

#3040 [Port 8.x] Fix for not all CREATE/DELETE Relationship requests coming through, during submission entity lookup
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.scss
Labels: bug, component: submission, component: configurable entities, 1 APPROVAL

#2841 Fix for not all CREATE/DELETE Relationship requests coming through, during submission entity lookup
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.scss
Labels: bug, component: submission, component: configurable entities, 1 APPROVAL

#3042 [Port dspace-7_x] After English, reorder languages alphabetically by code
  config/config.example.yml
  src/config/default-app-config.ts
Labels: i18n / l10n, 1 APPROVAL

#3025 Czech DSpace 7 UI translation by NTK
  src/assets/i18n/cs.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#3028 Add HTML support on system-wide alert (Fixes #3019)
  src/app/system-wide-alert/alert-banner/system-wide-alert-banner.component.html
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.html
Labels: improvement, 1 APPROVAL, port to dspace-7_x

#3043 [Port dspace-7_x] Czech DSpace 7 UI translation by NTK
  src/assets/i18n/cs.json5
Labels: i18n / l10n, 1 APPROVAL

#2837 Enhanced community/collection logo edit
  src/app/collection-page/collection-form/collection-form.component.ts
  src/app/collection-page/create-collection-page/create-collection-page.component.html
  src/app/collection-page/edit-collection-page/collection-metadata/collection-metadata.component.html
  src/app/community-page/community-form/community-form.component.ts
  src/app/community-page/create-community-page/create-community-page.component.html
  src/app/community-page/edit-community-page/community-metadata/community-metadata.component.html
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.html
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.spec.ts
  src/app/shared/comcol/comcol-forms/comcol-form/comcol-form.component.ts
  src/app/shared/comcol/comcol-forms/create-comcol-page/create-comcol-page.component.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-metadata/comcol-metadata.component.spec.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-metadata/comcol-metadata.component.ts
  src/assets/i18n/en.json5
Labels: improvement, 1 APPROVAL, component: Community, component: Collection

#2944 Disable `inlineCriticalCss` by default for better SSR performance
  src/config/ssr-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: performance / caching, configuration, 1 APPROVAL, port to dspace-7_x

#2706 Update pt-PT.json5
  src/assets/i18n/pt-PT.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#3051 [Port dspace-7_x] Disable inlineCriticalCss by default for better SSR performance
  config/config.example.yml
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: performance / caching, configuration, 1 APPROVAL

#3053 [Port dspace-7_x] Fix submission lost changes after save
  src/app/core/submission/submission-json-patch-operations.service.spec.ts
  src/app/core/submission/submission-json-patch-operations.service.ts
Labels: bug, component: submission, 1 APPROVAL

#3046 Fix self link don't match warnings for authorization endpoint
  src/app/core/data/feature-authorization/authorization-data.service.spec.ts
  src/app/core/data/feature-authorization/authorization-data.service.ts
Labels: bug, testathon, port to dspace-7_x

#3056 Fixed item-edit.cy.ts regularly failing & minor UI improvements
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/submission.cy.ts
  src/app/footer/footer.component.html
  src/app/info/notify-info/notify-info.component.html
  src/app/info/notify-info/notify-info.component.spec.ts
  src/app/info/notify-info/notify-info.component.ts
  src/app/login-page/login-page.component.html
  src/app/logout-page/logout-page.component.html
  src/app/my-dspace-page/my-dspace-qa-events-notifications/my-dspace-qa-events-notifications.component.scss
  src/app/shared/comcol/comcol-forms/edit-comcol-page/edit-comcol-page.component.html
  src/app/shared/dso-page/dso-edit-menu/dso-edit-expandable-menu-section/dso-edit-menu-expandable-section.component.html
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.html
  src/assets/i18n/en.json5
  src/assets/images/dspace-logo.png
  src/assets/images/n-coar.png
  src/assets/images/n-coar.svg
  src/themes/custom/app/login-page/login-page.component.html
  src/themes/custom/app/login-page/login-page.component.scss
  src/themes/custom/app/logout-page/logout-page.component.html
  src/themes/custom/app/logout-page/logout-page.component.scss
Labels: bug, accessibility, 1 APPROVAL, testathon, testing framework, integration: COAR Notify / LDN

#3061 Hide search text field when number of facet values is less than the maximum
  src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.html
Labels: bug, component: Discovery, 1 APPROVAL, port to main

#3069 #2923 - Fixed redirect on new Item version creation
  src/app/core/submission/workspaceitem-data.service.spec.ts
  src/app/core/submission/workspaceitem-data.service.ts
Labels: bug, component: versioning, 1 APPROVAL

#3062 Made legacy bitstream URLs redirect with 301 status code
  src/app/bitstream-page/bitstream-page-routes.ts
  src/app/bitstream-page/legacy-bitstream-url-redirect.guard.spec.ts
  src/app/bitstream-page/legacy-bitstream-url-redirect.guard.ts
  src/app/bitstream-page/legacy-bitstream-url.resolver.spec.ts
  src/app/bitstream-page/legacy-bitstream-url.resolver.ts
  src/app/shared/testing/server-response-service.stub.ts
Labels: bug, component: SEO, high priority, testathon, claimed: Atmire, port to dspace-7_x

#3080 Fixed page size change and sorting not working on comcol pages
  src/app/shared/page-size-selector/page-size-selector.component.html
  src/app/shared/search/search-settings/search-settings.component.html
  src/app/shared/sidebar/sidebar-dropdown.component.html
  src/app/shared/sidebar/sidebar-dropdown.component.ts
Labels: bug, component: configurable entities, high priority, 1 APPROVAL, component: Community, component: Collection, testathon, claimed: Atmire, port to dspace-7_x

#3079 Fixed delete item page freezing when having relationships
  src/app/core/data/base/delete-data.spec.ts
  src/app/core/data/base/delete-data.ts
  src/app/item-page/edit-item-page/item-delete/item-delete.component.html
  src/app/item-page/edit-item-page/item-delete/item-delete.component.ts
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/full/full-item-page.component.ts
  src/app/item-page/item-page.resolver.spec.ts
  src/app/item-page/item-page.resolver.ts
  src/app/item-page/simple/item-page.component.spec.ts
  src/app/item-page/simple/item-page.component.ts
Labels: bug, component: configurable entities, high priority, 1 APPROVAL, testathon, port to dspace-7_x

#3064 [Port dspace-7_x] Fixed item-edit.cy.ts regularly failing & minor UI improvements
  cypress/e2e/item-edit.cy.ts
  cypress/e2e/submission.cy.ts
  src/app/login-page/login-page.component.html
  src/app/logout-page/logout-page.component.html
  src/app/shared/comcol/comcol-forms/edit-comcol-page/edit-comcol-page.component.html
  src/app/shared/dso-page/dso-edit-menu/dso-edit-expandable-menu-section/dso-edit-menu-expandable-section.component.html
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.html
  src/assets/images/dspace-logo.png
  src/themes/custom/app/login-page/login-page.component.html
  src/themes/custom/app/login-page/login-page.component.scss
  src/themes/custom/app/logout-page/logout-page.component.html
  src/themes/custom/app/logout-page/logout-page.component.scss
Labels: bug, accessibility, testathon, testing framework

#2761 Fix caching issues for versioning
  src/app/core/data/base/identifiable-data.service.spec.ts
  src/app/core/data/base/identifiable-data.service.ts
  src/app/core/data/version-history-data.service.spec.ts
  src/app/core/data/version-history-data.service.ts
  src/app/core/submission/workflowitem-data.service.ts
  src/app/shared/dso-page/dso-versioning-modal-service/dso-versioning-modal.service.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.ts
  src/app/submission/objects/submission-objects.effects.spec.ts
  src/app/submission/objects/submission-objects.effects.ts
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
Labels: bug, component: versioning, performance / caching, component: Item, port to dspace-7_x

#3095 [Port dspace-7_x] Fix caching issues for versioning
  src/app/core/data/base/identifiable-data.service.spec.ts
  src/app/core/data/base/identifiable-data.service.ts
  src/app/core/data/version-history-data.service.spec.ts
  src/app/core/data/version-history-data.service.ts
  src/app/core/submission/workflowitem-data.service.ts
  src/app/shared/dso-page/dso-versioning-modal-service/dso-versioning-modal.service.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts
  src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.ts
  src/app/submission/objects/submission-objects.effects.spec.ts
  src/app/submission/objects/submission-objects.effects.ts
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
Labels: bug, component: versioning, performance / caching, component: Item

#3060 Fixed creation & deletion of relationships not working correctly & added same entity type relationship support
  src/app/app.component.ts
  src/app/core/data/object-updates/object-updates.reducer.ts
  src/app/core/data/object-updates/object-updates.service.ts
  src/app/core/data/relationship-data.service.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.html
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.html
  src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.spec.ts
  src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/themed-dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.ts
  src/app/shared/testing/base-data-service.stub.ts
  src/app/shared/testing/edit-item-relationships.service.stub.ts
  src/app/shared/testing/entity-type-data.service.stub.ts
  src/app/shared/testing/item-data.service.stub.ts
  src/app/shared/testing/object-updates.service.stub.ts
  src/app/shared/testing/relationship-data.service.stub.ts
  src/assets/i18n/en.json5
Labels: bug, component: configurable entities, high priority, testathon

#3059 [Port dspace-7_x] Fixed creation & deletion of relationships not working correctly & added same entity type relationship support
  src/app/app.component.ts
  src/app/core/data/object-updates/object-updates.reducer.ts
  src/app/core/data/object-updates/object-updates.service.ts
  src/app/core/data/relationship-data.service.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-item-relationships.service.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.html
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship/edit-relationship.component.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.html
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/item-relationships.component.ts
  src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.html
  src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.spec.ts
  src/app/item-page/edit-item-page/virtual-metadata/virtual-metadata.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/themed-dynamic-lookup-relation-search-tab.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.ts
  src/app/shared/testing/base-data-service.stub.ts
  src/app/shared/testing/edit-item-relationships.service.stub.ts
  src/app/shared/testing/entity-type-data.service.stub.ts
  src/app/shared/testing/item-data.service.stub.ts
  src/app/shared/testing/object-updates.service.stub.ts
  src/app/shared/testing/relationship-data.service.stub.ts
  src/assets/i18n/en.json5
Labels: bug, component: configurable entities, high priority, testathon

#3097 [Port main] Hide search text field when number of facet values is less than the maximum
  src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.html
Labels: bug, component: Discovery, 1 APPROVAL
