Repository DSpace/dspace-angular, pull requests merged in 2024-03, with the labels that each got.

#2749 Basic Duplicate Detection
  config/config.example.yml
  src/app/core/core.module.ts
  src/app/core/submission/models/workspaceitem-section-duplicates.model.ts
  src/app/core/submission/models/workspaceitem-sections.model.ts
  src/app/core/submission/submission-duplicate-data.service.spec.ts
  src/app/core/submission/submission-duplicate-data.service.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/shared/object-list/duplicate-data/duplicate.model.ts
  src/app/shared/object-list/duplicate-data/duplicate.resource-type.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.html
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.spec.ts
  src/app/shared/object-list/my-dspace-result-list-element/pool-search-result/pool-search-result-list-element.component.ts
  src/app/submission/objects/submission-objects.actions.ts
  src/app/submission/objects/submission-objects.effects.ts
  src/app/submission/objects/submission-objects.reducer.spec.ts
  src/app/submission/objects/submission-objects.reducer.ts
  src/app/submission/sections/duplicates/section-duplicates.component.html
  src/app/submission/sections/duplicates/section-duplicates.component.spec.ts
  src/app/submission/sections/duplicates/section-duplicates.component.ts
  src/app/submission/sections/sections-type.ts
  src/app/submission/submission.module.ts
  src/assets/i18n/en.json5
  src/config/config.util.spec.ts
  src/config/default-app-config.ts
  src/config/submission-config.interface.ts
  src/environments/environment.test.ts
Labels: component: submission, component: workflow, high priority, new feature

#2371 Fix Spec has no expectations errors
  karma.conf.js
  src/app/access-control/epeople-registry/epeople-registry.component.spec.ts
  src/app/community-page/sections/sub-com-col-section/sub-collection-list/community-page-sub-collection-list.component.spec.ts
  src/app/community-page/sections/sub-com-col-section/sub-community-list/community-page-sub-community-list.component.spec.ts
  src/app/core/auth/auth.interceptor.spec.ts
  src/app/core/cache/object-cache.reducer.spec.ts
  src/app/core/cache/server-sync-buffer.reducer.spec.ts
  src/app/core/coar-notify/notify-info/notify-info.service.spec.ts
  src/app/core/data/external-source-data.service.spec.ts
  src/app/core/data/object-updates/object-updates.effects.spec.ts
  src/app/core/data/object-updates/object-updates.reducer.spec.ts
  src/app/core/data/object-updates/object-updates.reducer.ts
  src/app/core/eperson/eperson-data.service.spec.ts
  src/app/core/eperson/eperson-data.service.ts
  src/app/core/shared/item.model.spec.ts
  src/app/entity-groups/journal-entities/item-pages/journal-issue/journal-issue.component.html
  src/app/entity-groups/journal-entities/item-pages/journal-volume/journal-volume.component.html
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.html
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/entity-groups/research-entities/item-pages/person/person.component.html
  src/app/entity-groups/research-entities/item-pages/project/project.component.html
  src/app/home-page/top-level-community-list/top-level-community-list.component.spec.ts
  src/app/item-page/edit-item-page/edit-item-operators.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.spec.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-drag-handle/item-edit-bitstream-drag-handle.component.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream/item-edit-bitstream.component.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts
  src/app/item-page/simple/item-types/publication/publication.component.html
  src/app/item-page/simple/item-types/shared/item.component.spec.ts
  src/app/item-page/simple/item-types/shared/item.component.ts
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
  src/app/item-page/versions/item-versions.component.spec.ts
  src/app/shared/browse-by/browse-by.component.spec.ts
  src/app/shared/browse-by/shared-browse-by.module.ts
  src/app/shared/dso-page/dso-edit-menu.resolver.spec.ts
  src/app/shared/dso-page/dso-edit-menu.resolver.ts
  src/app/shared/form/vocabulary-treeview-modal/vocabulary-treeview-modal.component.ts
  src/app/shared/host-window.reducer.spec.ts
  src/app/shared/menu/menu.reducer.spec.ts
  src/app/shared/notifications/notifications.reducers.spec.ts
  src/app/shared/object-list/metadata-representation-list-element/browse-link/browse-link-metadata-list-element.component.spec.ts
  src/app/shared/object-list/metadata-representation-list-element/metadata-representation-list-element.component.spec.ts
  src/app/shared/object-list/metadata-representation-list-element/metadata-representation-list-element.component.ts
  src/app/shared/object-list/object-list.component.html
  src/app/shared/object-list/search-result-list-element/collection-search-result/collection-search-result-list-element.component.spec.ts
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-filter.reducer.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/app/shared/sidebar/sidebar.reducer.spec.ts
  src/app/shared/subscriptions/subscriptions-data.service.spec.ts
  src/app/shared/truncatable/truncatable.reducer.spec.ts
  src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
Labels: code task, 1 APPROVAL, testing framework

#2849 [Port dspace-7_x] Update dependencies for Node v20
  package.json
  yarn.lock
Labels: dependencies, quick win, code task, 1 APPROVAL

#2856 fix 'undefined' error on anonymous item page landing
  src/app/item-page/edit-item-page/edit-item-page.component.html
  src/app/item-page/simple/item-page.component.ts
Labels: bug, 1 APPROVAL, integration: COAR Notify / LDN

#2777 Element reference for typeahead directive is only defined when model has authority
  src/app/shared/form/builder/ds-dynamic-form-ui/models/tag/dynamic-tag.component.ts
Labels: bug, component: submission, 1 APPROVAL, port to dspace-7_x

#2877 System-wide alert shouldn't be created when the message is empty
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.spec.ts
  src/app/system-wide-alert/alert-form/system-wide-alert-form.component.ts
Labels: bug, 1 APPROVAL, claimed: Atmire, port to dspace-7_x
