Repository DSpace/dspace-angular, pull requests merged in 2024-08, with the labels that each got.

#3220 Enabling navbar links in import section
  src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.scss
Labels: quick win, 1 APPROVAL, ux, port to dspace-8_x

#3230 Improving the file browser for importing metadata
  src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.component.html
  src/app/shared/upload/file-dropzone-no-uploader/file-dropzone-no-uploader.component.ts
Labels: bug, component: administrative tools, 1 APPROVAL, component: file upload, port to dspace-8_x

#3234 WorkspaceitemsEditPageModule: remove duplicated delete route
  src/app/workspaceitems-edit-page/workspaceitems-edit-page-routes.ts
Labels: code task, 1 APPROVAL, port to dspace-8_x

#3235 Missing translations in de.json5 (translation key prefix workspace-item)
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL

#3239 [Port dspace-8_x] Missing translations in de.json5 (translation key prefix workspace-item)
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL

#3048 add import of missing Angular interfaces (squashed version)
  .eslintrc.json
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.ts
  src/app/admin/admin-reports/filtered-collections/filtered-collections.component.ts
  src/app/admin/admin-reports/filtered-items/filtered-items.component.ts
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/collection-search-result/collection-admin-search-result-grid-element.component.ts
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/community-search-result/community-admin-search-result-grid-element.component.ts
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-list-element/collection-search-result/collection-admin-search-result-list-element.component.ts
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-list-element/community-search-result/community-admin-search-result-list-element.component.ts
  src/app/collection-page/edit-collection-page/collection-curate/collection-curate.component.ts
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.ts
  src/app/core/submission/submission-duplicate-data.service.ts
  src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.ts
  src/app/forgot-password/forgot-password-form/forgot-password-form.component.ts
  src/app/home-page/recent-item-list/recent-item-list.component.ts
  src/app/item-page/edit-item-page/item-register-doi/item-register-doi.component.ts
  src/app/item-page/edit-item-page/item-status/item-status.component.ts
  src/app/item-page/edit-item-page/item-version-history/item-version-history.component.ts
  src/app/item-page/orcid-page/orcid-queue/orcid-queue.component.ts
  src/app/item-page/simple/related-items/related-items-component.ts
  src/app/notifications/qa/project-entry-import-modal/project-entry-import-modal.component.ts
  src/app/notifications/qa/source/quality-assurance-source.component.ts
  src/app/notifications/suggestion-targets/publication-claim/publication-claim.component.ts
  src/app/process-page/form/process-parameters/parameter-value-input/date-value-input/date-value-input.component.ts
  src/app/process-page/form/process-parameters/parameter-value-input/string-value-input/string-value-input.component.ts
  src/app/process-page/form/process-parameters/process-parameters.component.ts
  src/app/profile-page/profile-page-security-form/profile-page-security-form.component.ts
  src/app/shared/dso-page/dso-edit-menu/dso-edit-expandable-menu-section/dso-edit-menu-expandable-section.component.ts
  src/app/shared/error/error.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/selection-tab/dynamic-lookup-relation-selection-tab.component.ts
  src/app/shared/form/number-picker/number-picker.component.ts
  src/app/shared/object-collection/shared/badges/access-status-badge/access-status-badge.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/workflow-item-search-result/workflow-item-search-result-detail-element.component.ts
  src/app/shared/object-detail/my-dspace-result-detail-element/workspace-item-search-result/workspace-item-search-result-detail-element.component.ts
  src/app/shared/object-grid/search-result-grid-element/item-search-result/item/item-search-result-grid-element.component.ts
  src/app/shared/object-list/identifier-data/identifier-data.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-approved-search-result/claimed-approved-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/claimed-search-result/claimed-declined-search-result/claimed-declined-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/workflow-item-search-result/workflow-item-search-result-list-element.component.ts
  src/app/shared/object-list/my-dspace-result-list-element/workspace-item-search-result/workspace-item-search-result-list-element.component.ts
  src/app/shared/object-list/search-result-list-element/collection-search-result/collection-search-result-list-element.component.ts
  src/app/shared/object-list/search-result-list-element/community-search-result/community-search-result-list-element.component.ts
  src/app/shared/object-list/search-result-list-element/item-search-result/item-types/item/item-search-result-list-element.component.ts
  src/app/shared/object-list/sidebar-search-list-element/sidebar-search-list-element.component.ts
  src/app/shared/pagination-drag-and-drop/abstract-paginated-drag-and-drop-list.component.ts
  src/app/shared/upload/uploader/uploader.component.ts
  src/app/submission/form/collection/submission-form-collection.component.ts
  src/app/submission/form/submission-upload-files/submission-upload-files.component.ts
  src/app/submission/sections/duplicates/section-duplicates.component.ts
  src/app/submission/sections/identifiers/section-identifiers.component.ts
Labels: code task, 1 APPROVAL, port to dspace-8_x

#3236 #3094 - Update date slider to prevent automatic page reloads
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
Labels: bug, accessibility, component: Discovery, 1 APPROVAL, claimed: 4Science, port to dspace-7_x, port to dspace-8_x, funded

#3243 Fix lint error regarding missing interface
  src/app/notifications/suggestion-targets/publication-claim/publication-claim.component.ts
Labels: code task, 1 APPROVAL, port to dspace-8_x

#3245 [Port dspace-7_x] #3094 - Update date slider to prevent automatic page reloads
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
Labels: bug, accessibility, component: Discovery, 1 APPROVAL, claimed: 4Science, funded

#3251 Minor accessibibity fixes
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
Labels: accessibility, 1 APPROVAL, port to dspace-7_x, affects: 8.x, affects: 7.x, port to dspace-8_x

#3277 Typo in German translation
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3035 Set color black on filter section for mobile
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
Labels: bug, 1 APPROVAL, port to main, port to dspace-8_x

#3253 Fixed Edit Item's Version History crashing
  src/app/item-page/versions/item-versions.component.html
  src/app/item-page/versions/item-versions.component.ts
Labels: bug, component: versioning, performance / caching, claimed: Atmire, port to dspace-7_x, port to dspace-8_x

#3285 [Port dspace-7_x] Bump axios from 1.6.7 to 1.7.4
  package.json
  yarn.lock
Labels: dependencies
