Repository DSpace/dspace-angular, pull requests merged in 2024-11, with the labels that each got.

#3272 Improving accessibility on the new user registration page
  src/app/register-email-form/register-email-form.component.html
  src/app/register-email-form/register-email-form.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, authentication: general, authentication: password, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3590 Complete tag translations in french for ORCID and Researcher Profile
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3619 BitstreamAuthorizationsComponent: update selector and comment to correctly describe component's purpose
  src/app/bitstream-page/bitstream-authorizations/bitstream-authorizations.component.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3620 class `Metadata`: rename parameter names in JSDoc from `mapOrMaps` to `mdMapOrMaps`
  src/app/core/shared/metadata.utils.ts
Labels: code task, 1 APPROVAL

#3199 [#2718] Migrate cookie consent from Klaro to Orejime
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
  cypress/e2e/admin-sidebar.cy.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.html
  src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.ts
  src/app/admin/admin-sidebar/admin-sidebar.component.html
  src/app/admin/admin-sidebar/admin-sidebar.component.ts
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.html
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts
  src/app/collection-page/collection-item-mapper/collection-item-mapper.component.html
  src/app/collection-page/collection-item-mapper/collection-item-mapper.component.ts
  src/app/core/google-recaptcha/google-recaptcha.service.spec.ts
  src/app/core/google-recaptcha/google-recaptcha.service.ts
  src/app/footer/footer.component.ts
  src/app/item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.html
  src/app/item-page/edit-item-page/item-collection-mapper/item-collection-mapper.component.ts
  src/app/register-email-form/register-email-form.component.html
  src/app/register-email-form/register-email-form.component.ts
  src/app/shared/cookies/browser-orejime.service.spec.ts
  src/app/shared/cookies/browser-orejime.service.ts
  src/app/shared/cookies/klaro-configuration.ts
  src/app/shared/cookies/orejime-configuration.ts
  src/app/shared/cookies/orejime.service.ts
  src/app/statistics/google-analytics.service.spec.ts
  src/app/statistics/google-analytics.service.ts
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/vi.json5
  src/modules/app/browser-app.config.ts
  src/modules/app/browser-init.service.ts
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
  src/styles/_vendor.scss
  src/themes/custom/app/admin/admin-sidebar/admin-sidebar.component.ts
Labels: accessibility, new feature, funded

#3625 Fix Klaro translations by forcing Klaro to use a zy language code that DSpace will translate
  src/app/shared/cookies/browser-klaro.service.spec.ts
  src/app/shared/cookies/browser-klaro.service.ts
  src/app/shared/cookies/klaro-configuration.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#3328 [8.x] Accessibility cookie settings
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x

#3627 [Port dspace-7_x] Klaro Accessibility cookie settings
  src/styles/_custom_variables.scss
  src/styles/_global-styles.scss
Labels: bug, accessibility, 1 APPROVAL

#3644 French translations for COAR Notify LDN Service
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3585 Removed observable function calls from template (part 1)
  src/app/access-control/epeople-registry/epeople-registry.component.html
  src/app/access-control/epeople-registry/epeople-registry.component.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/access-control/group-registry/group-form/group-form.component.html
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.html
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.spec.ts
  src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.html
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.spec.ts
  src/app/admin/admin-registries/metadata-registry/metadata-registry.component.ts
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.html
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.spec.ts
  src/app/admin/admin-registries/metadata-registry/metadata-schema-form/metadata-schema-form.component.ts
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.spec.ts
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.spec.ts
  src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts
  src/app/item-page/alerts/item-alerts.component.html
  src/app/item-page/alerts/item-alerts.component.spec.ts
  src/app/item-page/alerts/item-alerts.component.ts
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/pagination/pagination.component.ts
  src/app/shared/testing/registry.service.stub.ts
Labels: bug, high priority, performance / caching, component: Item, claimed: Atmire, port to dspace-7_x, port to dspace-8_x

#3646 Fixed authorization tab not loading in dev mode
  src/app/item-page/item-page.resolver.ts
Labels: bug, component: Item, port to dspace-8_x

#3225 Fixed headings by their rank
  src/app/collection-page/create-collection-page/create-collection-page.component.html
  src/app/community-page/create-community-page/create-community-page.component.html
  src/app/notifications/qa/events/quality-assurance-events.component.html
  src/app/notifications/qa/source/quality-assurance-source.component.html
  src/app/notifications/qa/topics/quality-assurance-topics.component.html
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
  src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html
  src/app/shared/search/search-results/search-results.component.html
  src/app/submission/sections/upload/section-upload.component.html
  src/app/workspaceitems-edit-page/workspaceitems-delete-page/workspaceitems-delete-page.component.html
Labels: bug, accessibility, 1 APPROVAL, claimed: 4Science, port to dspace-7_x, port to dspace-8_x, funded

#3649 French translations for subscriptions feature
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3650 [Port dspace-8_x] Fixed headings by their rank
  src/app/collection-page/create-collection-page/create-collection-page.component.html
  src/app/community-page/create-community-page/create-community-page.component.html
  src/app/notifications/qa/events/quality-assurance-events.component.html
  src/app/notifications/qa/source/quality-assurance-source.component.html
  src/app/notifications/qa/topics/quality-assurance-topics.component.html
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
  src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html
  src/app/shared/search/search-results/search-results.component.html
  src/app/submission/sections/upload/section-upload.component.html
  src/app/workspaceitems-edit-page/workspaceitems-delete-page/workspaceitems-delete-page.component.html
Labels: bug, accessibility, 1 APPROVAL, claimed: 4Science

#3651 [Port dspace-7_x] Fixed headings by their rank
  src/app/collection-page/create-collection-page/create-collection-page.component.html
  src/app/community-page/create-community-page/create-community-page.component.html
  src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.html
  src/app/shared/object-list/my-dspace-result-list-element/item-list-preview/item-list-preview.component.html
  src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html
  src/app/shared/search/search-results/search-results.component.html
  src/app/submission/sections/upload/section-upload.component.html
  src/app/workspaceitems-edit-page/workspaceitems-delete-page/workspaceitems-delete-page.component.html
Labels: bug, accessibility, 1 APPROVAL, claimed: 4Science

#3656 #3655 - Fixes Spacing Issue Between Email Label and Email Address on Profile Setup Form
  src/app/register-page/create-profile/create-profile.component.html
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3661 [Port dspace-8_x] Added support for caching embedded objects without a self link & null responses
  src/app/core/breadcrumbs/item-breadcrumb.resolver.ts
  src/app/core/browse/browse.service.spec.ts
  src/app/core/browse/browse.service.ts
  src/app/core/cache/object-cache.reducer.ts
  src/app/core/cache/object-cache.service.ts
  src/app/core/data/dspace-rest-response-parsing.service.ts
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/core/data/version-history-data.service.ts
  src/app/core/index/index.effects.ts
  src/app/home-page/recent-item-list/recent-item-list.component.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-delete/item-delete.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/item-page.resolver.ts
  src/app/item-page/item.resolver.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/utils/relation-query.utils.ts
Labels: bug, component: Discovery, high priority, performance / caching, claimed: Atmire

#3660 [Port dspace-7_x] Added support for caching embedded objects without a self link & null responses
  cypress/e2e/item-edit.cy.ts
  src/app/collection-page/collection-page.component.ts
  src/app/core/breadcrumbs/item-breadcrumb.resolver.ts
  src/app/core/browse/browse.service.spec.ts
  src/app/core/browse/browse.service.ts
  src/app/core/cache/object-cache.reducer.ts
  src/app/core/cache/object-cache.service.ts
  src/app/core/data/dspace-rest-response-parsing.service.ts
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-data.service.ts
  src/app/core/data/version-history-data.service.ts
  src/app/core/index/index.effects.ts
  src/app/home-page/recent-item-list/recent-item-list.component.ts
  src/app/item-page/edit-item-page/abstract-item-update/abstract-item-update.component.ts
  src/app/item-page/edit-item-page/item-delete/item-delete.component.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
  src/app/item-page/item.resolver.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts
  src/app/shared/utils/relation-query.utils.ts
Labels: bug, component: Discovery, high priority, performance / caching, claimed: Atmire

#3671 Fixes the display of the System Wide Alert
  src/app/core/provide-core.ts
Labels: bug, high priority, 1 APPROVAL, port to dspace-8_x

#3681 Update docker files for 8_x
  Dockerfile.dist
  docker/README.md
  docker/cli.yml
  docker/db.entities.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-dist.yml
  docker/docker-compose-rest.yml
  docker/docker-compose.yml
Labels: 1 APPROVAL, backend: Docker

#3683 Fix incorrect example in `config.example.yml`
  config/config.example.yml
Labels: configuration, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3685 [Port dspace-7_x] Fix incorrect example in `config.example.yml`
  config/config.example.yml
Labels: configuration, 1 APPROVAL

#3181 Orcid Authorization / Synchronization Page Fixes
  src/app/item-page/orcid-page/orcid-auth/orcid-auth.component.ts
  src/app/item-page/orcid-page/orcid-page.component.ts
  src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.spec.ts
  src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.ts
  src/app/shared/remote-data.utils.ts
Labels: bug, high priority, authentication: general, 1 APPROVAL, integration: ORCID

#3308 #3288 - Enabled 'admin-div' only for Site Administrator
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
Labels: bug, component: administrative tools, 1 APPROVAL, component: Community, port to dspace-7_x, port to dspace-8_x

#3696 [Port dspace-7_x] #3288 - Enabled 'admin-div' only for Site Administrator
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.spec.ts
  src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.ts
Labels: bug, component: administrative tools, 1 APPROVAL, component: Community
