Repository DSpace/dspace-angular, pull requests merged in 2024-02, with the labels that each got.

#2778 Dedupe patch operations by op and path
  src/app/core/json-patch/json-patch-operations.reducer.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x

#2791 Fix issue with cli.yml not using same network as backend.
  .github/workflows/build.yml
  docker/cli.assetstore.yml
  docker/cli.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
Labels: bug, high priority, 1 APPROVAL, backend: Docker, port to dspace-7_x

#2796 [Port dspace-7_x] Fix issue with cli.yml not using same network as backend.
  .github/workflows/build.yml
  docker/cli.assetstore.yml
  docker/cli.yml
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
Labels: bug, high priority, 1 APPROVAL, backend: Docker

#2795 fix German translation of admin.workflow.item.workflow
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2766 Fix missing Register DOI button if configuration enabled
  src/app/item-page/edit-item-page/item-status/item-status.component.ts
Labels: bug, identifiers: DOIs, 1 APPROVAL, component: Item, port to dspace-7_x

#2705 Minor updates to i18n strings for clarity and consistency
  src/app/info/privacy/privacy-content/privacy-content.component.html
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2373 Added support to import from external source on Edit Item > Relationships
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/dynamic-lookup-relation-modal.component.ts
  src/assets/i18n/en.json5
Labels: component: configurable entities, new feature, 1 APPROVAL, component: Item, integration: ORCID, claimed: Atmire

#2624 [#2622] Makes forgot-password link removable
  src/app/app-routing.module.ts
  src/app/core/data/feature-authorization/feature-id.ts
  src/app/core/rest-property/forgot-password-check-guard.guard.ts
  src/app/shared/log-in/methods/password/log-in-password.component.html
  src/app/shared/log-in/methods/password/log-in-password.component.ts
Labels: authentication: password, authorization, new feature, 1 APPROVAL

#2800 [Port dspace-7_x] Refactored community & collection pages
  src/app/admin/admin-search-page/admin-search-results/admin-search-result-grid-element/item-search-result/item-admin-search-result-grid-element.component.ts
  src/app/admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-grid-element/workflow-item/workflow-item-search-result-admin-workflow-grid-element.component.ts
  src/app/admin/admin-workflow-page/admin-workflow-search-results/admin-workflow-search-result-grid-element/workspace-item/workspace-item-search-result-admin-workflow-grid-element.component.ts
  src/app/shared/comcol/comcol-page-browse-by/comcol-page-browse-by.component.html
  src/app/shared/context-help.directive.ts
  src/app/shared/loading/themed-loading.component.ts
  src/app/shared/metadata-representation/metadata-representation-loader.component.ts
  src/app/shared/mydspace-actions/claimed-task/switcher/claimed-task-actions-loader.component.ts
  src/app/shared/object-collection/shared/listable-object/listable-object-component-loader.component.ts
  src/app/shared/theme-support/themed.component.ts
  src/app/workflowitems-edit-page/advanced-workflow-action/advanced-workflow-actions-loader/advanced-workflow-actions-loader.component.ts
Labels: bug, accessibility, themes

#2719 ROR Integration - Identifier Visualization
  src/app/entity-groups/research-entities/item-pages/org-unit/org-unit.component.html
  src/app/item-page/field-components/metadata-values/metadata-values.component.html
  src/app/item-page/field-components/metadata-values/metadata-values.component.ts
  src/app/item-page/item-shared.module.ts
  src/app/item-page/simple/field-components/specific-field/img/item-page-img-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/img/item-page-img-field.component.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.html
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/assets/i18n/en.json5
  src/assets/images/ror-icon.svg
  src/styles/_custom_variables.scss
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
Labels: new feature, component: Item

#2647 File edit component updated to work for forms without access conditions.
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
Labels: bug, component: submission, 1 APPROVAL, port to dspace-7_x

#2794 Added scope @Input() to the SearchComponent & fixed related bugs
  src/app/core/shared/search/search-filter.service.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-wrapper/search-facet-filter-wrapper.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter/search-facet-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.html
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-range-filter/search-range-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-settings/search-settings.component.spec.ts
  src/app/shared/search/search-settings/search-settings.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
  src/assets/i18n/en.json5
Labels: bug, component: Discovery, 1 APPROVAL, claimed: Atmire, port to dspace-7_x

#2770 German translations of feedback page translation keys
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#2733 Use keyboard to select values
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
Labels: bug, accessibility, component: submission, 1 APPROVAL, port to dspace-7_x

#2821 [Port dspace-7_x] Use keyboard to select values (part 2)
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
Labels: bug, accessibility, component: submission, 1 APPROVAL

#2631 CST-12044 visualize the primary bitstream & CST-12043 primary bitstream flag
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.scss
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/app/core/data/bitstream-data.service.spec.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/submission/models/workspaceitem-section-upload.model.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.html
  src/app/item-page/simple/field-components/file-section/file-section.component.spec.ts
  src/app/item-page/simple/field-components/file-section/file-section.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/custom-switch/custom-switch.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/custom-switch/custom-switch.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/models/custom-switch/custom-switch.component.spec.ts
  src/app/shared/form/builder/form-builder.service.ts
  src/app/shared/mocks/section-upload.service.mock.ts
  src/app/shared/mocks/submission.mock.ts
  src/app/submission/objects/submission-objects.actions.ts
  src/app/submission/objects/submission-objects.reducer.ts
  src/app/submission/sections/license/section-license.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.html
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.spec.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts
  src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts
  src/app/submission/sections/upload/file/section-upload-file.component.html
  src/app/submission/sections/upload/file/section-upload-file.component.spec.ts
  src/app/submission/sections/upload/file/section-upload-file.component.ts
  src/app/submission/sections/upload/file/themed-section-upload-file.component.ts
  src/app/submission/sections/upload/section-upload.component.html
  src/app/submission/sections/upload/section-upload.component.spec.ts
  src/app/submission/sections/upload/section-upload.component.ts
  src/app/submission/sections/upload/section-upload.service.spec.ts
  src/app/submission/sections/upload/section-upload.service.ts
  src/assets/i18n/en.json5
Labels: component: submission, new feature

#2820 Add translation for DOI multiple parallel import source.
  src/assets/i18n/en.json5
Labels: i18n / l10n, 1 APPROVAL

#2732 Added search facets to community & collection pages
  config/config.example.yml
  src/app/collection-page/collection-page-routing.module.ts
  src/app/collection-page/collection-page.module.ts
  src/app/collection-page/sections/recently-added/collection-recently-added.component.html
  src/app/collection-page/sections/recently-added/collection-recently-added.component.spec.ts
  src/app/collection-page/sections/recently-added/collection-recently-added.component.ts
  src/app/community-page/community-page-routing.module.ts
  src/app/community-page/sections/sub-com-col-section/sub-com-col-section.component.spec.ts
  src/app/community-page/sections/sub-com-col-section/sub-com-col-section.component.ts
  src/app/search-page/configuration-search-page.component.ts
  src/app/shared/comcol/comcol-page-browse-by/comcol-page-browse-by.component.ts
  src/app/shared/comcol/comcol.module.ts
  src/app/shared/comcol/sections/comcol-search-section/comcol-search-section.component.html
  src/app/shared/comcol/sections/comcol-search-section/comcol-search-section.component.scss
  src/app/shared/comcol/sections/comcol-search-section/comcol-search-section.component.spec.ts
  src/app/shared/comcol/sections/comcol-search-section/comcol-search-section.component.ts
  src/app/shared/search-form/search-form.component.ts
  src/app/shared/search-form/themed-search-form.component.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.ts
  src/app/shared/search/search.component.html
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/search/themed-search.component.ts
  src/app/shared/sidebar/page-with-sidebar.component.html
  src/app/shared/testing/active-router.stub.ts
  src/app/statistics/angulartics/dspace-provider.ts
  src/assets/i18n/en.json5
  src/config/app-config.interface.ts
  src/config/collection-page-config.interface.ts
  src/config/community-page-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
Labels: component: Discovery, high priority, new feature, 1 APPROVAL

#2818 site search should not adopt existing URL query string parameters
  src/app/search-navbar/search-navbar.component.spec.ts
  src/app/search-navbar/search-navbar.component.ts
Labels: bug, component: Discovery, 1 APPROVAL, port to dspace-7_x

#2480 Feature process polling
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.spec.ts
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.ts
  src/app/core/cache/builders/remote-data-build.service.ts
  src/app/core/data/base/base-data.service.spec.ts
  src/app/core/data/base/base-data.service.ts
  src/app/core/data/collection-data.service.spec.ts
  src/app/core/data/processes/process-data.service.spec.ts
  src/app/core/data/processes/process-data.service.ts
  src/app/core/data/relationship-data.service.spec.ts
  src/app/core/data/relationship-type-data.service.spec.ts
  src/app/core/notifications/qa/events/quality-assurance-event-data.service.spec.ts
  src/app/core/notifications/qa/source/quality-assurance-source-data.service.spec.ts
  src/app/core/notifications/qa/topics/quality-assurance-topic-data.service.spec.ts
  src/app/core/resource-policy/resource-policy-data.service.spec.ts
  src/app/core/submission/vocabularies/vocabulary.service.spec.ts
  src/app/core/supervision-order/supervision-order-data.service.spec.ts
  src/app/process-page/detail/process-detail.component.html
  src/app/process-page/detail/process-detail.component.spec.ts
  src/app/process-page/detail/process-detail.component.ts
  src/app/process-page/process-breadcrumb.resolver.ts
  src/app/process-page/process-breadcrumbs.service.ts
  src/app/process-page/process-page.resolver.ts
  src/app/process-page/processes/filetypes.model.ts
  src/app/process-page/processes/filetypes.resource-type.ts
  src/app/process-page/processes/process-status.model.ts
  src/app/process-page/processes/process.model.ts
  src/app/shared/testing/object-cache-service.stub.ts
  src/assets/i18n/en.json5
Labels: improvement, high priority, new feature, code task, 1 APPROVAL

#2756 Split processes overview page into sections
  src/app/collection-page/edit-collection-page/collection-source/collection-source-controls/collection-source-controls.component.ts
  src/app/core/data/processes/process-data.service.spec.ts
  src/app/core/data/processes/process-data.service.ts
  src/app/process-page/detail/process-detail.component.ts
  src/app/process-page/form/process-form.component.ts
  src/app/process-page/overview/process-overview.component.html
  src/app/process-page/overview/process-overview.component.spec.ts
  src/app/process-page/overview/process-overview.component.ts
  src/app/process-page/overview/process-overview.service.ts
  src/app/process-page/overview/table/process-overview-table.component.html
  src/app/process-page/overview/table/process-overview-table.component.scss
  src/app/process-page/overview/table/process-overview-table.component.spec.ts
  src/app/process-page/overview/table/process-overview-table.component.ts
  src/app/process-page/process-page-shared.module.ts
  src/app/process-page/processes/process.model.ts
  src/assets/i18n/en.json5
  src/styles/_custom_variables.scss
Labels: new feature, tools:processes

#2653 Implement vocabulary value selectors in item’s metadata edit form
  config/config.example.yml
  src/app/core/submission/vocabularies/vocabulary.data.service.spec.ts
  src/app/core/submission/vocabularies/vocabulary.data.service.ts
  src/app/core/submission/vocabularies/vocabulary.service.spec.ts
  src/app/core/submission/vocabularies/vocabulary.service.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-field-values/dso-edit-metadata-field-values.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-form.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata.component.html
  src/app/dso-shared/dso-shared.module.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/dynamic-vocabulary.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/onebox/dynamic-onebox.component.ts
  src/app/shared/form/directives/authority-confidence-state.directive.ts
  src/app/shared/testing/vocabulary-service.stub.ts
  src/assets/i18n/en.json5
  src/config/default-app-config.ts
  src/config/submission-config.interface.ts
  src/environments/environment.test.ts
Labels: new feature, component: Item, component: authority control

#2275 only add Display Search Facets to the Homepage
  config/config.example.yml
  src/app/collection-page/collection-page.component.html
  src/app/community-page/community-page.component.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.ts
  src/app/home-page/home-page.module.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/search/search-filters/search-filters.component.ts
  src/app/shared/search/search-sidebar/search-sidebar.component.html
  src/app/shared/search/search.component.html
  src/app/shared/search/search.module.ts
  src/app/shared/sidebar/sidebar-dropdown.component.html
  src/assets/i18n/en.json5
  src/config/default-app-config.ts
  src/config/homepage-config.interface.ts
  src/environments/environment.test.ts
Labels: component: Discovery, new feature, 1 APPROVAL

#2608 Advance search search page
  config/config.example.yml
  src/app/shared/search/advanced-search/advanced-search.component.html
  src/app/shared/search/advanced-search/advanced-search.component.scss
  src/app/shared/search/advanced-search/advanced-search.component.spec.ts
  src/app/shared/search/advanced-search/advanced-search.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/search/search-filters/search-filters.component.ts
  src/app/shared/search/search.module.ts
  src/app/shared/search/search.utils.ts
  src/assets/i18n/en.json5
  src/config/advance-search-config.interface.ts
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/search-page-config.interface.ts
  src/environments/environment.test.ts
Labels: component: Discovery, new feature

#2163 Content reports ported from DSpace 6.x
  src/app/admin/admin-reports/admin-reports-routing.module.ts
  src/app/admin/admin-reports/admin-reports.module.ts
  src/app/admin/admin-reports/filtered-collections/filtered-collection.model.ts
  src/app/admin/admin-reports/filtered-collections/filtered-collections.component.html
  src/app/admin/admin-reports/filtered-collections/filtered-collections.component.scss
  src/app/admin/admin-reports/filtered-collections/filtered-collections.component.spec.ts
  src/app/admin/admin-reports/filtered-collections/filtered-collections.component.ts
  src/app/admin/admin-reports/filtered-collections/filtered-collections.model.ts
  src/app/admin/admin-reports/filtered-items/filtered-items-model.ts
  src/app/admin/admin-reports/filtered-items/filtered-items.component.html
  src/app/admin/admin-reports/filtered-items/filtered-items.component.scss
  src/app/admin/admin-reports/filtered-items/filtered-items.component.spec.ts
  src/app/admin/admin-reports/filtered-items/filtered-items.component.ts
  src/app/admin/admin-reports/filtered-items/option-vo.model.ts
  src/app/admin/admin-reports/filtered-items/preset-query.model.ts
  src/app/admin/admin-reports/filtered-items/query-predicate.model.ts
  src/app/admin/admin-reports/filters-section/filter-group.model.ts
  src/app/admin/admin-reports/filters-section/filter.model.ts
  src/app/admin/admin-reports/filters-section/filters-section.component.html
  src/app/admin/admin-reports/filters-section/filters-section.component.scss
  src/app/admin/admin-reports/filters-section/filters-section.component.spec.ts
  src/app/admin/admin-reports/filters-section/filters-section.component.ts
  src/app/admin/admin-routing-paths.ts
  src/app/admin/admin-routing.module.ts
  src/app/admin/admin.module.ts
  src/app/menu.resolver.spec.ts
  src/app/menu.resolver.ts
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
Labels: new feature, component: administrative tools

#2840 Removed 250 and 1000 items/page options and set 10 as default value
  src/app/admin/admin-reports/filtered-items/filtered-items.component.ts
Labels: bug, 1 APPROVAL

#2356 Update dependencies for Node v20
  package.json
  yarn.lock
Labels: dependencies, quick win, code task, 1 APPROVAL, port to dspace-7_x
