Repository DSpace/dspace-angular, pull requests merged in 2024-09, with the labels that each got.

#3287 Provided label for cclicense required error
  src/assets/i18n/en.json5
Labels: improvement, 1 APPROVAL, integration: Creative Commons

#3289 Ignore some paths from file watcher
  webpack/webpack.browser.ts
Labels: 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3302 [Port dspace-7_x] Bump micromatch to 4.0.8
  yarn.lock
Labels: dependencies

#3011 Fixed page and admin menu for Shibboleth auth
  src/modules/app/browser-init.service.ts
Labels: bug, authentication: Shibboleth, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3306 [Port dspace-7_x] Fixed page and admin menu for Shibboleth auth
  src/modules/app/browser-init.service.ts
Labels: bug, authentication: Shibboleth, 1 APPROVAL

#3173 Use npm instead of Yarn
  .dockerignore
  .github/pull_request_template.md
  .github/workflows/build.yml
  .gitignore
  Dockerfile
  Dockerfile.dist
  README.md
  lint/src/util/structure.ts
  package-lock.json
  package.json
  yarn.lock
Labels: improvement, dependencies, high priority, needs documentation

#3171 Remove material-ui dependency
  package-lock.json
  package.json
Labels: dependencies

#3324 [Port dspace-8_x] Bump body-parser and express
  package.json
  yarn.lock
Labels: dependencies, port to dspace-7_x

#3326 [Port dspace-7_x] Bump Express to v4.20.0
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL

#3348 [Port dspace-8_x] updates isbot dependency to newest version
  package.json
  server.ts
  yarn.lock
Labels: dependencies

#3353 [Port dspace-8_x] Minor accessibility fixes
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
Labels: accessibility, 1 APPROVAL

#3352 [Port dspace-7_x] Minor accessibility fixes
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/shared/form/vocabulary-treeview/vocabulary-treeview.component.html
Labels: accessibility, 1 APPROVAL

#3149 missing German translations (500 error)
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x

#3175 minor change: added missing periods in German translations
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3354 [Port dspace-7_x] updates isbot dependency to newest version
  .github/workflows/build.yml
  package.json
  server.ts
  yarn.lock
Labels: dependencies, needs documentation

#3340 DS-3330: Updated en.json5 to fixed typo for 'occurred'
  src/assets/i18n/en.json5
Labels: i18n / l10n, port to dspace-7_x, port to dspace-8_x

#3153 Fix to Mobile navbar hamburger menu for base (custom) theme
  src/app/navbar/navbar.component.scss
Labels: bug, accessibility, usability, 1 APPROVAL, ux, port to dspace-7_x, port to dspace-8_x

#3337 Live Region
  config/config.example.yml
  src/app/root/root.component.html
  src/app/root/root.component.ts
  src/app/shared/live-region/live-region.component.html
  src/app/shared/live-region/live-region.component.scss
  src/app/shared/live-region/live-region.component.spec.ts
  src/app/shared/live-region/live-region.component.ts
  src/app/shared/live-region/live-region.config.ts
  src/app/shared/live-region/live-region.service.spec.ts
  src/app/shared/live-region/live-region.service.ts
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
  src/styles/_custom_variables.scss
  src/themes/custom/app/root/root.component.ts
Labels: accessibility, high priority, port to dspace-7_x, port to dspace-8_x

#3370 [Port dspace-8_x] Live region
  config/config.example.yml
  src/app/root/root.component.html
  src/app/root/root.component.ts
  src/app/shared/live-region/live-region.component.html
  src/app/shared/live-region/live-region.component.scss
  src/app/shared/live-region/live-region.component.spec.ts
  src/app/shared/live-region/live-region.component.ts
  src/app/shared/live-region/live-region.config.ts
  src/app/shared/live-region/live-region.service.spec.ts
  src/app/shared/live-region/live-region.service.ts
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
  src/styles/_custom_variables.scss
  src/themes/custom/app/root/root.component.ts
Labels: accessibility, high priority

#3371 [Port dspace-7_x] Live region
  config/config.example.yml
  src/app/root/root.component.html
  src/app/shared/live-region/live-region.component.html
  src/app/shared/live-region/live-region.component.scss
  src/app/shared/live-region/live-region.component.spec.ts
  src/app/shared/live-region/live-region.component.ts
  src/app/shared/live-region/live-region.config.ts
  src/app/shared/live-region/live-region.service.spec.ts
  src/app/shared/live-region/live-region.service.ts
  src/app/shared/shared.module.ts
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/environments/environment.test.ts
  src/styles/_custom_variables.scss
Labels: accessibility, high priority
