Repository DSpace/dspace-angular, pull requests merged in 2025-02, with the labels that each got.

#3935 Ensure `/reload/` (hard reload) path is included in SSR paths.
  config/config.example.yml
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: bug, high priority, performance / caching, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3948 Avoid retrieving user suggestions if Researcher profiles are disabled
  src/app/notifications/suggestion-targets/suggestion-targets.effects.ts
Labels: bug, high priority, component: user profile, error handling, 1 APPROVAL, port to dspace-8_x

#3358 Provide a setting to use a different REST url during SSR execution
  config/config.example.yml
  server.ts
  src/app/app.config.ts
  src/app/core/dspace-rest/dspace-rest.interceptor.spec.ts
  src/app/core/dspace-rest/dspace-rest.interceptor.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/shared/utils/safe-url-pipe.ts
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
  src/config/config.server.ts
  src/config/server-config.interface.ts
  src/config/ssr-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/modules/app/browser-init.service.ts
  src/modules/app/server-init.service.ts
Labels: high priority, performance / caching

#3953 [Port dspace-8_x] Provide a setting to use a different REST url during SSR execution
  config/config.example.yml
  server.ts
  src/app/app.config.ts
  src/app/core/dspace-rest/dspace-rest.interceptor.spec.ts
  src/app/core/dspace-rest/dspace-rest.interceptor.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/shared/utils/safe-url-pipe.ts
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
  src/config/config.server.ts
  src/config/server-config.interface.ts
  src/config/ssr-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/modules/app/browser-init.service.ts
  src/modules/app/server-init.service.ts
Labels: high priority, performance / caching

#3797 Update catalan translation
  src/assets/i18n/ca.json5
Labels: i18n / l10n, 1 APPROVAL

#2827 use translation service to determine placeholder values of date picker
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.ts
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, component: submission, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3964 [Port dspace-8_x] use translation service to determine placeholder values of date picker
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.ts
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, component: submission, 1 APPROVAL

#3965 [Port dspace-7_x] use translation service to determine placeholder values of date picker
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.ts
  src/assets/i18n/de.json5
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, component: submission, 1 APPROVAL

#3962 [Port dspace-7_x] Provide a setting to use a different REST url during SSR execution
  config/config.example.yml
  server.ts
  src/app/app.module.ts
  src/app/core/dspace-rest/dspace-rest.interceptor.spec.ts
  src/app/core/dspace-rest/dspace-rest.interceptor.ts
  src/app/core/services/server-hard-redirect.service.spec.ts
  src/app/core/services/server-hard-redirect.service.ts
  src/app/shared/utils/safe-url-pipe.ts
  src/app/thumbnail/thumbnail.component.spec.ts
  src/app/thumbnail/thumbnail.component.ts
  src/config/config.server.ts
  src/config/server-config.interface.ts
  src/config/universal-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/modules/app/browser-init.service.ts
  src/modules/app/server-init.service.ts
Labels: high priority, performance / caching

#3966 Move `enablePerformanceProfiler` option to last in list in `config.example.yml`
  config/config.example.yml
Labels: configuration, code task, 1 APPROVAL, port to dspace-8_x

#3976 Added missing line to enable access to Content Reports
  src/app/menu-resolver.service.ts
Labels: bug, high priority, component: administrative tools, 1 APPROVAL, component: admin reports, port to dspace-8_x

#3960 Update fr.json5 to add identifiers deposit's step translations in french
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3673 Update fr.json5
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to main, port to dspace-7_x

#4020 Changes to fr.json5 following version 8.1
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3786 translation keys for datacite project import
  src/assets/i18n/en.json5
Labels: identifiers: DOIs, new feature, 1 APPROVAL, tools:import-sources
