Repository DSpace/dspace-angular, pull requests merged in 2025-01, with the labels that each got.

#3718 fix selector in OrgUnitSearchResultListSubmissionElementComponent compontent
  src/app/entity-groups/research-entities/submission/item-list-elements/org-unit/org-unit-search-result-list-submission-element.component.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3737 Fixes typo for 'descrption'
  src/assets/i18n/en.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3724 Fixed dropdown/lookup & lookup-name fields being reset when hitting enter
  src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/form.service.ts
Labels: bug, component: submission, component: controlled vocabulary, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3792 README.md: update Node.js and NPM versions
  README.md
Labels: 1 APPROVAL, documentation

#3793 [Port dspace-8_x] README.md: update Node.js and NPM versions
  README.md
Labels: 1 APPROVAL, documentation

#3192 Spanish translation keys
  src/assets/i18n/es.json5
Labels: bug, i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3801 [Port dspace-8_x] Spanish translation keys
  src/assets/i18n/es.json5
Labels: bug, i18n / l10n, 1 APPROVAL

#3772 add German translation of process view related keys
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#3142 Add support for non repeatable relationships
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
Labels: bug, component: configurable entities, 1 APPROVAL, port to dspace-8_x

#3143 [Port dspace-7_x] Add support for non repeatable relationships
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.spec.ts
  src/app/item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts
Labels: bug, component: configurable entities, 1 APPROVAL

#3796 [Port dspace-8_x] Fixed dropdown/lookup & lookup-name fields being reset when hitting enter
  src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/form.service.ts
Labels: bug, component: submission, component: controlled vocabulary, 1 APPROVAL

#3795 [Port dspace-7_x] Fixed dropdown/lookup & lookup-name fields being reset when hitting enter
  src/app/shared/form/builder/ds-dynamic-form-ui/models/lookup/dynamic-lookup.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/form.service.ts
Labels: bug, component: submission, component: controlled vocabulary, 1 APPROVAL

#3701 Reduce browse definition requests on simple item page
  src/app/core/shared/browse-definition.model.ts
  src/app/core/shared/hierarchical-browse-definition.model.ts
  src/app/core/shared/non-hierarchical-browse-definition.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/img/item-page-img-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts
  src/app/shared/testing/browse-service.stub.ts
Labels: high priority, performance / caching, port to dspace-7_x, port to dspace-8_x

#3812 [Port dspace-7_x] Reduce browse definition requests on simple item page (#3701)
  src/app/core/shared/browse-definition.model.ts
  src/app/core/shared/hierarchical-browse-definition.model.ts
  src/app/core/shared/non-hierarchical-browse-definition.ts
  src/app/entity-groups/journal-entities/item-pages/journal/journal.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts
  src/app/item-page/simple/item-types/publication/publication.component.spec.ts
  src/app/item-page/simple/item-types/shared/item.component.spec.ts
  src/app/item-page/simple/item-types/untyped-item/untyped-item.component.spec.ts
  src/app/shared/testing/browse-service.stub.ts
Labels: bug, high priority, performance / caching

#3811 [Port dspace-8_x] Reduce browse definition requests on simple item page (#3701)
  src/app/core/shared/browse-definition.model.ts
  src/app/core/shared/hierarchical-browse-definition.model.ts
  src/app/core/shared/non-hierarchical-browse-definition.ts
  src/app/item-page/simple/field-components/specific-field/abstract/item-page-abstract-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/author/item-page-author-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/date/item-page-date-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/generic/generic-item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/img/item-page-img-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.spec.ts
  src/app/item-page/simple/field-components/specific-field/item-page-field.component.ts
  src/app/item-page/simple/field-components/specific-field/uri/item-page-uri-field.component.spec.ts
  src/app/shared/testing/browse-service.stub.ts
Labels: bug, high priority, performance / caching

#3814 Update spanish translation
  src/assets/i18n/es.json5
Labels: i18n / l10n, 1 APPROVAL

#3815 [Port dspace-8_x] Update spanish translation
  src/assets/i18n/es.json5
Labels: i18n / l10n, 1 APPROVAL

#3816 [Port dspace-8_x] Update catalan translation
  src/assets/i18n/ca.json5
Labels: i18n / l10n, 1 APPROVAL

#3608 Add button to allow free-text editing in the dropdown field of Edit Item
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.html
  src/app/dso-shared/dso-edit-metadata/dso-edit-metadata-value/dso-edit-metadata-value.component.ts
  src/assets/i18n/en.json5
Labels: bug, improvement, component: submission, 1 APPROVAL, component: Item, port to dspace-8_x

#3096 Change - Metadata field selector, add infinite scroll for data paginated
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.html
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.scss
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
Labels: bug, 1 APPROVAL, component: Item, ux, port to dspace-7_x, port to dspace-8_x

#3105 Fix for User profile (/profile): only 20 group memberships shown instead of all
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
  src/assets/i18n/en.json5
  src/themes/custom/app/profile-page/profile-page.component.ts
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3824 [Port dspace-7_x] Change - Metadata field selector, add infinite scroll for data paginated
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.html
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.scss
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
Labels: bug, 1 APPROVAL, component: Item, ux

#3823 [Port dspace-8_x] Change - Metadata field selector, add infinite scroll for data paginated
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.html
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.scss
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.spec.ts
  src/app/dso-shared/dso-edit-metadata/metadata-field-selector/metadata-field-selector.component.ts
Labels: bug, 1 APPROVAL, component: Item, ux

#3826 [Port dspace-7_x] Fix for User profile (/profile): only 20 group memberships shown instead of all
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.ts
  src/assets/i18n/en.json5
Labels: bug, component: user profile, 1 APPROVAL

#3825 [Port dspace-8_x] Fix for User profile (/profile): only 20 group memberships shown instead of all
  src/app/profile-page/profile-page.component.html
  src/app/profile-page/profile-page.component.spec.ts
  src/app/profile-page/profile-page.component.ts
  src/assets/i18n/en.json5
  src/themes/custom/app/profile-page/profile-page.component.ts
Labels: bug, component: user profile, 1 APPROVAL

#3842 Attempt to stabilize a few randomly failing e2e tests
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
  cypress/e2e/item-edit.cy.ts
Labels: bug, 1 APPROVAL, testing framework, port to dspace-7_x, port to dspace-8_x

#3843 [Port dspace-8_x] Attempt to stabilize a few randomly failing e2e tests
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
  cypress/e2e/item-edit.cy.ts
Labels: 1 APPROVAL, testing framework

#3844 [Port dspace-7_x] Attempt to stabilize a few randomly failing e2e tests
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
  cypress/e2e/item-edit.cy.ts
Labels: 1 APPROVAL, testing framework

#3845 Fix issue where scoped browse by would not inititialze correct component
  src/app/shared/comcol/sections/comcol-browse-by/comcol-browse-by.component.ts
Labels: bug, component: Discovery, high priority, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3872 SCSS cleanup: remove duplicated line
  src/styles/_bootstrap_variables_mapping.scss
Labels: code task, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3682 Restrict Angular SSR to paths in the sitemap
  config/config.example.yml
  server.ts
  src/config/ssr-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: bug, high priority, performance / caching, port to dspace-7_x, port to dspace-8_x

#3875 Stabilize e2e tests that use admin sidebar menu
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
Labels: work in progress, 1 APPROVAL, testing framework, port to main, port to dspace-7_x

#3879 [Post dspace-7_x] Restrict Angular SSR to paths in the sitemap
  config/config.example.yml
  server.ts
  src/config/universal-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: bug, high priority, performance / caching

#3883 [Port main] Stabilize e2e tests that use admin sidebar menu
  cypress/e2e/admin-add-new-modals.cy.ts
  cypress/e2e/admin-edit-modals.cy.ts
  cypress/e2e/admin-export-modals.cy.ts
Labels: 1 APPROVAL, testing framework

#3345 [Port dspace-8_x] Add orcid icon with tooltip
  src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.html
  src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.ts
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.html
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.scss
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.spec.ts
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.ts
  src/assets/i18n/en.json5
Labels: identifiers: ORCID, integration: ORCID

#3346 [Port dspace-7_x] Add orcid icon with tooltip
  src/app/entity-groups/research-entities/metadata-representations/person/person-item-metadata-list-element.component.html
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.html
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.scss
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.spec.ts
  src/app/shared/orcid-badge-and-tooltip/orcid-badge-and-tooltip.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/en.json5
Labels: identifiers: ORCID, integration: ORCID

#3876 Fix redirect URLs of bitstreams with spaces in filename
  src/app/core/data/bitstream-data.service.spec.ts
  src/app/core/data/bitstream-data.service.ts
Labels: bug, component: SEO, 1 APPROVAL, port to main, port to dspace-8_x

#3884 [Port main] Fix redirect URLs of bitstreams with spaces in filename (new test ONLY)
  src/app/core/data/bitstream-data.service.spec.ts
Labels: 1 APPROVAL, testing framework

#3885 [Port dspace-8_x] Fix redirect URLs of bitstreams with spaces in filename (new test ONLY)
  src/app/core/data/bitstream-data.service.spec.ts
Labels: 1 APPROVAL, testing framework

#3709 Exclude search and browse from Angular SSR
  config/config.example.yml
  package.json
  src/app/browse-by/browse-by-date/browse-by-date.component.spec.ts
  src/app/browse-by/browse-by-date/browse-by-date.component.ts
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.html
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.spec.ts
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.ts
  src/app/browse-by/browse-by-title/browse-by-title.component.spec.ts
  src/app/browse-by/browse-by-title/browse-by-title.component.ts
  src/app/search-page/configuration-search-page.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.scss
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/search/search-filters/search-filters.component.ts
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.html
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.scss
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.spec.ts
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.ts
  src/app/shared/search/search-results/search-results.component.html
  src/app/shared/search/search-results/search-results.component.scss
  src/app/shared/search/search-results/search-results.component.spec.ts
  src/app/shared/search/search-results/search-results.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/testing/search-configuration-service.stub.ts
  src/config/default-app-config.ts
  src/config/search-page-config.interface.ts
  src/config/ssr-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/styles/_custom_variables.scss
  src/themes/custom/app/shared/search/search-filters/search-filters.component.ts
  src/themes/custom/app/shared/search/search-results/search-results.component.ts
  src/themes/custom/lazy-theme.module.ts
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
  yarn.lock
Labels: high priority, performance / caching, 1 APPROVAL, port to main, port to dspace-7_x

#3886 [Port main] Exclude search and browse from Angular SSR (#3709)
  config/config.example.yml
  package-lock.json
  package.json
  src/app/browse-by/browse-by-date/browse-by-date.component.spec.ts
  src/app/browse-by/browse-by-date/browse-by-date.component.ts
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.html
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.spec.ts
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.ts
  src/app/browse-by/browse-by-title/browse-by-title.component.spec.ts
  src/app/browse-by/browse-by-title/browse-by-title.component.ts
  src/app/search-page/configuration-search-page.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.scss
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/search/search-filters/search-filters.component.ts
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.html
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.scss
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.spec.ts
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.ts
  src/app/shared/search/search-results/search-results.component.html
  src/app/shared/search/search-results/search-results.component.scss
  src/app/shared/search/search-results/search-results.component.spec.ts
  src/app/shared/search/search-results/search-results.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/testing/search-configuration-service.stub.ts
  src/config/default-app-config.ts
  src/config/search-page-config.interface.ts
  src/config/ssr-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/styles/_custom_variables.scss
  src/themes/custom/app/shared/search/search-filters/search-filters.component.ts
  src/themes/custom/app/shared/search/search-results/search-results.component.ts
  src/themes/custom/lazy-theme.module.ts
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
Labels: high priority, performance / caching, 1 APPROVAL

#3694 Prevent request with page size of 9999
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/data/bundle-data.service.ts
  src/app/core/metadata/head-tag.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/process-page/form/scripts-select/scripts-select.component.html
  src/app/process-page/form/scripts-select/scripts-select.component.scss
  src/app/process-page/form/scripts-select/scripts-select.component.spec.ts
  src/app/process-page/form/scripts-select/scripts-select.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.model.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.scss
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts
  src/assets/i18n/en.json5
Labels: bug, high priority, performance / caching, code task, claimed: 4Science, port to dspace-7_x, port to dspace-8_x

#3887 [Port dspace-8_x] Prevent request with page size of 9999 (#3694)
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/data/bundle-data.service.ts
  src/app/core/metadata/head-tag.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/process-page/form/scripts-select/scripts-select.component.html
  src/app/process-page/form/scripts-select/scripts-select.component.scss
  src/app/process-page/form/scripts-select/scripts-select.component.spec.ts
  src/app/process-page/form/scripts-select/scripts-select.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.model.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.scss
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts
  src/assets/i18n/en.json5
Labels: bug, high priority, performance / caching, code task

#3880 Improving the color contrast of home news content
  src/themes/dspace/app/home-page/home-news/home-news.component.scss
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
  src/themes/dspace/styles/_theme_sass_variable_overrides.scss
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3413 Improve descriptive labels for show/hide x more buttons for related items (Item/Entity Homepage)
  src/app/item-page/simple/related-items/related-items.component.html
Labels: bug, accessibility, 1 APPROVAL, component: Item, port to dspace-7_x, port to dspace-8_x

#3212 Fix truncatable-part keyboard accessibility
  src/app/shared/truncatable/truncatable-part/truncatable-part.component.html
  src/app/shared/truncatable/truncatable-part/truncatable-part.component.spec.ts
  src/app/shared/truncatable/truncatable-part/truncatable-part.component.ts
Labels: bug, accessibility, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3895 Bump cross-spawn from 7.0.3 to 7.0.6
  yarn.lock
Labels: dependencies

#3894 Bump cross-spawn from 7.0.3 to 7.0.6
  yarn.lock
Labels: dependencies

#3898 Bump cross-spawn from 7.0.3 to 7.0.6
  package-lock.json
Labels: dependencies

#3907 [Port dspace-7_x] Exclude search and browse from Angular SSR
  config/config.example.yml
  package.json
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.spec.ts
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.html
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.spec.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.spec.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
  src/app/search-page/configuration-search-page.component.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.scss
  src/app/shared/search/search-filters/search-filters.component.spec.ts
  src/app/shared/search/search-filters/search-filters.component.ts
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.html
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.scss
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.spec.ts
  src/app/shared/search/search-results/search-results-skeleton/search-results-skeleton.component.ts
  src/app/shared/search/search-results/search-results.component.html
  src/app/shared/search/search-results/search-results.component.scss
  src/app/shared/search/search-results/search-results.component.spec.ts
  src/app/shared/search/search-results/search-results.component.ts
  src/app/shared/search/search.component.spec.ts
  src/app/shared/search/search.component.ts
  src/app/shared/search/search.module.ts
  src/app/shared/testing/search-configuration-service.stub.ts
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/search-page-config.interface.ts
  src/config/universal-config.interface.ts
  src/environments/environment.production.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/styles/_custom_variables.scss
  src/themes/custom/lazy-theme.module.ts
  src/themes/dspace/styles/_theme_css_variable_overrides.scss
  yarn.lock
Labels: high priority, performance / caching, 1 APPROVAL

#3846 Browse performance fixes
  src/app/browse-by/browse-by-date/browse-by-date.component.ts
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.ts
  src/app/browse-by/browse-by-title/browse-by-title.component.ts
  src/app/core/data/base/base-data.service.ts
Labels: component: Discovery, high priority, performance / caching, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3916 [Port dspace-7_x] Changing metadata in a user profile without specifying a password brings up a success and an error panel
  src/app/profile-page/profile-page.component.ts
Labels: bug, component: user profile, 1 APPROVAL

#3914 [Port dspace-8_x] Browse performance fixes
  src/app/browse-by/browse-by-date/browse-by-date.component.ts
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.ts
  src/app/browse-by/browse-by-title/browse-by-title.component.ts
  src/app/core/data/base/base-data.service.ts
Labels: component: Discovery, high priority, performance / caching, 1 APPROVAL

#3913 [Port dspace-7_x] Browse performance fixes
  src/app/browse-by/browse-by-date-page/browse-by-date-page.component.ts
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/browse-by/browse-by-title-page/browse-by-title-page.component.ts
  src/app/core/data/base/base-data.service.ts
Labels: component: Discovery, high priority, performance / caching, 1 APPROVAL

#3385 Accessibility when selecting a search filter
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, component: Discovery, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3918 [Port dspace-8_x] Accessibility when selecting a search filter
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, component: Discovery, 1 APPROVAL

#3581 Made expandable navbar section more keyboard accessible
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
  src/app/shared/menu/menu-section/menu-section.component.ts
  src/app/shared/utils/hover-outside.directive.ts
  src/themes/custom/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
Labels: bug, accessibility, claimed: Atmire, port to dspace-7_x, port to dspace-8_x, funded

#3920 Fix YAML syntax in config.example.yml
  config/config.example.yml
Labels: configuration, 1 APPROVAL, port to dspace-8_x

#3921 [Port dspace-7_x] Fix YAML syntax and revert section name to "universal"
  config/config.example.yml
Labels: configuration, 1 APPROVAL

#3372 Make reorder buttons keyboard accessible
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.ts
  src/assets/i18n/en.json5
Labels: bug, accessibility, high priority, port to dspace-7_x, port to dspace-8_x, funded

#3927 [Port dspace-8_x] Make submission reorder buttons keyboard accessible
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.ts
  src/assets/i18n/en.json5
Labels: bug, accessibility, component: submission, high priority

#3924 [Port dspace-7_x] Made expandable navbar section more keyboard accessible
  src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.html
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.spec.ts
  src/app/navbar/expandable-navbar-section/expandable-navbar-section.component.ts
  src/app/navbar/navbar.module.ts
  src/app/shared/menu/menu-section/menu-section.component.ts
  src/app/shared/utils/hover-outside.directive.ts
Labels: bug, accessibility, claimed: Atmire, funded

#3925 [Port dspace-7_x] Prevent request with page size of 9999
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.spec.ts
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/core/data/bundle-data.service.ts
  src/app/core/data/relationship-type-data.service.ts
  src/app/core/metadata/metadata.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
  src/app/process-page/form/scripts-select/scripts-select.component.html
  src/app/process-page/form/scripts-select/scripts-select.component.scss
  src/app/process-page/form/scripts-select/scripts-select.component.spec.ts
  src/app/process-page/form/scripts-select/scripts-select.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.component.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/scrollable-dropdown/dynamic-scrollable-dropdown.model.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.spec.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.scss
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.spec.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts
  src/assets/i18n/en.json5
Labels: bug, high priority, performance / caching, code task

#3912 Fix auth in UI with LDAP if password authentication is disabled
  src/app/core/auth/auth.interceptor.ts
Labels: bug, high priority, authentication: LDAP, authentication: password, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3926 [Port dspace-7_x] Accessibility when selecting a search filter
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.html
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.spec.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.ts
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/pt-BR.json5
Labels: bug, accessibility, component: Discovery, 1 APPROVAL
