Repository DSpace/dspace-angular, pull requests merged in 2025-06, with the labels that each got.

#4424 .github/dependabot.yml: adjust rules for zone.js
  .github/dependabot.yml
Labels: dependencies, 1 APPROVAL

#4423 Pin zone.js dependency for DSpace 8.x
  package.json
  yarn.lock
Labels: dependencies, 1 APPROVAL

#4434 Resolve field instance models using index when filtering errors
  src/app/shared/form/form.component.ts
Labels: bug, quick win, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x, port to dspace-9_x

#4389 Confirmation dialog before deleting Group
  src/app/access-control/group-registry/groups-registry.component.html
  src/app/access-control/group-registry/groups-registry.component.spec.ts
  src/app/access-control/group-registry/groups-registry.component.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.html
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.spec.ts
  src/app/shared/comcol/comcol-forms/edit-comcol-page/comcol-role/comcol-role.component.ts
  src/app/shared/confirmation-modal/confirmation-modal.component.scss
  src/app/shared/confirmation-modal/confirmation-modal.component.ts
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: bug, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x, port to dspace-9_x

#4440 [Port dspace-8_x] Removed observable function calls from template (part 2)
  src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.html
  src/app/admin/admin-registries/metadata-schema/metadata-field-form/metadata-field-form.component.ts
  src/app/item-page/edit-item-page/item-authorizations/item-authorizations.component.html
  src/app/item-page/edit-item-page/item-authorizations/item-authorizations.component.spec.ts
  src/app/item-page/edit-item-page/item-authorizations/item-authorizations.component.ts
  src/app/item-page/orcid-page/orcid-auth/orcid-auth.component.html
  src/app/item-page/orcid-page/orcid-auth/orcid-auth.component.ts
  src/app/item-page/orcid-page/orcid-queue/orcid-queue.component.html
  src/app/item-page/orcid-page/orcid-queue/orcid-queue.component.ts
  src/app/navbar/navbar.component.html
  src/app/process-page/overview/process-overview.component.html
  src/app/process-page/overview/process-overview.component.ts
  src/app/profile-page/profile-page-researcher-form/profile-page-researcher-form.component.html
  src/app/profile-page/profile-page-researcher-form/profile-page-researcher-form.component.ts
  src/app/register-email-form/register-email-form.component.html
  src/app/register-email-form/register-email-form.component.ts
  src/app/shared/eperson-group-list/eperson-group-list.component.html
  src/app/shared/eperson-group-list/eperson-group-list.component.spec.ts
  src/app/shared/eperson-group-list/eperson-group-list.component.ts
  src/app/shared/host-window.service.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/pagination/pagination.component.ts
  src/app/shared/resource-policies/create/resource-policy-create.component.html
  src/app/shared/theme-support/themed.component.ts
  src/app/submission/form/section-add/submission-form-section-add.component.html
  src/app/submission/form/section-add/submission-form-section-add.component.ts
  src/app/submission/form/submission-form.component.html
  src/app/submission/form/submission-form.component.spec.ts
  src/app/submission/form/submission-form.component.ts
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
  src/app/submission/sections/cc-license/submission-section-cc-licenses.component.ts
  src/app/submission/sections/identifiers/section-identifiers.component.html
  src/app/submission/sections/identifiers/section-identifiers.component.ts
Labels: bug, performance / caching

#4291 Improve community list e2e tests
  cypress/e2e/community-list.cy.ts
  src/app/community-list-page/community-list/community-list.component.html
Labels: 1 APPROVAL, testing framework, port to dspace-7_x, port to dspace-8_x, port to dspace-9_x

#3615 [Port dspace-7_x] Accessibility settings page
  .github/workflows/build.yml
  config/config.example.yml
  src/app/accessibility/accessibility-settings.config.ts
  src/app/accessibility/accessibility-settings.service.spec.ts
  src/app/accessibility/accessibility-settings.service.stub.ts
  src/app/accessibility/accessibility-settings.service.ts
  src/app/core/auth/auth.service.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/info/accessibility-settings/accessibility-settings.component.html
  src/app/info/accessibility-settings/accessibility-settings.component.spec.ts
  src/app/info/accessibility-settings/accessibility-settings.component.ts
  src/app/info/info-routing-paths.ts
  src/app/info/info-routing.module.ts
  src/app/info/info.module.ts
  src/app/profile-page/profile-page.component.html
  src/app/shared/cookies/browser-klaro.service.ts
  src/app/shared/cookies/klaro-configuration.ts
  src/app/shared/cookies/klaro.service.stub.ts
  src/app/shared/form/builder/ds-dynamic-form-ui/models/array-group/dynamic-form-array.component.spec.ts
  src/app/shared/live-region/live-region.service.spec.ts
  src/app/shared/live-region/live-region.service.ts
  src/app/shared/notifications/notifications-board/notifications-board.component.spec.ts
  src/app/shared/notifications/notifications-board/notifications-board.component.ts
  src/app/shared/search/search-filters/search-filter/search-facet-filter-options/search-facet-option/search-facet-option.component.spec.ts
  src/app/shared/testing/auth-service.stub.ts
  src/assets/i18n/en.json5
  src/config/app-config.interface.ts
  src/config/default-app-config.ts
  src/config/info-config.interface.ts
  src/environments/environment.test.ts
Labels: bug, accessibility

#4371 Improve Hungarian translations in DSpace 8.1
  src/assets/i18n/hu.json5
Labels: i18n / l10n, 1 APPROVAL

#4518 [Port main] Improve Hungarian translations in DSpace 9.0
  src/assets/i18n/hu.json5
Labels: i18n / l10n, 1 APPROVAL
