Repository DSpace/dspace-angular, pull requests merged in 2025-09, with the labels that each got.

#4628 Fix untranslated i18n keys ror api
  src/assets/i18n/en.json5
  src/assets/i18n/pt-BR.json5
Labels: 1 APPROVAL, tools:import-sources, port to dspace-8_x, port to dspace-9_x

#2734 Clear url parameters for entity search tabs
  src/app/browse-by/browse-by-metadata/browse-by-metadata.component.ts
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.spec.ts
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.ts
  src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html
  src/app/shared/starts-with/date/starts-with-date.component.spec.ts
  src/app/shared/starts-with/starts-with-abstract.component.ts
  src/app/shared/starts-with/text/starts-with-text.component.spec.ts
Labels: bug, 1 APPROVAL, port to dspace-8_x, port to dspace-9_x

#2735 7.x - Clear url parameters for entity search tabs
  src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.spec.ts
  src/app/item-page/simple/related-entities/tabbed-related-entities-search/tabbed-related-entities-search.component.ts
  src/app/shared/object-list/browse-entry-list-element/browse-entry-list-element.component.html
  src/app/shared/starts-with/date/starts-with-date.component.spec.ts
  src/app/shared/starts-with/starts-with-abstract.component.ts
  src/app/shared/starts-with/text/starts-with-text.component.spec.ts
Labels: bug, 1 APPROVAL, affects: 7.x

#4677 [Port dspace-9_x] Fix: Remove HTML tags from cookie popup translations
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
Labels: bug, usability, 1 APPROVAL

#4180 [Port dspace-7_x] Clean up spacing in input forms
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.scss
Labels: component: submission, 1 APPROVAL, port to dspace-8_x

#4636 src/themes/dspace: rework banner image
  src/themes/dspace/assets/images/banner-half.jpg
  src/themes/dspace/assets/images/banner-half.webp
  src/themes/dspace/assets/images/banner.jpg
  src/themes/dspace/assets/images/banner.webp
Labels: performance / caching, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x, port to dspace-9_x

#4713 [Port dspace-8_x] Clean up spacing in input forms
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.scss
Labels: component: submission, 1 APPROVAL

#4369 Fix back button behavior on roles page
  src/app/access-control/group-registry/group-form/group-form.component.spec.ts
  src/app/access-control/group-registry/group-form/group-form.component.ts
Labels: bug, usability, 1 APPROVAL, port to main, port to dspace-8_x, port to dspace-9_x

#4728 src/app: use correct icon in item mapper
  src/app/shared/object-select/collection-select/collection-select.component.html
Labels: high priority, quick win, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x, port to dspace-9_x
