Repository DSpace/dspace-angular, pull requests merged in 2025-04, with the labels that each got.

#3982 No platform specific code in abstract services 8_x
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/server-auth.service.ts
  src/app/core/services/cookie.service.ts
  src/app/core/services/server-cookie.service.ts
Labels: bug, 1 APPROVAL

#3983 No platform specific code in abstract services 7_x
  src/app/core/auth/auth.service.spec.ts
  src/app/core/auth/auth.service.ts
  src/app/core/auth/server-auth.service.ts
  src/app/core/services/cookie.service.ts
  src/app/core/services/server-cookie.service.ts
Labels: bug, 1 APPROVAL

#4125 [DURACOM-339] fix downloads not working when matomo is disabled
  src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.spec.ts
  src/app/bitstream-page/bitstream-download-page/bitstream-download-page.component.ts
  src/app/shared/cookies/browser-orejime.service.ts
  src/app/statistics/matomo.service.ts
Labels: bug, high priority, 1 APPROVAL

#4129 Add note with link to Release Notes on homepage (for Testathon)
  src/themes/dspace/app/home-page/home-news/home-news.component.html
Labels: code task, 1 APPROVAL

#4130 [Port dspace-8_x] Add note with link to Release Notes on homepage
  src/themes/dspace/app/home-page/home-news/home-news.component.html
Labels: code task, 1 APPROVAL

#4134 Request-a-copy: Show correct preview link
  src/app/app-routing-paths.ts
  src/app/request-copy/grant-request-copy/grant-request-copy.component.ts
Labels: bug, 1 APPROVAL

#4075 Adding missing french labels
  src/assets/i18n/fr.json5
Labels: i18n / l10n, 1 APPROVAL, port to dspace-8_x

#4136 Clean up spacing in input forms
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.scss
  src/app/shared/form/builder/ds-dynamic-form-ui/existing-metadata-list-element/existing-metadata-list-element.component.html
  src/app/shared/form/builder/ds-dynamic-form-ui/models/date-picker/date-picker.component.scss
Labels: component: submission, 1 APPROVAL

#4138 Added the DSO menus back to the comcol search tabs
  src/app/collection-page/collection-page-routes.ts
  src/app/community-page/community-page-routes.ts
Labels: bug, component: Community, component: Collection, testathon

#4098 Update dependencies to use versions supporting ES modules
  package-lock.json
  package.json
  src/app/shared/utils/file-size-pipe.ts
Labels: dependencies, performance / caching, code task

#4161 Fix ssr error by only importing altcha on the client side
  src/app/item-page/bitstreams/request-a-copy/bitstream-request-a-copy-page.component.html
  src/app/item-page/bitstreams/request-a-copy/bitstream-request-a-copy-page.component.ts
  src/app/request-copy/email-request-copy/email-request-copy.component.ts
  src/modules/app/browser-app.config.ts
Labels: bug, component: SEO, high priority, 1 APPROVAL, testathon, affects: main

#4163 Ensure all i18n files are up to date with the english version
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: i18n / l10n

#4164 Wrap long bitstream filenames
  src/app/bitstream-page/edit-bitstream-page/edit-bitstream-page.component.html
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.html
Labels: bug, 1 APPROVAL, component: Item, testathon

#4160 [Port main] Store the state of the computed filters
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.ts
Labels: bug, high priority, 1 APPROVAL

#4121 Store the state of the computed filters
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.ts
Labels: bug, high priority, port to dspace-8_x

#4175 trivial change: fixed typo in description of trackSearch method
  src/app/core/shared/search/search.service.ts
Labels: code task, 1 APPROVAL

#4174 Fix issue where required cookies are removed by orejime
  src/app/shared/cookies/orejime-configuration.ts
Labels: bug, i18n / l10n, high priority, 1 APPROVAL, testathon

#4143 Fix pagination on the "Select bitstreams" modal of the "Access Control" tab
  src/app/shared/access-control-form-container/item-access-control-select-bitstreams-modal/item-access-control-select-bitstreams-modal.component.html
  src/app/shared/access-control-form-container/item-access-control-select-bitstreams-modal/item-access-control-select-bitstreams-modal.component.spec.ts
  src/app/shared/access-control-form-container/item-access-control-select-bitstreams-modal/item-access-control-select-bitstreams-modal.component.ts
Labels: bug, component: Item, claimed: Atmire, port to dspace-7_x, port to dspace-8_x

#4168 Fix export button enabled in bulk access management without selecting step 2
  src/app/access-control/bulk-access/bulk-access.component.spec.ts
  src/app/access-control/bulk-access/bulk-access.component.ts
  src/app/access-control/bulk-access/settings/bulk-access-settings.component.ts
  src/app/shared/access-control-form-container/access-control-array-form/access-control-array-form.component.ts
  src/app/shared/access-control-form-container/access-control-form-container.component.ts
Labels: bug, usability, component: administrative tools, port to dspace-8_x

#4169 [Port dspace-7_x] Fix export button enabled in bulk access management without selecting step 2
  src/app/access-control/bulk-access/bulk-access.component.spec.ts
  src/app/access-control/bulk-access/bulk-access.component.ts
  src/app/access-control/bulk-access/settings/bulk-access-settings.component.ts
  src/app/shared/access-control-form-container/access-control-array-form/access-control-array-form.component.ts
  src/app/shared/access-control-form-container/access-control-form-container.component.ts
Labels: bug, usability, component: administrative tools

#4179 [Port dspace-8_x] Store the state of the computed filters
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.ts
Labels: bug, high priority

#4189 Add additional automated server-side rendering (SSR) tests for all Entity Types
  .github/workflows/build.yml
Labels: 1 APPROVAL, testing framework, port to dspace-7_x, port to dspace-8_x

#4193 Fix: adding tooltips to indicate functionality of buttons when switching views of search results
  src/app/shared/view-mode-switch/view-mode-switch.component.html
Labels: usability, 1 APPROVAL, testathon

#4197 [Port dspace-7_x] Add additional automated server-side rendering (SSR) tests for all Entity Types
  .github/workflows/build.yml
Labels: 1 APPROVAL, testing framework

#2317 Update ESLint configuration for json5 files
  .eslintrc.json
Labels: i18n / l10n, port to dspace-7_x, port to dspace-8_x

#4210 [Port dspace-7_x] Update ESLint configuration for json5 files
  .eslintrc.json
Labels: i18n / l10n

#4215 Correct small typo in en.json5
  src/assets/i18n/en.json5
Labels: i18n / l10n, 1 APPROVAL

#4216 fix untyped item display in edit item modal
  src/app/shared/object-list/sidebar-search-list-element/item-types/publication/publication-sidebar-search-list-element.component.ts
Labels: bug, 1 APPROVAL, component: Item, testathon

#4219 Full update pl translations and minor changes in cz and uk translations
  src/assets/i18n/cs.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/uk.json5
Labels: i18n / l10n, 1 APPROVAL

#3968 Fix - previously entered qualdrop value field is deleted when adding a new (emtpy) line with the same(!) qualifier and then deleting it
  src/app/shared/form/form.component.ts
Labels: bug, component: submission, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#4240 Update Docker Compose scripts for Solr 9 compatibility
  docker/docker-compose-ci.yml
  docker/docker-compose-rest.yml
Labels: 1 APPROVAL, backend: Docker

#4231 Fix for double view events when using dynamic themes
  src/app/app-routes.ts
  src/app/collection-page/collection-page-routes.ts
  src/app/collection-page/collection-page.component.html
  src/app/collection-page/collection-page.component.ts
  src/app/community-page/community-page-routes.ts
  src/app/community-page/community-page.component.html
  src/app/community-page/community-page.component.ts
  src/app/home-page/home-page-routes.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.ts
  src/app/item-page/full/full-item-page.component.html
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/full/full-item-page.component.ts
  src/app/item-page/item-page-routes.ts
  src/app/item-page/simple/item-page.component.html
  src/app/item-page/simple/item-page.component.spec.ts
  src/app/item-page/simple/item-page.component.ts
  src/app/statistics/angulartics/dspace/view-tracker-resolver.service.ts
  src/app/statistics/angulartics/dspace/view-tracker.component.html
  src/app/statistics/angulartics/dspace/view-tracker.component.scss
  src/app/statistics/angulartics/dspace/view-tracker.component.ts
  src/app/statistics/angulartics/dspace/view-tracker.resolver.ts
  src/themes/custom/app/collection-page/collection-page.component.ts
  src/themes/custom/app/community-page/community-page.component.ts
  src/themes/custom/app/home-page/home-page.component.ts
  src/themes/custom/app/item-page/full/full-item-page.component.ts
  src/themes/custom/app/item-page/simple/item-page.component.ts
Labels: bug, component: statistics, themes, 1 APPROVAL

#4232 [Port to dspace-8_x] Fix for double view events when using dynamic themes
  src/app/app-routes.ts
  src/app/collection-page/collection-page-routes.ts
  src/app/collection-page/collection-page.component.html
  src/app/collection-page/collection-page.component.ts
  src/app/community-page/community-page-routes.ts
  src/app/community-page/community-page.component.html
  src/app/community-page/community-page.component.ts
  src/app/home-page/home-page-routes.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.ts
  src/app/item-page/full/full-item-page.component.html
  src/app/item-page/full/full-item-page.component.spec.ts
  src/app/item-page/full/full-item-page.component.ts
  src/app/item-page/item-page-routes.ts
  src/app/item-page/simple/item-page.component.html
  src/app/item-page/simple/item-page.component.spec.ts
  src/app/item-page/simple/item-page.component.ts
  src/app/statistics/angulartics/dspace/view-tracker-resolver.service.ts
  src/app/statistics/angulartics/dspace/view-tracker.component.html
  src/app/statistics/angulartics/dspace/view-tracker.component.scss
  src/app/statistics/angulartics/dspace/view-tracker.component.ts
  src/app/statistics/angulartics/dspace/view-tracker.resolver.ts
  src/themes/custom/app/collection-page/collection-page.component.ts
  src/themes/custom/app/community-page/community-page.component.ts
  src/themes/custom/app/home-page/home-page.component.ts
  src/themes/custom/app/item-page/full/full-item-page.component.ts
  src/themes/custom/app/item-page/simple/item-page.component.ts
Labels: bug, component: statistics, themes, 1 APPROVAL

#4233 [Port to dspace-7_x] Fix for double view events when using dynamic themes
  src/app/app-routing.module.ts
  src/app/collection-page/collection-page-routing.module.ts
  src/app/collection-page/collection-page.component.html
  src/app/community-page/community-page-routing.module.ts
  src/app/community-page/community-page.component.html
  src/app/home-page/home-page-routing.module.ts
  src/app/home-page/home-page.component.html
  src/app/item-page/full/full-item-page.component.html
  src/app/item-page/item-page-routing.module.ts
  src/app/item-page/simple/item-page.component.html
  src/app/statistics/angulartics/dspace/view-tracker-resolver.service.ts
  src/app/statistics/angulartics/dspace/view-tracker.component.html
  src/app/statistics/angulartics/dspace/view-tracker.component.scss
  src/app/statistics/angulartics/dspace/view-tracker.component.ts
  src/app/statistics/statistics.module.ts
Labels: bug, component: statistics, themes, 1 APPROVAL

#4242 Fix the last update to the Czech Translation
  src/assets/i18n/cs.json5
Labels: i18n / l10n, 1 APPROVAL

#4234 [DURACOM-350] fix cache issue after mydspace action
  src/app/shared/mydspace-actions/mydspace-actions.ts
  src/app/shared/mydspace-actions/mydspace-reloadable-actions.spec.ts
  src/app/shared/mydspace-actions/mydspace-reloadable-actions.ts
  src/app/shared/search/search-filters/search-filter/search-filter.component.ts
  src/app/shared/search/search-filters/search-filters.component.html
  src/app/shared/search/search-filters/search-filters.component.ts
Labels: bug, component: workflow, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#4192 Adjust unnecessary capitalization in English i18n strings
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: improvement, i18n / l10n, quick win, ux, affects: main

#4243 Add translation keys for journal submission volume lookup
  src/assets/i18n/en.json5
Labels: bug, i18n / l10n, testathon, port to dspace-7_x, port to dspace-8_x

#4212 Fix: prevent bitstream format cache issue by disabling cached version
  src/app/core/data/bitstream-data.service.spec.ts
  src/app/core/data/bitstream-data.service.ts
Labels: bug, performance / caching, 1 APPROVAL, component: Item, port to dspace-7_x, port to dspace-8_x

#4253 [Port dspace-7_x] Fix: prevent bitstream format cache issue by disabling cached version
  src/app/core/data/bitstream-data.service.spec.ts
  src/app/core/data/bitstream-data.service.ts
  src/app/item-page/edit-item-page/item-bitstreams/item-edit-bitstream-bundle/item-edit-bitstream-bundle.component.ts
Labels: bug, performance / caching, 1 APPROVAL, component: Item

#4225 [DURACOM-353] fix orejime callbacks
  src/app/shared/cookies/browser-orejime.service.spec.ts
  src/app/shared/cookies/browser-orejime.service.ts
Labels: bug, 1 APPROVAL

#4217 Several fixes to RSS component and object lists
  src/app/app-routes.ts
  src/app/collection-page/collection-page-routes.ts
  src/app/community-page/community-page-routes.ts
  src/app/home-page/top-level-community-list/top-level-community-list.component.html
  src/app/home-page/top-level-community-list/top-level-community-list.component.ts
  src/app/shared/object-collection/object-collection.component.html
  src/app/shared/object-collection/object-collection.component.ts
  src/app/shared/object-detail/object-detail.component.html
  src/app/shared/object-detail/object-detail.component.ts
  src/app/shared/object-list/object-list.component.html
  src/app/shared/object-list/object-list.component.ts
  src/app/shared/object-list/themed-object-list.component.ts
  src/app/shared/pagination/pagination.component.html
  src/app/shared/pagination/pagination.component.ts
  src/app/shared/rss-feed/rss.component.ts
  src/app/shared/search/search-results/search-results.component.html
Labels: bug, 1 APPROVAL, testathon, integration: syndication feed

#4276 Fix submission footer wrapping on medium screens
  src/app/submission/form/footer/submission-form-footer.component.html
Labels: bug, component: submission, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3892 UI warning for export item limit
  src/app/shared/search/search-export-csv/search-export-csv.component.html
  src/app/shared/search/search-export-csv/search-export-csv.component.spec.ts
  src/app/shared/search/search-export-csv/search-export-csv.component.ts
  src/app/shared/search/search-results/search-results.component.html
  src/assets/i18n/en.json5
Labels: improvement, high priority, tools: export, performance / caching, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#3888 Fixed search page still returning stale data after invalidating a request
  src/app/core/shared/search/search.service.spec.ts
  src/app/core/shared/search/search.service.ts
Labels: bug, component: Discovery, performance / caching, port to dspace-7_x, port to dspace-8_x

#4273 Fix missing input fields for integer script parameters
  src/app/process-page/form/process-parameters/parameter-value-input/number-value-input/integer-value-input.component.html
  src/app/process-page/form/process-parameters/parameter-value-input/number-value-input/integer-value-input.component.scss
  src/app/process-page/form/process-parameters/parameter-value-input/number-value-input/integer-value-input.component.spec.ts
  src/app/process-page/form/process-parameters/parameter-value-input/number-value-input/integer-value-input.component.ts
  src/app/process-page/form/process-parameters/parameter-value-input/parameter-value-input.component.html
  src/app/process-page/form/process-parameters/parameter-value-input/parameter-value-input.component.ts
  src/app/process-page/scripts/script-parameter-type.model.ts
  src/assets/i18n/ar.json5
  src/assets/i18n/bn.json5
  src/assets/i18n/ca.json5
  src/assets/i18n/cs.json5
  src/assets/i18n/de.json5
  src/assets/i18n/el.json5
  src/assets/i18n/en.json5
  src/assets/i18n/es.json5
  src/assets/i18n/fi.json5
  src/assets/i18n/fr.json5
  src/assets/i18n/gd.json5
  src/assets/i18n/hi.json5
  src/assets/i18n/hu.json5
  src/assets/i18n/it.json5
  src/assets/i18n/ja.json5
  src/assets/i18n/kk.json5
  src/assets/i18n/lv.json5
  src/assets/i18n/nl.json5
  src/assets/i18n/pl.json5
  src/assets/i18n/pt-BR.json5
  src/assets/i18n/pt-PT.json5
  src/assets/i18n/sr-cyr.json5
  src/assets/i18n/sr-lat.json5
  src/assets/i18n/sv.json5
  src/assets/i18n/sw.json5
  src/assets/i18n/tr.json5
  src/assets/i18n/uk.json5
  src/assets/i18n/vi.json5
Labels: bug, 1 APPROVAL, tools:processes

#4279 Fix bitstream tables being duplicated
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
Labels: bug, high priority, component: administrative tools, 1 APPROVAL, component: Item

#4281 [Port dspace-7_x] Fix bitstream tables being duplicated
  src/app/item-page/edit-item-page/item-bitstreams/item-bitstreams.component.ts
Labels: bug, high priority, component: administrative tools, 1 APPROVAL, component: Item

#4270 fixed flash and translate problems on statistics
  src/app/core/statistics/models/usage-report.model.ts
  src/app/statistics-page/statistics-table/statistics-table.component.html
  src/app/statistics-page/statistics-table/statistics-table.component.spec.ts
  src/app/statistics-page/statistics-table/statistics-table.component.ts
Labels: bug, usability, 1 APPROVAL, testathon

#4057 apply spellCheck configuration to input model
  src/app/shared/form/builder/parsers/onebox-field-parser.ts
Labels: improvement, 1 APPROVAL

#4272 German de.json5 additions, fixes and updates (port of https://github.com/DSpace/dspace-angular/pull/3980)
  src/assets/i18n/de.json5
Labels: i18n / l10n, 1 APPROVAL
